### ISSUE TITLE
Reference: Automatically document props

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/getkirby.com#1004]
Classes like [`Http\Uri`](https://getkirby.com/docs/reference/@/classes/http/uri/__construct) currently only document that there is a `$props` argument, but not what the possible props are.

All properties are documented in the code, so the reference could do something like this:

- Apply the following logic only if the current method is `__construct()` or `::factory()`.
- Check if the class uses the `Properties` trait with `class_uses()`. The check also needs to be made for all parent classes. If any class in the inheritance chain uses the trait, continue. Otherwise abort.
- Print a section on the reference page that lists all props of the class like in the [`Page` reference](https://getkirby.com/docs/reference/objects/page/__construct). Both public and protected/private props would need to be included, but not the internal `propertyData` property. Maybe we should add a new static `propertyNames()` method to the `Properties` trait for this (it could use `get_class_vars()`).

Once this is implemented, we would need to check which props are currently manually documented and move the documentation to the code to avoid duplication.

---

Based on a [discussion in Slack](https://app.slack.com/client/T2URU1Z6X/C2UTAQAN4/thread/C2UTAQAN4-1595838620.489500) with @nilshoerrmann.

**Comment by distantnative** [comment]
Ideally, we could also reference this in other doc pages than `__construct()`, `::factory()`, `::create()`...
Looking at: https://github.com/getkirby/getkirby.com/issues/1005

Basically a KirbyTag or something similar, where we can say: give me the props of this class and list them as values for `$myVariable`

Edit: Thinking a bit more about it, I am not even so sure if we can identify exact method names (`__construct()`, `::factory()`, `::create()`...) or whether such a KirbyTag, content field etc. would be the best solution also for these methods

**Comment by lukasbestle** [comment]
Yes, a KirbyTag would definitely be most flexible. Then we also wouldn't need to automatically determine whether the class uses the `Properties` trait. If the tag is used, the props are printed, boom.

**Comment by distantnative** [comment]
`(properties: $props)` which checks if it can get the classname out of the current page context. And `(properties: $props class: \Kirby\Http\Uri)` if we need to manually define it.

**Comment by lukasbestle** [comment]
@distantnative Sounds great!
