### ISSUE TITLE
Missing `empty` option for select fields

### ISSUE THREAD

**Issue by medienbaecker** [getkirby/getkirby.com#1006]
The select field properties are missing the `empty` option:
https://getkirby.com/docs/reference/panel/fields/select#field-properties

See this thread in the forum: https://forum.getkirby.com/t/select-with-no-empty-option/19037

**Comment by distantnative** [comment]
@medienbaecker since you are a user of `empty: false`, would be great to get your opinion in here https://github.com/getkirby/kirby/pull/3373 for why you use it, why your prefer it over `required` etc.

Thanks!

**Comment by distantnative** [comment]
Will be removed eventually https://github.com/getkirby/kirby/pull/6459
