### ISSUE TITLE
Optional mod_deflate module

### ISSUE THREAD

**Issue by afbora** [getkirby/getkirby.com#1013]
It would be great if [deflate lines](https://github.com/getkirby/getkirby.com/blob/master/www/.htaccess#L51-L53) are enclosed in `if` clause in .htaccess file. Because it didn't work in my local:

````php
<ifmodule mod_deflate.c>
    AddOutputFilterByType DEFLATE text/html
    AddOutputFilterByType DEFLATE text/css
    AddOutputFilterByType DEFLATE application/javascript
</ifmodule>
````

**Comment by distantnative** [comment]
✅
