### ISSUE TITLE
Search pagination not working properly

### ISSUE THREAD

**Issue by afbora** [getkirby/getkirby.com#1016]
Although 30 pages appear, it does not go beyond 20. Maybe there are 20 pages in total, not 30 pages, and it may be showing wrong.

### Steps to reproduce

1. Search "a"
2. Try to to page 21.
3. See the error

https://getkirby.com/search/page:20?q=a

**Comment by afbora** [comment]
I found the issue

> You can only fetch the 1000 hits for this query. You can extend the number of hits returned via the paginationLimitedTo index parameter or use the browse method. You can read our FAQ for more details about browsing: https://www.algolia.com/doc/faq/index-configuration/how-can-i-retrieve-all-the-records-in-my-index

**Comment by bastianallgeier** [comment]
✅
