### ISSUE TITLE
Add field methods aliases to the field methods in the Kirby refernces

### ISSUE THREAD

**Issue by janstieler** [getkirby/getkirby.com#1032]
Hi,
it would be nice if the alias field methods like

- [ ] 'bool'      => 'toBool',
- [ ] 'esc'        => 'escape',
- [ ] 'excerpt' => 'toExcerpt',
- [ ] 'float'      => 'toFloat',
- [ ] 'h'            => 'html',
- [ ] 'int'          => 'toInt',
- [ ] 'kt'           => 'kirbytext',
- [ ] 'kti'          => 'kirbytextinline',
- [ ] 'link'        => 'toLink',
- [ ] 'md'         => 'markdown',
- [ ] 'sp'          => 'smartypants',
- [ ] 'v'            => 'isValid',
- [ ] 'x'            => 'xml'

would also be described in the convenient field method.
Some of them I remember from K2. But I tried to search for `bool` in the reference but couldn't find something about.

Cheers,
jan

**Comment by distantnative** [comment]
@janstieler I guess this separates into two things:
- Mentioning the alias on the field method page itself (I think we can do that)
- Making these searchable (not as trivial)
  - would it be more helpful to bring up the main name (`toBool`) in the search
  - or should both appear as results and then lead to the same page?
