### ISSUE TITLE
Cache docs examples not working

### ISSUE THREAD

**Issue by MacGyer** [getkirby/getkirby.com#1039]
Just tried the steps to set up a custom cache by the doc pages (https://getkirby.com/docs/guide/cache).

Some information does not seem to be up-to-date.

### Config file name
https://getkirby.com/docs/guide/cache#cache-drivers-and-options__using-a-different-cache-driver
https://getkirby.com/docs/guide/cache#set-up-your-own-cache

It states `/site/config.php`. Shouldn't it be `/site/config/config.php`?

### Using remote data object
https://getkirby.com/docs/guide/cache#using-the-cache

```php
$apiData = Remote::get('https://someapi.com');
$apiCache->set('apiData', $apiData);
```

`$apiData` is the object returned by `Remote`. Trying to write the full object to cache results in an empty string (at least for file cache). As it is trying to `json_encode()` and `toArray()` and stuff like that.

The following works as expected:

```php
$apiData = Remote::get('https://someapi.com');
$apiCache->set('apiData', $apiData->content);
```

Same should then be changed here:

`$apiCache->set('apiData', $apiData->content, 30);`

Did I miss something?

Cheers

**Comment by bastianallgeier** [comment]
Thanks for spotting and reporting those! I just fixed them.
