### ISSUE TITLE
Image contains file upload which is missing in the code above.

### ISSUE THREAD

**Issue by tobscheeder** [getkirby/getkirby.com#1042]
It would be very interesting for beginners to see how the file upload is realized.

This is the file: content/1_docs/3_reference/3_panel/6_samples/0_events/event.png
This is the page: [https://getkirby.com/docs/reference/panel/samples/events](https://getkirby.com/docs/reference/panel/samples/events)

**Comment by texnixe** [comment]
The single event template uses `preset: page`, which automatically adds a files and a pages section, but the pages section is set to ` false`  in the example:
```
title: Event
preset: page
pages: false
```
