### ISSUE TITLE
Monolithic Plugin Setup docs may cause invalid plugin zip files

### ISSUE THREAD

**Issue by mauricerenck** [getkirby/getkirby.com#1056]
**Where:**
https://getkirby.com/docs/cookbook/setup/monolithic-plugin-setup

**What:**
In the section about the `.gitattributes` there is an example file including `src export-ignore`. Which may cause invalid packages.

**Why:**
Adding this line to the file will exclude **all** src folders from the automatically generated github zip-file. This may cause trouble when third party dependencies use a src in production. 

**Solution:**
Add a hint/note informing about that behavior or adapt the line so only the src folder on root level will be ignored (I don't know if that's possible)

**Comment by lukasbestle** [comment]
Thanks for pointing that out! I have tested it with a dummy repo – prepending a slash will tell Git to only match files on the top-level of the repo.
