### ISSUE TITLE
Add docs for 3.5.0

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/getkirby.com#1068]
🟨 = Added to the [Kirby 3.5 section](https://getkirby.com/v35/)
✅ = Documented on the `release/3.5.0` branch

| ✅ | Issue/Feature | Related PR | Assignees | Documenting Commit |
| :-- | :--| :-- | :-- | :-- |
| 🟨 | Blocks field | --- | @bastianallgeier | |
| 🟨 | Layouts field | --- | @bastianallgeier | |
| 🟨 | List field | --- | @bastianallgeier | |
| 🟨 | Writer field | --- | @bastianallgeier | |
| | New `logs` root | https://github.com/getkirby/kirby/pull/2875 | @distantnative | |
| | Help option for headline + info fields | https://github.com/getkirby/kirby/pull/2898 | @distantnative | |
| 🟨 | Improvements to date & time fields | https://github.com/getkirby/kirby/pull/2892 | @distantnative | |
| | Page create dialog: hide single template select | https://github.com/getkirby/kirby/pull/2899 | @distantnative | See PR https://github.com/getkirby/getkirby.com/pull/1069 |
| 🟨 | Reset password view | https://github.com/getkirby/kirby/pull/2916 | @lukasbestle | |
| | Locale option: Support for all locale formats (array/string) | https://github.com/getkirby/kirby/pull/2895 | @lukasbestle | |
| 🟨 | Themeable login form | https://github.com/getkirby/kirby/pull/2929 | @lukasbestle | |
| 🟨 | Passwordless login & 2FA | https://github.com/getkirby/kirby/pull/2923 https://github.com/getkirby/kirby/pull/2934 https://github.com/getkirby/kirby/pull/2939 | @lukasbestle | |
| | More detailed accept options for file blueprints | https://github.com/getkirby/kirby/pull/2973 | @lukasbestle | |
| | Add note about using `$app->clone()` to plugin docs | https://github.com/getkirby/kirby/pull/2894 | @lukasbestle | |
| | Impersonation as `nobody` | https://github.com/getkirby/kirby/pull/2882 | @lukasbestle | |
| | PHP support: 7.3-8.0 (dropped 7.2) | https://github.com/getkirby/kirby/pull/2957 | @lukasbestle | |
| | Check Panel docs for outdated screenshots | ---- | @bastianallgeier @distantnative | |
| | New UI kit components | ---- | @bastianallgeier @distantnative | |

**Comment by bastianallgeier** [comment]
Awesome to have such a list!

**Comment by lukasbestle** [comment]
Moved to #1079.
