### ISSUE TITLE
Code toolbar button preventing selection

### ISSUE THREAD

**Issue by moevbiz** [getkirby/getkirby.com#1070]
When trying to select only a fragment of a one-liner `code-toolbar` for copy-pasting, the "Copy"-button sometimes gets in the way:

<img width="615" alt="Screenshot 2020-11-26 at 10 20 35" src="https://user-images.githubusercontent.com/38008341/100333026-65a6cd00-2fd2-11eb-912c-755fe772bdef.png">
<img width="620" alt="Screenshot 2020-11-26 at 10 20 48" src="https://user-images.githubusercontent.com/38008341/100333032-66d7fa00-2fd2-11eb-89e8-836cbebcce16.png">

A `padding-right: 100px` on `.code>code` could be added to prevent this.

<img width="563" alt="Screenshot 2020-11-26 at 10 29 07" src="https://user-images.githubusercontent.com/38008341/100333612-18772b00-2fd3-11eb-8904-ee740800c383.png">
<img width="561" alt="Screenshot 2020-11-26 at 10 29 34" src="https://user-images.githubusercontent.com/38008341/100333614-190fc180-2fd3-11eb-9a0b-0b2615e8a992.png">

While at it, moving the `margin-bottom` from the `code` element to its parent `.code-toolbar` prevents the box shadow on the "Copy" button from overflowing, though I don't know if this might have unwanted layout changes somewhere else.

<img width="552" alt="Screenshot 2020-11-26 at 11 35 32" src="https://user-images.githubusercontent.com/38008341/100340444-832c6480-2fdb-11eb-8d2f-c509d6357ec5.png">

**Comment by distantnative** [comment]
We are currently in the process of refactoring our JS and CSS setups. Once we have that done, we'll take a look at this 👍

**Comment by distantnative** [comment]
@moevbiz The suggested padding-right fix works good for one-line code blocks. But for many lines where not the firs tone is the longest, it looks very odd that a scrollbar gets added for just scrolling into more black background.

**Comment by moevbiz** [comment]
You're right. Maybe it would make sense to add this only to one-liners, since a block with many lines in most cases begins with something like `<?php` – not an overflow right in the first line.

**Comment by distantnative** [comment]
We'll have a solution for this soon
