### ISSUE TITLE
Guide page for hooks

### ISSUE THREAD

**Issue by sebastiangreger** [getkirby/getkirby.com#1132]
Unless I overlooked something (checked https://getkirby.com/docs/reference/system/options/hooks , https://getkirby.com/docs/reference/plugins/hooks and the Guide and Cookbook), it appears that the new-ish wildcard hooks are not yet documented apart from the [3.4.0 release notes](https://github.com/getkirby/kirby/releases/tag/3.4.0).

**Comment by distantnative** [comment]
They are here
https://getkirby.com/docs/reference/plugins/extensions/hooks#registering-hooks
(a little below where it links)

But agreed, that info is currently too scattered.
I think all the main information should live in https://getkirby.com/docs/reference/system/options/hooks and then https://getkirby.com/docs/reference/plugins/extensions/hooks should only show how to register in a plugin and link to the option reference page.

**Comment by lukasbestle** [comment]
The page [about the hooks option](https://getkirby.com/docs/reference/system/options/hooks) currently links to this page: https://getkirby.com/docs/reference/plugins/hooks for more information. And I think this is where all the information belongs. So IMO we should move most of the docs from https://getkirby.com/docs/reference/plugins/extensions/hooks to https://getkirby.com/docs/reference/plugins/hooks and then link to that page from the hooks extension page.

**Comment by distantnative** [comment]
Did we just suggest the same @lukasbestle? Or I don't see the difference in your comment 😆 Before doing it wrong

**Comment by lukasbestle** [comment]
@distantnative Not quite. You suggested to put the info on https://getkirby.com/docs/reference/system/options/hooks and I suggested to put it on https://getkirby.com/docs/reference/plugins/hooks. The second is the more general page about hooks, while the first is just a page about one way to register them (and it also already links to the second page).

**Comment by distantnative** [comment]
Ah now I got it, thanks. I. An see both. I didn't go for this overview page as I think those won't get any table of contents even when they get longer.

**Comment by lukasbestle** [comment]
@distantnative That's a good point. But then we should also move the details from the overview page to the page we decide on. I don't like that the information is so scattered across the reference.

Or maybe we could add a TOC to the overview page? Don't we have a `(toc:)` KirbyTag for that?

**Comment by distantnative** [comment]
Maybe it would be good to actually create a guide page for hooks, explaining how they work and can be used. So that the different reference pages really just list all the type of hooks as well as ways to register one. What do you think?

**Comment by lukasbestle** [comment]
Good idea! That's much better.
