### ISSUE TITLE
Tag for local video embeds

### ISSUE THREAD

**Issue by distantnative** [getkirby/getkirby.com#1149]
Would be needed for finally (!) merging this great recipe: https://github.com/getkirby/getkirby.com/pull/947

**Comment by afbora** [comment]
@distantnative #1188 ?

**Comment by distantnative** [comment]
@afbora I think so yes! Maybe you can try to update/fork the PR and put your new tag to work?

**Comment by afbora** [comment]
@distantnative You mean updating the `First stab at a Backups recipe` PR, right?

**Comment by distantnative** [comment]
Yes :) It already includes the mp4 files but int he content file only mentions them, e.g. ``backups-07.mp4``
