### ISSUE TITLE
Algolia: JS and PHP results don't match

### ISSUE THREAD

**Issue by distantnative** [getkirby/getkirby.com#1175]
<img width="539" alt="Screen Shot 2021-01-16 at 10 31 30" src="https://user-images.githubusercontent.com/3788865/104808378-0a30d880-57e6-11eb-94e0-3a93829635fe.png">

<img width="1162" alt="Screen Shot 2021-01-16 at 10 31 34" src="https://user-images.githubusercontent.com/3788865/104808379-0c933280-57e6-11eb-9918-7fac58efe5ad.png">

**Comment by distantnative** [comment]
Source of issue: https://github.com/getkirby/getkirby.com/blob/242d03478e20efd829947a3b5221c91a534488c3/site/controllers/search.php#L18

@bastianallgeier Should we remove it, so that the PHP result page shows the same (fuzzy) results as the JS search?

**Comment by lukasbestle** [comment]
I think so. It's weird to get different results after pressing <kbd>Enter</kbd>.
