### ISSUE TITLE
[develop] Cachebusting of JS modules

### ISSUE THREAD

**Issue by distantnative** [getkirby/getkirby.com#1187]
While the directly called JS and CSS assets get loaded with a `?v=...` query, imports, e.g. JS modules don't get the same treatment. We should investigate if we need further methods to trigger a fresh load from server when an asset file has changed.

**Comment by distantnative** [comment]
Most what I find
`ETag` and `max-age`
https://stackoverflow.com/questions/47675549/how-do-i-cache-bust-imported-modules-in-es6/56801858#56801858

Or manually including version numbers in JS module file names.

**Comment by johannschopplich** [comment]
Pardon me for jumping on board of this discussion.

Advocating filename-based options, I have tried different solutions over the past year. Laravel Mix with webpack under the hood is just absolute overkill in my opinion. I've migrated to Rollup in between and now happily landed with a simple and straightforward solution:
- Sass files (main entry point and templates) are handled by [dart-sass](https://sass-lang.com/documentation/cli/dart-sass) – it's CLI will be called directly from a npm script
- JavaScript assets are handled [with a script utilizing ESBuild](https://github.com/johannschopplich/plainkit-hashed-assets/blob/master/scripts/incrementalEsbuild.js) (with chokidar watching for file-changes in development environment)
- building for production all `assets/{css,js}/**/*.{css,js}` files get hashed [by a straightforward script generating](https://github.com/johannschopplich/plainkit-hashed-assets/blob/master/scripts/hashAssets.js) a `manifest.json` in the process

I enjoy this easy to grasp setup. Maybe you'll be interested in it, too? I prefer less overhead in contrast to introducing another way to cache bust, such as HTTP headers you've linked. 

In the end, the build scripts stay reasonable:

```json
"scripts": {
  "assets:clean": "shx rm -rf public/assets/{css,js}",
  "assets:hash": "node scripts/hashAssets.js",
  "sass:main": "sass --style=compressed src/scss/main.scss public/assets/css/main.css",
  "sass:templates": "sass --style=compressed src/scss/templates:public/assets/css/templates",
  "esbuild": "node scripts/esbuild.js",
  "dev": "concurrently \"npm run sass:main -- --embed-source-map --watch\" \"npm run sass:templates -- --embed-source-map --watch\" \"npm run esbuild\"",
  "build": "npm run assets:clean && npm run sass:main -- --no-source-map && npm run sass:templates -- --no-source-map && NODE_ENV=production npm run esbuild && npm run assets:hash"
}
```

All left to do is to output the hashed filename by the `css()` and `js()` helpers, for which I've [created a plugin](https://github.com/johannschopplich/kirby-hashed-assets).

Dynamically imported chunks (apart from Node modules) are cache-busted by ESBuild by default. 

The only downside of ESBuild is that dynamic imports with variables or template literals [don't work at the time writing](https://github.com/evanw/esbuild/issues/16). But the creator of the plugin plans to introduce them. Therefore your dynamic component imports would't work and have to be rewritten... This is my current implementation of writing plain components:

<details><summary><strong>MediumZoom component with dynamic import</strong></summary>

```js
export default class {
  constructor () {
    const isMobile = !matchMedia('(min-width: 768px)').matches
    const elements = [...document.querySelectorAll('[data-zoomable]')]

    if (!isMobile && elements.length !== 0) {
      this.init(elements)
    }
  }

  async init (elements) {
    const { default: mediumZoom } = await import('medium-zoom')
    mediumZoom(elements, {
      background: 'var(--color-background)'
    })
  }
}
```
</details>

**Comment by distantnative** [comment]
Thanks for chiming in @johannschopplich.
The reality is we are trying to move away completely from a build process. Or let's say almost completely. we have switched our setup to be without a build process or bundling locally. Vanilla CSS, no SASS anymore. JS modules. That's it. And it feels so good.

For remotely, we had to add a little build script on that only minifies JS and concats CSS files into one (or rather one main one and template-specific ones). 

It all works quite well so far and is very liberating. But I realized caching of the JS component modules (not the main files, they are taken care of by calling via `?v=...`) could be an issue. So looking for a solution that doesn't lead us down the build and bundling path again.

**Comment by lukasbestle** [comment]
We could inject the version hashes of all files that could be loaded from a `<script>` tag in the template. The loader in the frontend could then pick up the the hashes dynamically. We could use quite short hashes for this, but the question is still whether this is viable depending on the number of files that would need to be included in the list.

**Comment by distantnative** [comment]
That could be a way, though it feels quite the long stretch (maybe there isn't a cleaner way).

@lukasbestle my knowledge of Etag etc is limited. But could that be an option? It sounds at least as if it could be a "once set up after that really easy" solution - maybe?

**Comment by johannschopplich** [comment]
@distantnative Thanks for the explanation. Indeed, that sounds great. Looking forward to explore the new setup.

**Comment by lukasbestle** [comment]
@distantnative The issue with `ETag` is that the browser still needs to revalidate the cache all the time, meaning it still needs to make a request and ask if the `ETag` has changed since the last request. This introduces latency that can be avoided with a strict "cache this URL forever" cache policy. I read that `ETag` is not recommended for assets, but more for larger file downloads in API contexts etc.

**Comment by lukasbestle** [comment]
I think we should also switch from a `?v=...` query string to the version identifier directly in the file path. URLs with query strings are sometimes not cached by browsers at all.

**Comment by distantnative** [comment]
@lukasbestle Just trying to find a solution that doesn't lead us down the building process path again and that doesn't overly complicate the actual asset files

**Comment by lukasbestle** [comment]
Absolutely.

I think the global list of available files in JSON format inside a `<script>` tag could work well unless we plan to have dozens of modules.

The backend would only need to print the JSON in the template and that would be it.

**Comment by bastianallgeier** [comment]
I think this is actually quite critical before we merge the develop branch. Keep in mind that we are hosting JS and CSS files on a CDN. With the next change we will already run into this issue. 

I like the idea of a JSON object but we should also check if it doesn't make sense to merge everything back into a single index.js in the build process instead – like with the index.css. This would definitely simplify this.

**Comment by lukasbestle** [comment]
Yep, that would be even better if the resulting JS file would still be small enough and wouldn't contain template-specific code for all templates.

**Comment by bastianallgeier** [comment]
We already separate template specific code and to be honest I'm even thinking about inlining template specific JS in the new version.

**Comment by distantnative** [comment]
Wouldn't that duplicate the code of utils etc. used by template JS files and the main JS file?

**Comment by distantnative** [comment]
And I guess we have the issue locally kinda too...
so back to build process and bundlers? 🙈🙈🙈

**Comment by distantnative** [comment]
@bastianallgeier also not sure if inlining will be great in the long term. Keeping the JS in readable modules is a big benefit of understanding the code as a team where not all of us deal with all of the site most of the time. 

It's one of the things I fear with the mix of tailwind and normal CSS classes - I'm sure it makes a lot of sense to your right now and for the future. But will it be as easily understandable for others jumping in if it doesn't follow a clear pattern but jumps between those worlds? Maybe it's not an issue but something I thought about

**Comment by distantnative** [comment]
I'd prefer @lukasbestle JSON map, honestly. Might look a bit stupid in code but better than down the bundler hole again


Something like

```js
// generated via PHP
window.scripts = {
  "utils/load": "utils/load.js?v=343843"
};
```

```js
// in the JS module files
import { component } from "../" + window.scripts["utils/load"];
```

> I think we should also switch from a `?v=...` query string to the version identifier directly in the file path. URLs with query strings are sometimes not cached by browsers at all.

I think that could be done if the small build step just adds in a version identifier when minimizing the JS.

**Comment by lukasbestle** [comment]
> Wouldn't that duplicate the code of utils etc. used by template JS files and the main JS file?

The template JS files could access the global utils. Or if we inline everything in the production build, it doesn't really matter.

> And I guess we have the issue locally kinda too...
> so back to build process and bundlers? 🙈🙈🙈

If we only do it in production and not locally, I'd say it's fine. We need to minify the files anyway, so we might as well bundle them.

**Comment by distantnative** [comment]
Bundlers don't recognize the current optional component module loading setup... ugh.
And increasing the load also for pages that don't require all omponents, e.g. code highlighting.
This really feels like so many steps backwards.

> so we might as well bundle them.

The thing is, minifying is quite straight forward and low tech. Add bundlers and the world starts to burn 😰

**Comment by lukasbestle** [comment]
True. :)
