### ISSUE TITLE
Errors in login methods template

### ISSUE THREAD

**Issue by sylvainjule** [getkirby/getkirby.com#1217]
I'd have PRed the emendations, but not sure how updating my whole fork would interfere on the other PR it's linked to, so I'm just mentioning them here. On this page:

https://getkirby.com/docs/guide/authentication/login-methods

The template examples  are in "i18n format" and won't work, `{user.nameOrEmail}` is rather `<?= $user->nameOrEmail() ?>`, and so on.

**Comment by lukasbestle** [comment]
Thanks for spotting! I think we added it like this on purpose back then (before the 3.5 release), but in the docs it makes a lot more sense to provide the examples so that they can be copied to custom templates straight away.
