### ISSUE TITLE
Wrong return types for classes inheriting Kirby\Toolkit\Collection

### ISSUE THREAD

**Issue by distantnative** [getkirby/getkirby.com#1223]
In many places in `Kirby\Toolkit\Collection` we have defined the return type as `Kirby\Toolkit\Collection` while it should `self`. Because of that e.g. `$pages->map()` shows `Kirby\Toolkit\Collection` as return type but should show `Kirby\Cms\Pages`

**Comment by distantnative** [comment]
@lukasbestle Need your knowledge here.

If I read https://docs.phpdoc.org/3.0/guide/guides/types.html correctly we should actually change a lot

- `self` when we mean the class where the method was defined
- `static` when we mean the class where the method is called on
- `$this` when we mean the actual instance

Do you understand it that way was well? Would we run in conflict with conventions Psalm or so use?

**Comment by lukasbestle** [comment]
@distantnative I agree, in most places we should probably use `$this` as we often return the same instance. `static` would make sense for all methods that return a new instance using `new static()` and `self` would be reserved for the few cases that actually only ever return a specific class instance.

As far as I know, Psalm will understand all these variants as they are meant.

**Comment by distantnative** [comment]
Ok, I will give it a go. Thanks!

**Comment by distantnative** [comment]
@lukasbestle couldn't this also help us to automatically determine what methods are immutable (returning `$this` vs. `static`/`self`)?

**Comment by lukasbestle** [comment]
Yes, that would be a nice side-effect actually.

**Comment by distantnative** [comment]
✅ Will be solved when new Kirby version is released.
