### ISSUE TITLE
Unify field names

### ISSUE THREAD

**Issue by distantnative** [getkirby/getkirby.com#1224]
It would help our code base if we could unify the content field names, mainly `excerpt`, `intro` and `description`.
Really no priority but maybe a lazy project.

**Comment by distantnative** [comment]
@bastianallgeier this should still be done

**Comment by bastianallgeier** [comment]
I thought we already eliminated most places. Ok, then let's keep it open :)

**Comment by distantnative** [comment]
we are currently using `excerpt` a lot in the Reference, `intro` a lot in guide and other pages, `description` in some other places and for meta.

I feel like this should all be one, shouldn't it?

**Comment by bastianallgeier** [comment]
Excerpt and intro yes! Description should be used for the meta tag only.
