### ISSUE TITLE
Plugins: support branches not called `master`

### ISSUE THREAD

**Issue by distantnative** [getkirby/getkirby.com#1228]
for download links

**Comment by bastianallgeier** [comment]
I think we should introduce a new field to determine the right branch.

**Comment by bastianallgeier** [comment]
Or link to releases instead.

**Comment by lukasbestle** [comment]
At least for GitHub we can use this link format for a ZIP download of the default branch, whatever that is configured to: https://docs.github.com/en/rest/reference/repos#download-a-repository-archive-zip
