### ISSUE TITLE
Version-specific docs

### ISSUE THREAD

**Issue by distantnative** [getkirby/getkirby.com#1231]
@lukasbestle 

Thought I start this issue as a place to collect thoughts

- select dropdown for versions (major? All minor?). Sets session. Default without session is current version.
- new <version from="" to=""> tag to display/hide docs sections based on the selected version
- everything we generate automatically from parsing files and reflections, we would need to generate and store for each versions since we can't import the same class from an older version that the site itself needs to run
- since we might come up with new features that need more information, we should save the rawest information, e.g. all reflectionclass information
- we probably have to write our own toArray/toJSON methods for these
- our page models would then rather load the json files 

Open questions:
- is this harmful because we reduce discoverability for new/old documented features?

**Comment by lukasbestle** [comment]
> select dropdown for versions (major? All minor?)

I'd say the latest minor version for each major version. Sometimes we add features in minor versions that get their own `<since>` blocks, so they should definitely be respected. But given that we don't have breaking-changes in minor versions, we can expect users to always use the latest minor version of that major version. Offering every single version will IMO make it all too complex and confusing.

> Sets session. Default without session is current version.

I'm for a simple cookie. Then we don't need to worry about server-side storage.
Maybe we could even include the version in the URL for easier sharing.

> new tag to display/hide docs sections based on the selected version

Somewhere we already discussed this and my idea was something like `<version from="..." to="...">`.

> since we might come up with new features that need more information, we should save the rawest information, e.g. all reflectionclass information

I don't think we need to. If we really need additional info later, we can still regenerate the data files for the old versions.

> is this harmful because we reduce discoverability for new/old documented features?

We should have a clear info box at the top of each page that shows up when an outdated version is selected. As long as we have that, users will always know which version they are looking at. Removed features are not really relevant when reading the latest docs for the version you are actually using and added features will only be in the latest docs the info box will point to.

**Comment by distantnative** [comment]
New plan:

- Each version has its own branch 3.5, 3.6 etc. 
- When we start working on the docs of a new version, we already start the branch for it. Just like we currently do with the 3.6 branch
- As soon as the release is out, the 3.6 branch will become main and main will become 3.5
- 3.5 will be deployed as a new redundant version on our domainfactory server. It's separate from the main webserver and already hosts the docs for 1 and 2. 
- The new 3.5 branch will get its own domain-specific config file, telling the instance that it is outdated. This would activate the router that redirects everything outside the docs folder to getkirby.com 
- The deploy script would also remove everything inside the content folder except an allow list, e.g. the site.txt, the docs folder and menu-relevant pages (but remove any children - just keeping them as shell).
- Add a config file with available versions and a select UI to switch between versions
- Add the version number to the header of the rest of the docs as well

**Comment by bastianallgeier** [comment]
What are the open todos for this? Where can I help best?

**Comment by distantnative** [comment]
- Search: currently we use the index from the main page. I would think this might be sufficient as the main information will match between versions. Missing pages in e.g. v3.5 will be redirected to current version already. But of course it's a bit off, though reworking our integration with multiple split indexes (between docs and rest) seems a lot of work. Not Sur eif worth it.
- UI: How do we make the different docs versions available?
- Process: how do we start a pre-release, what happens at release with the branches, what manual steps need to be done each time a current version is copied over as an old version?

**Comment by bastianallgeier** [comment]
- Search: I think we can keep this as an optimization step for later. Too much work for the launch
- UI: I will have a look at that
- Process: let's keep it as simple as possible for now. We can keep it manual for most parts

**Comment by distantnative** [comment]
On process: didn't mean to automate it, meant we should write it down somewhere so that when 3.7 comes around we know what to do

**Comment by bastianallgeier** [comment]
I totally agree. I think we should also find a good subdomain pattern for the versions. k1.getkirby.com and k2.getkirby.com are not really good. I'd prefer something like vX.X.getkirby.com

I.e:

- v1.1.getkirby.com
- v2.5.getkirby.com
- v3.5.getkirby.com
- v3.6.getkirby.com

Or just

- 1.1.getkirby.com
- 2.5.getkirby.com
- 3.5.getkirby.com
- 3.6.getkirby.com

**Comment by distantnative** [comment]
Could the dots cause problems?

Another option
- docs-3.5.getkirby.com
- docs-3.6.getkirby.com
- docs-3.7.getkirby.com

**Comment by lukasbestle** [comment]
With the dots the semantics get turned around. E.g. in the example `v3.6.getkirby.com`, `v3` is a subdomain of `6.getkirby.com`.

This syntax would solve that:

- v11.getkirby.com
- v25.getkirby.com
- v35.getkirby.com
- v36.getkirby.com

...but it would cause problems once we have v3.10 or higher.

Alternatively maybe this:

- v1-1.getkirby.com
- v2-5.getkirby.com
- v3-5.getkirby.com
- v3-6.getkirby.com

Or we turn it around:

- v1.getkirby.com -> Redirects to 1.v1.getkirby.com
- v2.getkirby.com -> Redirects to 5.v2.getkirby.com
- v3.getkirby.com -> Redirects to getkirby.com
- 5.v3.getkirby.com
- 6.v3.getkirby.com
- etc.

**Comment by distantnative** [comment]
✅
