### ISSUE TITLE
Docs: Broken link to WordPress exporter

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/getkirby.com#126]
From flobin on the Kirby forum:

> Just thought I should let someone know that on the [blog import page](http://getkirby.com/docs/solutions/blog/import-articles) the link to the internal resource, "Export all your WordPress articles to Kirby" is broken. Hope this helps.

**Comment by texnixe** [comment]
The exporter is quite old, does it work with Kirby 2 or should those links be removed or the exporter updated?

**Comment by lukasbestle** [comment]
I haven't tried to use it with Kirby 2 yet, so yes, that's the question. ;)

**Comment by foobartel** [comment]
@texnixe It seems the exporter only worked with Kirby 1. I have tried it and the include path differs from the new structure and when changed, it throws another error. 
Also it's hosted in https://github.com/bastianallgeier/kirbycms-extensions which states "This is the repository for old Kirby 1 extensions.", so I believe it's outdated.

**Comment by texnixe** [comment]
What do we want to do with this link? Remove it completely or leave it as a source for people who may want to update the importer? Then we should at least make a note that the importer was developed for Kirby one. What do you think?

**Comment by lukasbestle** [comment]
I'm for removing it completely. If we keep all the Kirby 1 stuff, the docs will become quite bloated over time.
If anyone asks for it in the forum, we can point them to the old code.

**Comment by texnixe** [comment]
https://github.com/getkirby/getkirby.com/pull/231
