### ISSUE TITLE
Typo in Docu?

### ISSUE THREAD

**Issue by fritzlaszlo** [getkirby/getkirby.com#1263]
heya,

not sure how currently the reference documentation is generated, so I am opening an issue for this little error:

the default code snippet for the panel/blocks/text is missing an end:
[https://getkirby.com/docs/reference/panel/blocks/text](https://getkirby.com/docs/reference/panel/blocks/text)

**Comment by distantnative** [comment]
Not really, if you look at the file https://github.com/getkirby/kirby/blob/master/config/blocks/text/text.php it is how it ends.
Since the file is ending, the closing `?>` has been omitted/isn't necessary.

**Comment by lukasbestle** [comment]
We have omitted the end tag to avoid additional whitespace output that could cause issues down the road.

For the snippet it's not that critical, but in general it is, which is why our coding style analyzer would flag the end tag as incorrect.
