### ISSUE TITLE
CMD+- brings up search bar

### ISSUE THREAD

**Issue by distantnative** [getkirby/getkirby.com#1274]
Tested on macOS 11.2.2 with Firefox/Chrome/Safari

**Comment by distantnative** [comment]
@texnixe  what's your keyboard layout? German QWERTZ?

**Comment by afbora** [comment]
Might help: https://keycode.info/

**Comment by ralfgoeke** [comment]
I can confirm this bug with a German QWERTZ layout (MacBook Pro).

**Comment by distantnative** [comment]
@texnixe @ralfgoeke could you please use the tool Ahmet posted and let me know what the different even variables values are?

**Comment by ralfgoeke** [comment]
**command**
event.key: Meta
event.location: 1
event.which: 91
event.code: MetaLeft

**minus**
event.key: -
event.location: 0
event.which: 189
event.code: Slash

**Comment by texnixe** [comment]
minus
event.key: -
event.location: 0
event.which: 173
event.code: Slash

Command
event.key: Meta
event.location: 1
event.which: 224
event.code: OSLeft

**Comment by distantnative** [comment]
@afbora I think we have added the second part of `e.key === "/" || e.code === "Slash"` because of your experience (I think for you just checking `e.key` wasn't sufficient). So could you please also post the info you get for `/` as well as for `-`?

**Comment by afbora** [comment]
### For search

Slash Numpad
```
event.key: /
event.location: 3 (Numpad)
event.which(deprecated): 111
event.code: NumpadDivide
```

Slash Alternative
```
event.key: ":"
event.location: 0 (General keys)
event.which(deprecated): 190
event.code: Slash
```

### For zoom (CTRL +/-)

CTRL
```
event.key: Control
event.location: 1 (Left-side modifier keys)
event.which(deprecated): 17
event.code: ControlLeft
```

Plus
```
event.key: +
event.location: 3 (Numpad)
event.which(deprecated): 107
event.code: NumpadAdd
```

Minus
```
event.key: -
event.location: 3 (Numpad)
event.which(deprecated): 109
event.code: NumpadSubtract
```

**Comment by distantnative** [comment]
Which key is `Slash Alternative`?

**Comment by afbora** [comment]
`:` :)

**Comment by afbora** [comment]
I guess issue about line that `(e.target === document.body && withSlash)`, right?

**Comment by distantnative** [comment]
It's this one: https://github.com/getkirby/getkirby.com/blob/main/assets/js/components/search.js#L41
`e.code === "Slash"` is triggered for the others when using `Ctrl` and `-`.

But I think we can just get rid of it. You regular slash also matches `e.key === "/"` - so we might just go with that one.

@sonja @ralfgoeke can you confirm, that slash results in `e.key === "/"` for you too?

**Comment by afbora** [comment]
What about if we exclude minus?

````js
const withSlash = (e.key === "/" || e.code === "Slash") && e.key !== "-";
````

**Comment by distantnative** [comment]
But do we actually need `e.code === "Slash"`?

**Comment by afbora** [comment]
Actually, it looks like there is no need. We can add it again according to feedback from users.

**Comment by ralfgoeke** [comment]
@distantnative yep, slash is e.key === "/"
