### ISSUE TITLE
Fix .htaccess to be used with Valet locally

### ISSUE THREAD

**Issue by distantnative** [getkirby/getkirby.com#1287]

**Comment by lukasbestle** [comment]
My Caddy setup doesn't support .htaccess at all, so I'd be grateful for a solution that supports a Kirby routing fallback.

**Comment by trych** [comment]
Quick question, as I am trying to serve the site locally with valet as well, without having any success. What exactly would I need to change with the `.htaccess` to make it work?

**Comment by texnixe** [comment]
@trych Valet uses nginx not Apache, so the `.htaccess` is of no use.

**Comment by trych** [comment]
@texnixe Ok, but what else might be the reason the local serving does not work via Valet? I get a `502 Bad Gateway` error.

**Comment by lukasbestle** [comment]
@trych The current implementation uses a pretty standard setup actually, there's nothing special in `.htaccess` that you would need for Valet.

`502 Bad Gateway` sounds more like a PHP issue to be honest (nginx not being able to connect to the PHP socket). Have you checked if other sites served via Valet work?

**Comment by trych** [comment]
@lukasbestle I was gonna post something like "of course my other sites work", but ... you are right, all my valet sites are down right now. 😔 I think there was something going wrong brew updating my stuff yesterday. Will see if I can get it fixed. Thanks for the pointer in the right direction!
