### ISSUE TITLE
Screencasts: embed gets overlaid by text column

### ISSUE THREAD

**Issue by distantnative** [getkirby/getkirby.com#1288]
Starts sliding below text on narrow windows:

<img width="696" alt="Screen Shot 2021-04-15 at 22 34 21" src="https://user-images.githubusercontent.com/3788865/114934913-d4c67600-9e3a-11eb-8108-22cdbacc9628.png">

**Comment by bastianallgeier** [comment]
I don't think we can fix this at all tbh.

**Comment by distantnative** [comment]
I think we can mitigate it a bit more by earlier switching from columns to rows. Maybe even hiding the normal paragraph at a certain size to reserve the space for the headline.

But yes we won't fully avoid it
