### ISSUE TITLE
Sales banner throughout the site

### ISSUE THREAD

**Issue by distantnative** [getkirby/getkirby.com#1291]
Shouldn't we show it throughout the side (maybe not Reference) and not just on home?

With the automatic dates, this could be a caching problem.
But isn't that already on home?

**Comment by lukasbestle** [comment]
Regarding caching see #1296.

**Comment by bastianallgeier** [comment]
I think it's annoying to have it everywhere. We'd at least need a way to close it and then not show it again, but this would bring us back into cookie and flicker land.

**Comment by distantnative** [comment]
We just shouldn't think that most people will enter our website through home. But a link to the guide or so.

I honestly don't feel like that little banner (which isn't fixed even) would be as intrusive that you need to make it hidable.

**Comment by bastianallgeier** [comment]
You might be right. The "shy marketing mind" is speaking over here again 🤣

**Comment by lukasbestle** [comment]
I agree with Nico. Most people will land on a cookbook article that's linked from somewhere or they navigate through some guide pages someone sent them. I think the new styling is pretty unobtrusive.

From the technical side it's going to be very easy, I already have a new version almost ready. ETA tonight. :)

**Comment by bastianallgeier** [comment]
✅

**Comment by distantnative** [comment]
@bastianallgeier this isn't actually solved, the PR is still open (and stuck due to the core requirement)

**Comment by bastianallgeier** [comment]
That's true, but the issue itself is solved for now. The PR still has other open issues that stay open. That's why I thought it makes sense to close this one. Unless we mess up the PR when we finally merge it, this one should stay closed, right?

**Comment by distantnative** [comment]
Oh sorry true, i didn't realize it's now an each page 😅
