### ISSUE TITLE
Show ongoing sale on `buy` page

### ISSUE THREAD

**Issue by distantnative** [getkirby/getkirby.com#1292]
To make also clear that the currently displayed price isn't the regular price. Avoiding bad surprises if someone saw the price the first time during a sale, didn't realise it and comes back after the sale.

**Comment by distantnative** [comment]
@bastianallgeier I think we would need to use the new Api https://developer.paddle.com/api-reference/checkout-api/prices/getprices with authentication to get the list price vs. current price, identifying a sale

**Comment by lukasbestle** [comment]
I just tried it out, it doesn't need authentication, so it can be called from the frontend with a simple `GET` request to https://checkout.paddle.com/api/2.0/prices?product_ids=499826.

**Comment by lukasbestle** [comment]
But since we already include the Paddle library in the frontend, isn't it possible to somehow tell Paddle to use the v2.0 API for the call?

**Comment by distantnative** [comment]
Oh nice, somehow I tried it but kept failing, thought it'd be due to auth.

I haven't figured out if/how. As is, the library returns less data (only current, not list price).

**Comment by lukasbestle** [comment]
It looks like the Paddle API doesn't implement CORS, so we need JSONP:

```html
<script type="text/javascript">
function paddle_update_price(data) {
    let product      = data.response.products[0];
    let currency     = product.currency;
    let currentPrice = product.price.net;
    let listPrice    = product["list_price"].net;

    // ...
}
</script>
<script src="https://checkout.paddle.com/api/2.0/prices?product_ids=499826&callback=paddle_update_price"></script>
```

**Comment by lukasbestle** [comment]
I think we should include this in the HTML before the other Paddle JS stuff so it's loaded as soon as possible.

**Comment by distantnative** [comment]
That works well.

What do you think?
<img width="1430" alt="Screen Shot 2021-04-17 at 14 56 38" src="https://user-images.githubusercontent.com/3788865/115113954-21ba6180-9f8d-11eb-9ca9-f17a931e5ac7.png">

**Comment by lukasbestle** [comment]
I think the text in the line with the price shouldn't go beyond the first column of the box on larger screens, it looks a bit unbalanced. Maybe we can put the list price into the line above ("On Sale") somehow?

Also IMO the yellow strikethrough isn't very visible.

**Comment by distantnative** [comment]
Fighting the currency first. The new API returns three-letter codes, no symbols. So for most currencies it would extend the column anyways. Also we won't avoid the flow into the second columns anyways if we don't remove `per site` as well - which we shouldn't, I think.

**Comment by lukasbestle** [comment]
I don't think we need to prevent the text from being longer than one column, but I think we shouldn't make it any longer. I'm not a huge fan of the two prices with one crossed out in the same line.

Regarding the currencies: We can use this to make the browser format the currency automatically:

```js
let formatted = new Intl.NumberFormat('en', { style: 'currency', currency: currency, minimumFractionDigits: 0 }).format(price)
```

**Comment by distantnative** [comment]
<img width="1368" alt="Screen Shot 2021-04-17 at 15 26 33" src="https://user-images.githubusercontent.com/3788865/115114779-54feef80-9f91-11eb-89df-78e7413044dc.png">

**Comment by distantnative** [comment]
@lukasbestle `Intl.NumberFormat` is great!

**Comment by lukasbestle** [comment]
I think that's quite good already. Now that I look at it again: I'm not 100 % sure about the contrast of the yellow text.
@bastianallgeier What do you think about the styling?

**Comment by distantnative** [comment]
Let's say it works for some countries better than others 🤣🇦🇷

<img width="1318" alt="Screen Shot 2021-04-17 at 15 33 40" src="https://user-images.githubusercontent.com/3788865/115114995-5977d800-9f92-11eb-8da6-55545d8f0401.png">

Sidenote: Sad to see this currency and the country so destroyed... when I lived there it was about 10 peso per euro... now it's more than 100 😢

**Comment by lukasbestle** [comment]
OMG, that's crazy. At least not as bad as 42,926.34 ZWD (Zimbabwe dollar), but both of them are prices my brain can't even parse.

**Comment by distantnative** [comment]
Good thing Colombian peso aren't supported: 428,642.58
