### ISSUE TITLE
Sales banner missing on mobile

### ISSUE THREAD

**Issue by distantnative** [getkirby/getkirby.com#1297]

**Comment by bastianallgeier** [comment]
That's intended. I didn't find a good position for it in the menu.

**Comment by bastianallgeier** [comment]
If you have a good idea, let me know :)

**Comment by distantnative** [comment]
I thought so. But reading the tweet about a sale and not finding it anywhere on the site was confusing.

How about we just add it as little one-liner above the main headline? Sale should grab the attention during this short time 

![image](https://user-images.githubusercontent.com/3788865/115011780-535cfb00-9eaf-11eb-863d-28060f3b06f9.jpeg)
