### ISSUE TITLE
Reference: main column gets too narrow on desktop layout

### ISSUE THREAD

**Issue by hannesherold** [getkirby/getkirby.com#1306]
The main column of the three columns layout in "reference" becomes very narrow between some breakpoints. Readability and especially the “properties” table suffers from this. The table must then be scrolled horizontically.

Also, inside the table again only the right colum adapts. As this column holds text blocks, lines become very short.

It occurs between quite common screen widths of 960px and 1280px. See screenshots below.

One possible solution might be to also adjust width/layout of the middle column, not only of the main column; another, to make the table itself respond further.

![Bildschirmfoto 2021-04-17 um 11 09 05](https://user-images.githubusercontent.com/46819942/115108698-27567e00-9f72-11eb-9535-761dc484ad82.png)

![Bildschirmfoto 2021-04-17 um 11 09 25](https://user-images.githubusercontent.com/46819942/115108709-2f162280-9f72-11eb-8a20-2946266016db.png)

**Comment by bastianallgeier** [comment]
✅

**Comment by hannesherold** [comment]
NIce! Thank you.
