### ISSUE TITLE
OG image throws error

### ISSUE THREAD

**Issue by distantnative** [getkirby/getkirby.com#1322]
https://getkirby.com/features/developers/opengraph.png

**Comment by distantnative** [comment]
Works for me locally - maybe another server issue with image generation.

Does it work for any of you locally, team?

**Comment by lukasbestle** [comment]
Locally I get:

```
Class 'Imagick' not found
```

I think the missing extension is the most probable cause on the server as well.

**Comment by bastianallgeier** [comment]
It's the missing SVG module: https://staging.getkirby.com/features/developers/opengraph.png
It's weird though that my code to skip SVGs does not work.

**Comment by distantnative** [comment]
I think probably for the same reason that I went for this weird strpos if Statement and not F::extension

**Comment by distantnative** [comment]
My guess: the url helper adds the ?v= cache busting on it and F::extension fails with that?

**Comment by bastianallgeier** [comment]
Ahhh, yep. That could be an issue. I will check again.
