### ISSUE TITLE
Static methods should not display info text for `static` return

### ISSUE THREAD

**Issue by distantnative** [getkirby/getkirby.com#1331]
It doesn't make sense that a static method like https://getkirby.com/docs/reference/objects/http/remote/request displays

> This method does not modify the existing $remote object but returns a new object with the changes applied. Learn more →

Double checking with @lukasbestle - I think we could just drop this sentence for static methods.

**Comment by lukasbestle** [comment]
> I think we could just drop this sentence for static methods.

I fully agree!
