### ISSUE TITLE
Code blocks don't scroll at certain window widths in Firefox on maxOS

### ISSUE THREAD

**Issue by texnixe** [getkirby/getkirby.com#1337]
<img width="863" alt="Bildschirmfoto 2021-05-02 um 10 46 17" src="https://user-images.githubusercontent.com/5312492/116807511-d3cc5e80-ab33-11eb-96c0-00fbb7403b99.png">

Happens from a window width of  768px and above

**Comment by afbora** [comment]
Same with Windows & Firefox

**Comment by afbora** [comment]
![image (7)](https://user-images.githubusercontent.com/3393422/116808651-adfa8600-ab42-11eb-8101-f4d9542455f4.png)

By the way, I noticed that there is scroll in firefox, but it is not visible on the dark color. You can click the scroll area and scroll.

**Comment by texnixe** [comment]
I also have a scrollbar at smaller window widths in Firefox, but not above 768px and what is more is that there is no right margin anymore in those cases as you can see in the screenshot above. 

Fine here below 768;
<img width="554" alt="Bildschirmfoto 2021-05-02 um 12 46 27" src="https://user-images.githubusercontent.com/5312492/116810526-81476e00-ab44-11eb-8aad-4ad4f6b7a8de.png">

**Comment by afbora** [comment]
Yes you are right. Above 768px there is no scroll. 
Below 768px there is a scroll but it is not visible (for Windows & Firefox)

**Comment by pReya** [comment]
Not sure if this is related, but the code blocks on the style guide (https://getkirby.com/styleguide) are all running outside of my viewport on latest Firefox and latest macOS.
![Screenshot 2021-05-15 at 15-18-27 Content styleguide](https://user-images.githubusercontent.com/4677417/118362910-18271800-b592-11eb-9383-8d616bd28b74.png)

**Comment by pReya** [comment]
Again, the same thing happening in the new cookbook article (https://getkirby.com/docs/cookbook/extensions/virtual-files). Latest Firefox on latest MacOS.

<img width="1440" alt="Screenshot 2021-06-07 at 16 11 38" src="https://user-images.githubusercontent.com/4677417/121032049-322bd300-c7ab-11eb-8a4e-0b42f24d9931.png">

**Comment by texnixe** [comment]
Yes, I experienced the same in Firefox on MacOS

**Comment by VIPStephan** [comment]
I’m able to “fix” this by adding `max-width: 100%` to the article element.
![Bildschirmfoto 2021-07-29 um 21 00 32](https://user-images.githubusercontent.com/13770606/127550484-928c4539-461d-4cc3-bf3b-ef3e2365b474.png)
