### ISSUE TITLE
Required props in the references are missing

### ISSUE THREAD

**Issue by Werbschaft** [getkirby/getkirby.com#1348]
As already mentioned at Discord, some methods lack the required props. An example is available at:

https://getkirby.com/docs/reference/objects/cms/file/create#parameters

Here the `source` is missing in the documentation, without the method does not work at all. As I know `parent` is also required, but not highlighted as it. @distantnative meant that this still some other sides concerns.

**Comment by distantnative** [comment]
I've added a fix for the `source` prop. The `parent` prop is a bit tricky as the manual exception (required) in the method and the general property setter (optional) contradict each other - see https://github.com/getkirby/kirby/pull/3372

**Comment by lukasbestle** [comment]
@distantnative With the deprecation of optional `parent` props I think this is done as it will solve itself with the release of Kirby 3.7.0, right? Until then the property is actually not required, so the docs are correct.

Is there any general issue we still need to fix on getkirby.com? If not, I suggest to close this issue.

**Comment by distantnative** [comment]
It's actually not correctly documented because `File::create` will already enforce it as required. But I also don't see a good way to fix that issue in another way.

**Comment by lukasbestle** [comment]
We could temporarily update the docblock for `setParent()` to say something like "This property is required for `FiIe::create()` and will be generally required starting with Kirby 3.7.0".

**Comment by distantnative** [comment]
Agreed, sounds like a good temporary solution until 3.7
