### ISSUE TITLE
Plugin list: Display author names

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/getkirby.com#1354]
With the redesign we removed the author names from the overview and the plugin detail pages. To show that the plugins come from many different talented devs, I think we should bring the names back:

- Display author names together with the plugins in the overview
- Display author names on the detail pages
- Template for `plugin-developer` that displays all plugins of that author

**Comment by Werbschaft** [comment]
Is this something similar when you remove the plugin name in the URL? Then an empty page appears with the name. It would be better to list all plugins of the developer right?

Example: https://getkirby.com/plugins/hashandsalt/

**Comment by lukasbestle** [comment]
Yes, that's because we don't have a template for `plugin-developer` at the moment as I wrote above.
