### ISSUE TITLE
Cookbook: Cropping in 'Virtual pages from image gallery' does not work

### ISSUE THREAD

**Issue by foobartel** [getkirby/getkirby.com#1365]
Hello, It seems that image cropping in the cookbook article for "[Virtual pages from image gallery](https://getkirby.com/docs/cookbook/templating/virtual-pages-image-gallery)" does not work. 

After searching I think it might be the same underlying issue as discussed in this [conversation in the forum](https://forum.getkirby.com/t/page-model-for-virtual-children-pages-on-the-fly/21798/12). Unfortunately I could not get it to work.

**Comment by texnixe** [comment]
Hm, I cannot reproduce this issue. Although I must admit that the gallery-image.php template could be improved so that the image is cropped and not the linked image…

**Comment by foobartel** [comment]
Thanks for checking, yet it's somehow strange that it works for you. 

In my case, the crop/resize functions do not work on either page, gallery and gallery-image respectively. I get the correct URLs, e.g. `/media/pages/__xzy__/1b3d2fcfd3-1621846682/2010-10-2-1-02-26-am-500x500.jpg`, but the media folder stays empty and the original image, with its original dimensions, is loaded.

**Comment by texnixe** [comment]
Are the job files created? Do thumbs work in general?

**Comment by foobartel** [comment]
If by job files you are referring to the resized images in the media hash folder, then no, they are not created. 
The hash folders are created, but they all stay empty. Other thumbs around the site work as expected.

**Comment by texnixe** [comment]
With job files I was referring to the `.json` files inside the `.jobs` folder that is created inside every hash folder.

**Comment by foobartel** [comment]
Sorry, misunderstood. Yes, these are being created, I can see a few different formats in there.

**Comment by lukasbestle** [comment]
If you visit the URLs of the cropped images, Kirby will automatically pick up these job files and lazily create the thumb. This is the reason why the thumb files aren't physically there in the file system until they are requested.

If the thumb cannot be created, Kirby falls back to the original image. Which thumb driver are you using (GD or Imagick)?

**Comment by foobartel** [comment]
Thanks, that was a good tip, but no clue why it happened in the first place. 

I have added `im` as the driver and with that it works, but usually I never touch the thumb driver config. With `gd` as default thumbs were not created, even if requested and the original fallback was used. 

Thanks a lot for your help @texnixe and @lukasbestle! While not sure what the issue with GD is, I'm happy it works now :)
