### ISSUE TITLE
[Plugins] Composer dependency order and DevKit

### ISSUE THREAD

**Issue by bnomei** [getkirby/getkirby.com#138]
i am using the DevKit setup via composer and my plugins id look like `bnomei/something`. but when i create them as composer plugins and publish them on packagist and require them again this will cause an error.

> Kirby class not found.

why? because `bnomei/something` gets loaded before `getkirby/cms`.
i temporarly fixes this by requiring `getkirby/cms` in my plugins and ignoring vendor, folder but this way i will not be able to serve clean zips (which can be extracted in site/plugins/ folder ) once betas are over.

my composer knowledge is limited... maybe it can be done. any ideas how to solve this?

**Comment by bastianallgeier** [comment]
I moved it here. It's a docs issue.

**Comment by texnixe** [comment]
With the devkit gone and the composer guide in the pipeline, I guess we can close this issue?

**Comment by lukasbestle** [comment]
The Composer Guide will only cover installation with Composer, not plugin development. So I think we should keep this open for now.

**Comment by johannahoerrmann** [comment]
I searched the docs issues for something to reference the recent "plugin install using composter/submodules" discussion to and this looks like the right place – hope it is – so here's the reminder:

> @lukasbestle: After the launch we will add more docs on creating plugins and will probably add a note that it’s recommended to include the vendor directory. But we’ll first have to check if there is an easy way for plugin devs to do that. Remind us if we forget about this issue.

https://getkirby.slack.com/archives/CBY2BA82E/p1547231287219400?thread_ts=1547132605.102400&cid=CBY2BA82E

**Comment by lukasbestle** [comment]
Closing this in favor of #8. I will take a look at it soon.
