### ISSUE TITLE
Titles and images of Cookbook Recipes are getting cut off in Firefox 

### ISSUE THREAD

**Issue by trych** [getkirby/getkirby.com#1394]
Hi there,

I am getting weird layout issues in the most recent Firefox (v 89.0) on macOS.
The titles and images are getting cut off, see screenshots:

![20210611-114018_Screenshot_Finder](https://user-images.githubusercontent.com/9803905/121666809-f2feca00-caa9-11eb-8ba8-4fb6ab6e7eec.png)

![20210611-114034_Screenshot_Firefox](https://user-images.githubusercontent.com/9803905/121666823-f6925100-caa9-11eb-8990-8f3a08f5443c.png)

The same thing looks fine on Chrome (exact same window size):

<img width="740" alt="20210611-114104_Screenshot_GoogleChrome" src="https://user-images.githubusercontent.com/9803905/121666855-001bb900-caaa-11eb-849e-5c82bf889e02.png">

**Comment by lukasbestle** [comment]
This could be related to #1337.
