### ISSUE TITLE
Some methods in the reference display wrong type hint

### ISSUE THREAD

**Issue by fabianmichael** [getkirby/getkirby.com#1400]
I found this issue on the `$file->blur()` page (https://getkirby.com/docs/reference/objects/cms/file/blur), but it probably affects other pages as well. In the source code, the method does not use a type hint, but the docs interpret this as `bool`, whereas the same page mentions, that the method also accepts an integer as parameter.

See https://github.com/getkirby/kirby/blob/3.5.6/src/Cms/FileModifications.php#L24

**Comment by distantnative** [comment]
The reference is using the doc block there... which seems to be the error then

**Comment by distantnative** [comment]
@fabianmichael looks solved to me. Please reopen if you disagree
