### ISSUE TITLE
Lightbox opens smaller image

### ISSUE THREAD

**Issue by medienbaecker** [getkirby/getkirby.com#1403]
Clicking on lightbox images you receive a smaller version of the images.
Looking at the source code I see the img tag in the lightbox has a srcset with `2x` while the images in the articles don't.

![getkirby com_docs_reference_panel_fields_blocks](https://user-images.githubusercontent.com/7975568/123103759-9d75d600-d436-11eb-9904-55c779577aa8.png)

**Comment by afbora** [comment]
I can confirm the issue when i click second time.

**Comment by medienbaecker** [comment]
[You hardcoded `2x` in the lightbox srcset](https://github.com/getkirby/getkirby.com/blob/main/assets/js/components/lightbox.js#L105). I guess because some screenshots are retina screenshots? The perfect solution would be to differentiate those by adding a `@2x` to their filename. Then the script can add the `2x` appendix conditionally .
