### ISSUE TITLE
Undocumented auth challenge config options

### ISSUE THREAD

**Issue by sebastiangreger** [getkirby/getkirby.com#1413]
Hi, I scratched my head over how to change the from address of the emails sent by the login auth flow.

Found `auth.challenge.email.from` etc. in `/Cms/Auth/EmailChallenge.php`, so this is to suggest whether these could be added to the documentation for convenience - at least the site search did not return any hits for that key.

Not quite sure what would be a good place ...could it be mentioned on https://getkirby.com/docs/reference/system/options/auth for example?

**Comment by afbora** [comment]
Do you mean following section? `Email options`

https://getkirby.com/docs/reference/system/options/auth#authentication-challenges__email-options

**Comment by sebastiangreger** [comment]
OMG, it's right there at plain sight! :open_mouth: Yes, @afbora, that is exactly what I was looking for :see_no_evil:

Sorry for this pointless issue ...I com-plete-ly overlooked that despite scrolling over that page twice!
