### ISSUE TITLE
Broken Github link in Database docs

### ISSUE THREAD

**Issue by tmslnz** [getkirby/getkirby.com#1425]
404 on the Github link a the bottom of this page:  
https://getkirby.com/docs/reference/objects/database/query/__construct

Discovered because I wanted to submit an edit, whereby the second param of the `new Query()` constructor is not optional as the docs state (`Optional name of the table, which should be queried`)

**Comment by afbora** [comment]
Same for all `__construct` methods.

**Comment by lukasbestle** [comment]
I don't think it's `__construct()` specifically. We don't have actual reference pages for all methods, most of them are virtual pages that are auto-generated from our code. So every link that points to such a virtual page is broken.

@distantnative I see two options: Either we only display the GitHub link if the content file already exists. Or we create an issue template for "reference improvements" specifically for such cases where a page doesn't already exist (in which case it's simpler if we create the page ourselves). The GitHub link could then point to https://github.com/getkirby/getkirby.com/issues/new?template=reference.md or something.

**Comment by distantnative** [comment]
I like the second suggestion!

On the concrete problem, this seems indeed wrong inline docs
