### ISSUE TITLE
Reference: File Blueprints reference shows search and pagination of page blueprints?

### ISSUE THREAD

**Issue by renestalder** [getkirby/getkirby.com#1467]
I'm really not that certain about what's going here.

https://getkirby.com/docs/reference/panel/fields/files#pagination

Pagination and search sections here show examples with `type: pages` and I can't figure out what that is about other than It must be a mistake. They are probably valid options, but the examples should show up with `type: files`.

I wanted to send a pull request, yet the [documentation source includes `(docs: panel-picker-pagination field: pages)`](https://github.com/getkirby/getkirby.com/blob/main/content/docs/3_reference/3_panel/3_fields/0_files/reference-article.txt) so I'd assume that's not a mistake at all. Not sure what this short snippet is and if it can be addapted to show the example with a files field. I though I might leave that one up to someone else.

**Comment by texnixe** [comment]
Thanks for pointing this out, I fixed it.
