### ISSUE TITLE
Docs: Have a list of reserved words in blueprint docs

### ISSUE THREAD

**Issue by PaulMorel** [getkirby/getkirby.com#147]
I just updated to Kirby 2.2.2 and one of my blueprints got this error.

`The field name: image must not be used for pages.`

It's a simple fix on my part, however I think it would be wise to have a list of reserved words we shouldn't use for panel fields.

**Comment by lukasbestle** [comment]
Also see [this discussion in the forum](https://forum.getkirby.com/t/kirby-2-2-x-incompatible-with-legacy-field-names/2616?u=lukasbestle) about the new feature.

**Comment by texnixe** [comment]
The feature was finally removed again and a notice regarding naming of fields added to docs. I don't think a list of words makes sense as these are the same as methods in the cheatsheet.
