### ISSUE TITLE
Add final config in sitemap recipe

### ISSUE THREAD

**Issue by oldinosor** [getkirby/getkirby.com#1473]
01 - Create the snippet with your XML
Line 4 of the code block
```php 
<?php if (in_array($p->uri(), $ignore)) continue ? 
```
uses the undefined variable $ignore
And could be replaced by something like:
```php 
<?php if (in_array($p->uri(), ['error', 'sitemap'])) continue ?>
```

02 - Create new routes
If a folder sitemap and a file sitemap.txt are created in /content
http://yourdomain.com/sitemap gives a result
But http://yourdomain.com/sitemap.xml redirects to the error page and not to the first above.
In any case, without creating this folder and this file, both http://yourdomain.com/sitemap and http://yourdomain.com/sitemap.xml redirect to the error page.

03 - Another way was used to create the getkirby.com sitemap, would it be possible to know which one?

**Comment by texnixe** [comment]
`$ignore` is defined in the route and passed to the snippet.

**Comment by oldinosor** [comment]
With
```php
return [
	'debug' => true,
];
```
in config.php

The error message is:
Whoops \ Exception \ ErrorException (E_WARNING)
Undefined variable $ignore

Please, try to use the recipe and the issue will be there! :-)

**Comment by texnixe** [comment]
Works for me, your config should include `sitemap.ignore` and the route.

**Comment by oldinosor** [comment]
I added the '2 - Create new routes' whole code in config.php
```php
return [
  'routes' => [
    [
      'pattern' => 'sitemap.xml',
      'action'  => function() {
          $pages = site()->pages()->index();

          // fetch the pages to ignore from the config settings,
          // if nothing is set, we ignore the error page
          $ignore = kirby()->option('sitemap.ignore', ['error']);

          $content = snippet('sitemap', compact('pages', 'ignore'), true);

          // return response with correct header type
          return new Kirby\Cms\Response($content, 'application/xml');
      }
    ],
    [
      'pattern' => 'sitemap',
      'action'  => function() {
        return go('sitemap.xml', 301);
      }
    ]
  ]
];
```
Is it enough or should I add something else?

**Comment by texnixe** [comment]
The `sitemap.ignore` option is still missing, unless you only want to exclude the error page (which is set as fallback. And make sure that your config only has one return statement and all options are included inside that return array.

**Comment by oldinosor** [comment]
OK, Thanks! :-)
Everything is all right now.

To help people (like me...) who don't read the comment at the top of the config.php file, 

perhaps could you change in this comment

"The config file is optional. It accepts a return array with config options."
by
"The config file is optional. It accepts only one return array with config options."

and add in the recipe

after 3 - Excluding pages from your sitemap
4 - Example of resulting config.php

```php
<?php

/**
 * The config file is optional. It accepts only one return array with config options
 * Note: Never include more than one return statement, all options go within this single return array
 * In this example, we set debugging to true, so that errors are displayed onscreen. 
 * This setting must be set to false in production.
 * All config options: https://getkirby.com/docs/reference/system/options
 */
return [
  
	'debug' => false,

  /* Cache */

  'cache' => [
	  'pages' => [
		  'active' => true,
		  'ignore' => function ($page) {
			return $page->title()->value() === 'Do not cache me';
		  }
	  ]
  ],

  /* SiteMap */

  'routes' => [
    [
      'pattern' => 'sitemap.xml',
      'action'  => function() {
          $pages = site()->pages()->index();

          // fetch the pages to ignore from the config settings,
          // if nothing is set, we ignore the error page
          $ignore = kirby()->option('sitemap.ignore', ['error']);

          $content = snippet('sitemap', compact('pages', 'ignore'), true);

          // return response with correct header type
          return new Kirby\Cms\Response($content, 'application/xml');
      }
    ],
    [
      'pattern' => 'sitemap',
      'action'  => function() {
        return go('sitemap.xml', 301);
      }
    ]
  ],
  
  'sitemap.ignore' => ['error'],
  
];
```
