### ISSUE TITLE
Reference: Splat syntax is converted to a single argument

### ISSUE THREAD

**Issue by sebastiangreger** [getkirby/getkirby.com#1484]
https://getkirby.com/docs/reference/objects/cms/site/find states that `->find()` expects a string, but this also works with an array of page IDs (e.g. the `pages()` helper does that).

As an additional note: the reference does not indicate that `->find()` only finds published pages (listed/unlisted) but not drafts.

**Comment by lukasbestle** [comment]
[In the code](https://github.com/getkirby/kirby/blob/3.5.7.1/src/Cms/HasChildren.php#L128) we have hinted this argument as `string ...$arguments`, which is correct. @distantnative I think the reference converts this syntax to `string $arguments = null`, which seems like a bug to me.

Regarding the note about drafts: You are right, I have fixed it in the code: https://github.com/getkirby/kirby/pull/3791
