### ISSUE TITLE
Docs: How to set up cache for multilingual site with different URLs

### ISSUE THREAD

**Issue by zanstro** [getkirby/getkirby.com#1489]
**Describe the bug**  
I have a Kirby multilingual site and I use different URLs for each language. When I update a page in English the cache is cleared but this doesn’t happen when I update a page in a different language. Actually, when I update a page in a different language the system clears the cache of the English cache pages directory. I currently use two languages EN as default and IT.

The structure of the cache folders in my case is as follows:

site/cache/www.example.co.uk/pages/ url-key.en.html.cache

and

site/cache/www.example.it/pages/ url-key.it.html.cache

The language setup for en is this:
```php
return [
    'code' => 'en',
    'default' => true,
    'direction' => 'ltr',
    'locale' => [
        'LC_ALL' => 'en_GB'
    ],
    'name' => 'English',
    'translations' => Yaml::decode(F::read(kirby()->root('languages').'/vars/en.yml')),
    'url' => 'https://www.example.co.uk',
];
```

Accordingly for it lang the setup is this:
```php
return [
    'code' => 'it',
    'default' => false,
    'direction' => 'ltr',
    'locale' => [
        'LC_ALL' => 'it_IT'
    ],
    'name' => 'Italian',
    'translations' => Yaml::decode(F::read(kirby()->root('languages').'/vars/it.yml')),
    'url' => 'https://www.example.it'
];
```

The cache setup config is as follows:
```php
return [
    'cache' => [
    'pages' => [
        'active' => true,
        'ignore' => function ($page) {
            return in_array($page->slug(), ['contact', 'blog']);
        }
    ]
]
];
```

**Kirby Version**  
3.4.3

**Comment by mrflix** [comment]
I just ran into this issues again ☹️

I looked for a fix here: https://getkirby.com/docs/guide/languages/introduction#language-specific-urls
Before I googled it and found [my own issue](https://github.com/getkirby/kirby/issues/4259) from April 🙈

**Comment by lukasbestle** [comment]
Sorry for the huge delay. I've finally resolved this and used the opportunity to improve other parts of the caching docs as well.
