### ISSUE TITLE
Search: `referer` yields countless results

### ISSUE THREAD

**Issue by distantnative** [getkirby/getkirby.com#1516]
<img width="1291" alt="Screen Shot 2021-10-23 at 18 11 54" src="https://user-images.githubusercontent.com/3788865/138563732-2620d0c0-75e5-4866-8c4e-0e85499b4e57.png">

**Comment by lukasbestle** [comment]
I've added it to the issue in #1285. Because of 3.6 I didn't find the time for it yet.
