### ISSUE TITLE
Add `aspect-ratio` to image kirbytag

### ISSUE THREAD

**Issue by medienbaecker** [getkirby/getkirby.com#1519]
The lazy loaded images you insert via the `(image: )` kirbytag do not receive `width`/`height` attributes or an `aspect-ratio`. 

When the images load there's significant content reflow. You can reproduce this by opening this page and scrolling up: https://getkirby.com/docs/reference/panel/fields/blocks#custom-block-types__tabs

**Comment by distantnative** [comment]
I tried: https://github.com/getkirby/getkirby.com/commit/294d34be4e74df66166aec38b31caebfcddb8633
However, I still get the content reflow. Any ideas?

**Comment by bastianallgeier** [comment]
✅
