### ISSUE TITLE
Not all components documented on the UI Kit reference

### ISSUE THREAD

**Issue by renestalder** [getkirby/getkirby.com#1520]
Is it me or are there certain UI components missing on the reference page for the UI Kit? A couple of cookbook articles show the usage of `<k-writer>` and I build custom block components with it, but I can't find it anywhere in the documentation.

https://getkirby.com/docs/reference/plugins/ui

So, I wonder if that is the wanted behaviour and if not, if other components are missing from that page.

**Comment by distantnative** [comment]
There are indeed a number of components missing currently. We are trying to automate part of the docs for the UI components which will hopefully at least offer some basic docs for all components: https://github.com/getkirby/getkirby.com/pull/1335

**Comment by distantnative** [comment]
Will be available with release of Kirby 3.6.0
