### ISSUE TITLE
Plugin downloads aren't working

### ISSUE THREAD

**Issue by gearsdigital** [getkirby/getkirby.com#1526]
It seems that all the download links are broken because of double slash `//` in the Downlaod URL

**Reference page:**
https://getkirby.com/plugins/gearsdigital/reporter

**Not working:**
https://api.github.com/repos/gearsdigital/kirby-reporter//zipball

**Working:**
https://api.github.com/repos/gearsdigital/kirby-reporter/zipball

**Comment by bastianallgeier** [comment]
✅
