### ISSUE TITLE
Finish 3.6 docs

### ISSUE THREAD

**Issue by distantnative** [getkirby/getkirby.com#1562]
- [x] Custom iframe attributes allowed in video helper
- [x] toggle field now supports the query syntax in the text property
- [x] Now default block previews are overwritable
- [x] Breaking: Multi-language setup: slugs in content files of the default language will be ignored
- [x] Html::encode(): Single quotes now are also converted

**Comment by youngcut** [comment]
- [ ] Dynamic Blueprints
