### ISSUE TITLE
Add information about overriding Sane class defaults

### ISSUE THREAD

**Issue by sebastiangreger** [getkirby/getkirby.com#1573]
This is totally niche, and probably very low priority – just opening this issue for future consideration, as I've run into this twice now.

The `Sane` class comes with a preset of permitted SVG/XML attributes etc., which can be overridden. These allowlist overrides are not currently documented (and, frankly, I'm not quite sure where that info would be best placed in the reference).

Related:
- https://forum.getkirby.com/t/how-to-define-my-allowlist-for-svg-attributes-k3-6-sane-class/23999/6
- https://github.com/getkirby/kirby/issues/3433#issuecomment-864851723

**Comment by distantnative** [comment]
@lukasbestle What do you think about if we add a note on the `Sane` class reference docs but also link to that from here: https://getkirby.com/docs/guide/files#supported-file-types ?

**Comment by lukasbestle** [comment]
@distantnative That sounds great! 👍
