### ISSUE TITLE
Depreciate cookbook article on selective page cache

### ISSUE THREAD

**Issue by sebastiangreger** [getkirby/getkirby.com#1584]
A [discord discussion](https://discord.com/channels/525634039965679616/525641819854471168/914572838143393792) this morning made me aware that the solution outlined in the cookbook article at https://github.com/getkirby/getkirby.com/tree/main/content/docs/2_cookbook/9_setup/0_selective-page-cache has no longer been working since 3.5.5 and actually harms performance of any website using it – as far as I understand, calling `kirby()->user()` makes use of the `session()` method and thereby disables both the server-side page cache as well as triggers sending a `Cache-control: no-cache` header with every page request (introduced by https://github.com/getkirby/kirby/pull/3292).

This should probably be taken down or marked with a highly visible warning?

**Comment by sebastiangreger** [comment]
Related issue in core: https://github.com/getkirby/kirby/issues/3976

So for versions 3.5.5–3.6.1 (as planned today), the solution from the cookbook essentially triggers Kirby to disable the page cache and send out "no cache" headers globally for the entire website. I.e. it is no different from turning off page cache entirely (as a matter of fact, just turning of the cache entirely does not come with the added effect of the "no-cache" header).

Once the changes outlined in that core ticket are implemented (potentially 3.6.2), the recipe's solution would be obsolete as the suggested logic is actually much smarter than this (only disables page cache for logged in users if there's anything in the code accessing a session). I can't quite see a use case for this recipe's solution beyond that.

**Comment by lukasbestle** [comment]
@sebastiangreger I think the best way forward is to delete the recipe entirely. What do you think?

**Comment by sebastiangreger** [comment]
I don't see any value in this cookbook's solution in present (due to the potentially unwanted consequences, even though the technique still works) or for the future (as the outcome of this tweak pretty much is what you outlined for the future default behaviour).

So yes, deletion makes sense. I was contemplating whether it would be good to retire it gracefully (e.g. setting it to unlisted and add a warning text for anybody who still ends up there, e.g. from their bookmarks or incoming links), but that might be overkill for such a small hack? No need to make a mountain out of a mole hill (aka. :mosquito: != :elephant:), I'd say…
