### ISSUE TITLE
Code examples cut-off at certain resolutions in Firefox

### ISSUE THREAD

**Issue by fabianmichael** [getkirby/getkirby.com#1593]
As the screenshot shots, the code examples are rendered too long. It’s great, that they are wider than regular paragraphs, but in Firefox, the text does not wrap, making the last characters of long lines invisible. See screenshots below:

![Bildschirmfoto 2021-12-01 um 17 02 28](https://user-images.githubusercontent.com/395617/144269061-bcf484cf-9bd5-4ace-8486-20e846a6f427.png)
Firefox 94.0.2 on macOS 11.6.1

![Bildschirmfoto 2021-12-01 um 17 04 34](https://user-images.githubusercontent.com/395617/144269378-ca3a8b6e-80b0-4897-8eff-a3e86edabf2d.png)
Chromium 98.0.4694.0 on macOS 11.6.1

**Comment by pReya** [comment]
Duplicate of #1337

**Comment by fabianmichael** [comment]
@pReya You’re right.
