### ISSUE TITLE
Plugin directory still lists "Twit" plugin, now superseded by "kirby3-twitter"

### ISSUE THREAD

**Issue by sebastiangreger** [getkirby/getkirby.com#1601]
via https://forum.getkirby.com/t/twit-plugin-twitter-feed-help/24183 :

Plugin page https://getkirby.com/plugins/hashandsalt/twit should probably be removed and https://github.com/HashandSalt/kirby3-twitter added to directory instead?

**Comment by texnixe** [comment]
Fixed with e737f0266864741bdbc0951475c80223ea45823c
