### ISSUE TITLE
Misspelling on Aspect Ratio UI Kit Page

### ISSUE THREAD

**Issue by bryantwells** [getkirby/getkirby.com#1626]
**Issue with Reference**  

closing tag is misspelled @ https://getkirby.com/docs/reference/plugins/ui/aspect-ratio
```
<k-ratio ratio="3/2">
  <div>Ratio!</div>
</k-reatio>
```

**Expected**  

```
<k-aspect-ratio ratio="3/2">
  <div>Ratio!</div>
</k-aspect-ratio>
```

**Screenshots**

**Comment by lukasbestle** [comment]
Thanks for letting us know. I've opened a PR in the Kirby repo to fix this typo directly in the code: https://github.com/getkirby/kirby/pull/4080
