### ISSUE TITLE
Find another name for default controller (site.php) to avoid confusion with default.php controller

### ISSUE THREAD

**Issue by texnixe** [getkirby/getkirby.com#1631]
In the guide (https://getkirby.com/docs/guide/templates/controllers#default-controller) we call the general purpose `site.php` controller "default controller". What would be a better name for this controller to avoid confusion with the actual `default.php` controller.

- General controller
- Base controller
- ...

**Comment by distantnative** [comment]
> Be aware that the default controller only works as a fallback if no specific page controller for the template exists.

To me it sounds as if the `site.php` controller actually should be `default.php` controller? or was our idea that one could have a `default.php` controller for `default.php` templates but even another one that pages use that have a specific template but no own controller?

**Comment by texnixe** [comment]
> To me it sounds as if the site.php controller actually should be default.php controller? 

I don't think so. Because the `default.php` controller only works with the `default.php` template, while the `site.php` controller works for all templates unless there is a template specific controller.

**Comment by distantnative** [comment]
Then I would go for something as `General site controller`
