### ISSUE TITLE
Markdown rendering issue?

### ISSUE THREAD

**Issue by yurivish** [getkirby/getkirby.com#1645]
**Issue with Reference**  

URL: https://getkirby.com/docs/cookbook/extensions/ab-testing

**Expected**  
The sentence should say "either return `0` or `1`“.

**Screenshots**  

![image](https://user-images.githubusercontent.com/114388/149069296-c2c60c11-702e-4080-962b-fde7fba1b2d7.png)

The issue is interesting because the [source](https://github.com/getkirby/getkirby.com/blob/68b62a6cde3c01949d8e94b0042b2d2d1a04ce9e/content/docs/2_cookbook/7_extensions/0_ab-testing/cookbook-recipe.txt#L86) has a `0`, which fails to get rendered. Is the Markdown parser perhaps treating the `0` as a falsy value, and skipping over it?

**Comment by distantnative** [comment]
Thanks! for spotting!

**Comment by yurivish** [comment]
Thanks for fixing!
