### ISSUE TITLE
Fiber: Document objects/keys under window.panel

### ISSUE THREAD

**Issue by sebastiangreger** [getkirby/getkirby.com#1646]
Just preserving these here as @bastianallgeier shared [in Discord](https://discord.com/channels/525634039965679616/525638772591951882/930831469734166580) :pray: – this would be a valuable addition to the docs (though I am currently having a hard time coming up with a good suggestion where/how):

> With Fiber, the entire state is sent from the backend to the frontend in every request. This means that you can easily inspect it via the browser console. 
> 
> The following objects/keys are all available under window.panel: 
```js
// i.e. $config.debug
window.panel.$config 
// ltr, rtl
window.panel.$direction 
// current language in a multi-language env
window.panel.$language 
// array with all installed languages 
window.panel.$languages
// registered: true/false
window.panel.$license
// true/false
window.panel.$multilang
// object with permissions for the current user
// useful to enable/disable UI elements
window.panel.$permissions
// object with various system variables 
window.panel.$system
// the current UI translation object with all translated strings
window.panel.$translation
// the view settings with all props from the backend
window.panel.$view
```
> We expose them in window.panel but they are also available in your Vue components. 
```vue
<template>
  <p v-if="$license">This thing is registered</p>
</template>
<script>
export default {
  computed: {
    somethingFromTheCurrentView() {
      return this.$view.props.myProp;
    }
  }
}
</script>
```

**Comment by distantnative** [comment]
Maybe a bit embarrassing that I only realise this now, but: https://getkirby.com/docs/reference/plugins/internals/data

I'll add your example though.
