### ISSUE TITLE
Titles with long words overflowing on mobile due to `widont()` method

### ISSUE THREAD

**Issue by texnixe** [getkirby/getkirby.com#1697]
Example result:

![IMG_3217](https://user-images.githubusercontent.com/5312492/160704420-61a1a88e-0255-4abe-86e6-10b8e25352f0.png)

**Comment by distantnative** [comment]
@bastianallgeier I would say headlines shouldn't use the widont helper. Or we need to add &shy

**Comment by bastianallgeier** [comment]
I think we could probably remove the widont method and see how bad the results are afterwards. But they are probably never as bad as that mobile issue above.
