### ISSUE TITLE
`$block` object missing from reference

### ISSUE THREAD

**Issue by S1SYPHOS** [getkirby/getkirby.com#1705]
.. under headline `Objects` there's `$blocks`, but no `$block` in the sidebar (it exists, but isn't displayed) - [here](https://getkirby.com/docs/reference/objects) it does, though

.. looking at the files, there's no quick way for me to figure out a PR - sorry!

**Comment by afbora** [comment]
Here all objects: https://getkirby.com/docs/reference/objects

**Comment by afbora** [comment]
It would be difficult to list them all on the sidebar. I think that's why only frequently used are listed in the sidebar. `$block` object is https://getkirby.com/docs/reference/objects/cms/block

**Comment by S1SYPHOS** [comment]
In this case, it would be mirror-imaged to the plural `$blocks`, but if that doesn't convince you, then closing this is alright :+1: 

Thanks @afbora for the clarification, really appreciated

**Comment by texnixe** [comment]
I'm also missing  $block and $layout in the sidebar, though. I think they are needed rather often.

**Comment by distantnative** [comment]
✅ Added them (left them out when we launched cause I never found the actual methods that insightful)
