### ISSUE TITLE
readme: tip to exclude pages via model

### ISSUE THREAD

**Issue by bnomei** [getkirby/getkirby.com#1721]
maybe add to the readme that its also possible to overwrite `$page->isCacheable()` in a model to control the behaviour dynamically instead of adding to many `if` clauses to the config.
https://getkirby.com/docs/reference/objects/cms/page/is-cacheable
https://getkirby.com/docs/guide/cache#caching-pages

**Comment by iskrisis** [comment]
This is super neat trick! I had no idea about this. This should be surely in the guide. But it's not really about this driver but all cache drivers? Maybe this issue should be ticket getkirby.com repo.
