### ISSUE TITLE
"Search By" text wraps on Safari

### ISSUE THREAD

**Issue by manuelmoreale** [getkirby/getkirby.com#1724]
Very minor issue but on Safari Mac (I'm using 15.4) the "Search by" next to the Algolia logo spans over two lines instead of one
The screenshot should be quite clear

**Screenshots**  
![Screenshot 2022-04-14 at 10 00 23 AM](https://user-images.githubusercontent.com/1738077/163341427-59ce0aa3-dbb7-4ae0-b7de-27f45a1deda9.png)

**Comment by distantnative** [comment]
Cannot reproduce this with newer Safari versions anymore
