### ISSUE TITLE
Reference: `k-date-time-input` doesn't exist anymore (in 3.6.4+ at least)

### ISSUE THREAD

**Issue by adamkiss** [getkirby/getkirby.com#1729]
**Issue with Reference**  
[date time input](https://getkirby.com/docs/reference/plugins/ui/date-time-input) component referenced in the documentation doesn't seem to exist anymore, at least the getkirby/kirby repository link goes to 404

**Expected**  
I'd expect the reference to be removed

**Comment by distantnative** [comment]
UI docs will be solved differently with v4 going forward
