### ISSUE TITLE
Docs: label/badge for "since version X"

### ISSUE THREAD

**Issue by distantnative** [getkirby/getkirby.com#173]
I'd love to have a better markup to make clear since when a feature exists. A little badge or so. Putting it in parentheses in a heading doesn't look pretty and isn't really practical either. A visual representation somehow.

Also maybe for different code examples when we need to keep a legacy example (e.g. < 2.2) and the new one.

**Comment by texnixe** [comment]
Yes, I agree absolutely. I think we had already agreed on some sort of marker in a discussion between Bastian, Lukas and me, but somehow that got lost on the way. I'll add it to the task list.

**Comment by distantnative** [comment]
Are you already actively working on it? Would be great to already use it when adding docs for the upcoming release, so we don't have to go through all of it again afterwards. /cc @lukasbestle @bastianallgeier

**Comment by lukasbestle** [comment]
I agree. I can implement something early next week.

**Comment by lukasbestle** [comment]
Hm, but what about the "main" docs? Cheat sheet is rather easy but how could we mark up the new section on the controllers page for example?

**Comment by distantnative** [comment]
How about a tag like `(since: 2.3)` that gets replaced with e.g. 
```
<span class="version"><span>since </span>2.3</span>
```

And then different CSS styles could be used for different contexts:
- in a headline on a cheatsheet page
- on the cheatsheet overview next to the item headline
- in/at the beginning of a text paragraph
- etc.
