### ISSUE TITLE
UI Kit: list possible values for enum-type props

### ISSUE THREAD

**Issue by LeBenLeBen** [getkirby/getkirby.com#1739]
**Issue with Reference**  
In general, in the [UI Kit](https://getkirby.com/docs/reference/plugins/ui) documenting Vue components, props that accept only specific values don’t have the actual values documented.

For example, the [item](https://getkirby.com/docs/reference/plugins/ui/item) has a prop `layout` with the default `list` value specified, but it doesn’t tell us that it accepts `cards` and `cardlets`.

**Expected**  
All possible values for a prop should be listed.

**Comment by lukasbestle** [comment]
For those props that take a fixed set of string values, we could change the type from `string` to `'list'|'cards'|'cardlets'`. This would be more specific and also more correct (the prop cannot take any ordinary string).

@distantnative Would that work from the technical perspective? Maybe we need to add support for this to the color highlighter, but I wonder whether this would break other tooling we use that maybe does not support this syntax.

**Comment by distantnative** [comment]
@lukasbestle I don't think we can but need to check. I think this is taken directly from the Vue props definition. However by adding `@values `list`|...` we can annotate this and our website will already pick it up as `Examples: ...`. So I think that's the best way for now and just missing here (we already use this in some places).

**Comment by lukasbestle** [comment]
Fixed by https://github.com/getkirby/kirby/pull/4302.
