### ISSUE TITLE
k-ratio tag name is misspelled

### ISSUE THREAD

**Issue by bryantwells** [getkirby/getkirby.com#1760]
Spelling error on UI Kit documentation. 
```
<k-ratio ratio="3/2">
  <div>Ratio!</div>
</k-reatio>
```
Should read...
```
<k-ratio ratio="3/2">
  <div>Ratio!</div>
</k-ratio>
```
[Link](https://getkirby.com/docs/reference/plugins/ui/aspect-ratio)

**Comment by texnixe** [comment]
Should actually be `<k-aspect-ratio>` and the example is already fixed in the source code, but still wrong in the index.json.

@lukasbestle Looks like this file is not updated automatically?

**Comment by distantnative** [comment]
Pinging @bastianallgeier here - I was under the impression each release would trigger the json file to be created newly and uploaded to our server. Probably not yet functioning?

**Comment by distantnative** [comment]
Solved differently in v4 going forward
