### ISSUE TITLE
add alt to (image: ...) attribute

### ISSUE THREAD

**Issue by jklue** [getkirby/getkirby.com#1761]
**Issue with Reference**  
On the kirbytext image page (https://getkirby.com/docs/reference/text/kirbytags/image), alt is not listed as an image attribute, although it is referenced later in the documentation

**Expected**  
Where the image attributes are listed, include "alt." So the full list would be "alt, caption, class, link, title."

**Screenshots**  
![image](https://user-images.githubusercontent.com/5399943/174285273-98111797-1214-4046-be81-9062e5cf27c5.png)

**Comment by texnixe** [comment]
There are in fact actually even more attributes missing, this is the full list:

```
            'alt',
            'caption',
            'class',
            'height',
            'imgclass',
            'link',
            'linkclass',
            'rel',
            'target',
            'title',
            'width'
```
The reason they are missing is that the getkirby.com code overwrites the default `image` tag 🙈 , thus messing up with the automatic attribute generation.

@bastianallgeier, @distantnative What would be the best way to fix this? Remove attributes from custom tag? Make sure the methods use the original tag?

**Comment by distantnative** [comment]
This is a bug. The reference should actually always load the original methods etc - no matter whether the getkirby.vom Site overwrites anything or not

**Comment by texnixe** [comment]
In this particular case ifthappens because the code calls `KirbyTag::$types[$this->name()]['attr']` and since types contains the merge type from core and plugins, it doesn't work as expected. So maybe we should use `$kirby->core()->kirbytags()` here instead.
