### ISSUE TITLE
Docs for Textarea button formats

### ISSUE THREAD

**Issue by maxackerman** [getkirby/getkirby.com#18]
Show how to add/remove buttons from the textarea field

**Comment by jaydenseric** [comment]
+1

The docs page is really bare: http://getkirby.com/docs/cheatsheet/panel-fields/textarea.

Need to also document the textarea `size` option.

**Comment by maxackerman** [comment]
Im not sure what the size option does, but I realized you can turn off the buttons with "buttons: false"

```
text:
  label: Text
  type:  textarea
  buttons: false
```

Im still not sure how to turn on/off a single button. The method from Kirby 1 doesn't work here

**Comment by bastianallgeier** [comment]
The size option does no longer exist since the textareas in Kirby 2 automatically adapt to the text length. The buttons have not been switchable individually either, but this will be back in the next release. I will add it to the docs then.

**Comment by jaydenseric** [comment]
@bastianallgeier Perhaps we should add a section to the [upgrade guide](http://getkirby.com/docs/installation/upgrade) documenting redundant stuff that is safe to remove, even if you don't have to, following an upgrade?
