### ISSUE TITLE
TXT should not be shown as a supported file type

### ISSUE THREAD

**Issue by miragecraft** [getkirby/getkirby.com#1816]
On the page: https://getkirby.com/docs/guide/content/files

Under **Supported File Types**, `txt` is listed as a supported file type under `Documents`, but it's actually NOT supported because Kirby itself uses txt files for page data.

I had to find this out here: https://forum.getkirby.com/t/unable-to-upload-txt-file-types/24381

**Comment by lukasbestle** [comment]
As far as I remember, `txt` files are allowed as long as the content extension is configured to something else (e.g. `md`). We need to verify and document this.

**Comment by distantnative** [comment]
We should also look into if we could make the error message more specific, explaining why this one isn't allowed.
