### ISSUE TITLE
Document how file upload process non-ASCII filenames

### ISSUE THREAD

**Issue by miragecraft** [getkirby/getkirby.com#1817]
Had to find this out the hard way, apparently when uploading files containing East Asian characterse Kirby will silently strip them all out.

This leads to weird error message of `You are not allowed to upload invisible files` if you upload something like `日本語.pdf`, because it becomes `.pdf` due to the character stripping (files starting with dot are invisible).

In addition, all accents/umlauts (such as French and German characters) are converted to their ascii equivalents.

This took me a while to figure out because I'm confused as to why my files are invisible when they're not.

This behavior should be properly documented.

**Comment by distantnative** [comment]
Besides documenting it, maybe we could also take the ascii converting rules of the current language into consideration. Might be a sensible assumption that uploaded filenames are in the same language and thus converting to ascii would fail in less cases.
