### ISSUE TITLE
Needed new plugin PR template

### ISSUE THREAD

**Issue by afbora** [getkirby/getkirby.com#1837]
Needed new plugin issue template to keep consistency for 3.8

https://github.com/getkirby/getkirby.com/issues/new/choose

**Comment by distantnative** [comment]
How should such an issue template look like?

**Comment by afbora** [comment]
These are the only ones I can think of for now. Maybe like that:

### I've checked followings for my plugin

- [ ] Plugin name (`Kirby::plugin('vendor/name', []);`) is same with getkirby.com (`getkirby.com/plugins/vendor/name`) is same
- [ ] composer.json version exists
- [ ] GitHub latest tag name and composer.json version is same

**Comment by lukasbestle** [comment]
@afbora This would be more for a PR template, right?

**Comment by afbora** [comment]
@lukasbestle Ah yes, for PR template.

**Comment by afbora** [comment]
This task has been shelved for now because the PR template could not be selected.
