### ISSUE TITLE
Upgrade kit to latest Kirby version in `Creating pages from frontend` cookbook

### ISSUE THREAD

**Issue by chrfickinger** [getkirby/getkirby.com#1848]
The downloadable example files from the cookbook recipe _"Creating pages from frontend"_ are no longer working with the latest kirby version. The following error message is displayed:

`Deprecated: Return type of Kirby\Toolkit\Iterator::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/kirby/src/Toolkit/Iterator.php on line 55`

and 

`Warning: Uncaught Error: Class "Kirby\Toolkit\Collection" not found in /var/www/kirby/src/Cms/Collection.php:25 Stack trace: #0`

URL: https://getkirby.com/docs/cookbook/forms/creating-pages-from-frontend

**Comment by afbora** [comment]
I've downloaded the `eventkit` and upgraded to 3.8.0. Works great for me. At what step are you getting this error?

**Comment by chrfickinger** [comment]
Seems it was my fault. I can't reproduce it, but it is running now. Issue can be closed.

**Comment by afbora** [comment]
Thanks for testing. Lets keep open for now to upgrade the `eventkit`
