### ISSUE TITLE
Page section sortBy

### ISSUE THREAD

**Issue by Small-Systems** [getkirby/getkirby.com#1850]
The kirby docs state that:

[_The sortBy option will automatically switch off manual sorting._](https://getkirby.com/docs/reference/panel/sections/pages#sorting__sortby)

This will disable drag and drop, however the position option will still be visible in the page status dialog box:

<img width="505" alt="Screenshot 2022-10-19 at 22 52 32" src="https://user-images.githubusercontent.com/2116283/196802089-3f8e6ef6-4f15-4d27-ab9e-473f7efef801.png">

The `num:` option must be added to the child page blueprint in order to turn this off.

According the the docs I would expect the position option to also be hidden when using `sortBy:` for a page section.

**Comment by texnixe** [comment]
If you use standard numbering, this is independent of the `sortBy` option, as this only refers how the items are displayed in the Panel.
