### ISSUE TITLE
Add a WebManifest to allow adding to homescreen.

### ISSUE THREAD

**Issue by vincentrouleau** [getkirby/getkirby.com#1865]
Adding a simple WebManifest file to the site would enable adding to homescreen (at least on Android) in standalone mode (no address bar) and with a cool little loading screen. 

I personally always keep my documentation at hands and this would offer a cleaner and more effective way to access the docs on the go. 

Here's the how-to:
https://developer.mozilla.org/en-US/docs/Web/Manifest

If you guys take PR, I'll gladly do it. 

😎 See ya.

**Comment by distantnative** [comment]
Not sure if we see ourselves the need to direct our time at this but I'd think we're happy to take a PR.

**Comment by distantnative** [comment]
Not sure if we see ourselves the need to direct our time at this but I'd think we're happy to take a PR.

**Comment by vincentrouleau** [comment]
Of course!

**Comment by vincentrouleau** [comment]
#1866
