### ISSUE TITLE
Redirect Old Cheatsheet and Toolkit Paths Somewhere

### ISSUE THREAD

**Issue by neildaniels** [getkirby/getkirby.com#187]
I have bookmarks to the old cheatsheet and toolkit docs, but they both now go to "not found pages". I assume these should redirected to either the archived docs or the new docs.

Old Cheatsheet link: https://getkirby.com/docs/cheatsheet

Old Toolkit link: https://getkirby.com/docs/toolkit

**Comment by distantnative** [comment]
✅
