### ISSUE TITLE
Update Virtual pages guides with UUID warning

### ISSUE THREAD

**Issue by adamkiss** [getkirby/getkirby.com#1884]
**Issue with Reference**  
Any virtual pages guide/docbook is currently broken, in the sense that if a programmer doesn't add a **self generated uuid** to the content array of the virtual page, kirby generates the uuid and that triggers the creation of an actual page - folder and file in the filesystem.

**Expected**  
"Since 3.8.1: You must include a 'uuid' in your content file"…

**Additional note**  
I'm emphasising "self generate" uuid, because the first thing I tried was of course `'uuid'=>Uuid::generate()`, but that seems to trigger the file/folder creation as well.

**Comment by texnixe** [comment]
Add UUID to content to prevent pages being created in the file system

    Yes, you should either be able to add a UUID already to the content or you can use a Model class and return null on UUID

https://discord.com/channels/525634039965679616/525641819854471168/1030095535236980746

**Comment by texnixe** [comment]
> I'm emphasising "self generate" uuid, because the first thing I tried was of course 'uuid'=>Uuid::generate(), but that seems to trigger the file/folder creation as well.

@adamkiss, I cannot reproduce this issue in the Plainkit you provided for testing, but `Uuid::generate()` or Str::random(16)` (which is used internally in the `Uuid::generate()` method) work fine.

**Comment by adamkiss** [comment]
@texnixe You're right, `Uuid::generate()` probably works.

To explain - I first tried generating the `uuid` inside the page array, not the content array, so perhaps there was some timing issue where I reloaded before the the correct version (uuid generated in the content array) was saved or something, so the code that actually run had in fact uuid in the wrong place. This confused me into thinking that the `Uuid::generate()` also does something else that forces Kirby to actually save the page.

**Comment by bnomei** [comment]
using this in **models** works like @texnixe suggested and avoids content files for virtual pages to be created.

```php
    public function uuid(): \Kirby\Uuid\Uuid|null
    {
        return null;
    }
```

**Comment by bnomei** [comment]
@texnixe maybe add Uuid:generate() here as well?
https://getkirby.com/docs/guide/virtual-pages/merging-virtual-and-local-content

**Comment by texnixe** [comment]
Overlooked, you are right, @bnomei.

**Comment by ceesvanegmond** [comment]
> @texnixe maybe add Uuid:generate() here as well? https://getkirby.com/docs/guide/virtual-pages/merging-virtual-and-local-content

I have to say this `generate()` isn't working at mine setup. Creating a virtual page model and return `null` like this does work.

```php
<?php

use Kirby\Cms\Page;
use Kirby\Uuid\Uuid;

class VirtualPage extends Page
{
    public function uuid(): Uuid|null
    {
        return null;
    }
}

```
