### ISSUE TITLE
Add link to license hub in footer?

### ISSUE THREAD

**Issue by texnixe** [getkirby/getkirby.com#1887]
Currently, you can only find the link here: https://getkirby.com/docs/guide/quickstart#purchase-license-register-your-installation

**Comment by bastianallgeier** [comment]
Where do you think it would fit best? Resources?

**Comment by texnixe** [comment]
@bastianallgeier Would be best next to `licenses`, but then it doesn't really fit in the Kirby category. So yes, Resources would be second best.
