### ISSUE TITLE
Releases: there's no way to get to major release page other than remember / guessing / knowing the number / URL

### ISSUE THREAD

**Issue by adamkiss** [getkirby/getkirby.com#1889]
getkirby.com/releases is both redirect to github releases and a parent for "major release" release pages you did for 3.8, 3.7, etc.

From time to time (and for some tiny features, forever), the release pages (and links from them) are the best source for double checking docs, additional notes, etc.

Consider adding index, or "major release" page links to navigation, or something.

Also: the releases/(:any) aren't in the algolia index.

**Comment by texnixe** [comment]
There is already a PR: https://github.com/getkirby/getkirby.com/pull/1718

**Comment by texnixe** [comment]
https://getkirby.com/releases now links to all releases
