### ISSUE TITLE
Docs 3.8.3

### ISSUE THREAD

**Issue by afbora** [getkirby/getkirby.com#1893]
- [x] New hook: `page.render:before|after` https://github.com/getkirby/kirby/pull/4862
- [x] New hooks: `language.*:before|after` https://github.com/getkirby/kirby/pull/4861
- [x] New option uuid option: https://github.com/getkirby/kirby/pull/4868

**Comment by lukasbestle** [comment]
👉 https://github.com/getkirby/getkirby.com/pull/1899

**Comment by afbora** [comment]
- [x] Kirby query language (optional chaining and simple comparisons) https://github.com/getkirby/kirby/pull/4854
