### ISSUE TITLE
Unclear distinction `label` vs. `headline` in pages section doc

### ISSUE THREAD

**Issue by sebastiangreger** [getkirby/getkirby.com#1894]
**Issue with Reference**  
There seems to be some mixup between `label` and `headline` in the examples under https://getkirby.com/docs/reference/panel/sections/pages#headline

**Expected**  
From reading that chapter, I should be able to understand the difference between `label` and `headline`; examples in chapter `headline` should be consistent and not demonstrate `label`.

**Comment by texnixe** [comment]
Thanks @sebastiangreger Those were some leftovers from the old syntax, headline is still valid, though, for the moment.
