### ISSUE TITLE
Docs 3.9.0

### ISSUE THREAD

**Issue by distantnative** [getkirby/getkirby.com#1903]
- [x] https://github.com/getkirby/kirby/pull/4935
- [x] https://github.com/getkirby/kirby/pull/4944
- [x] https://github.com/getkirby/kirby/pull/4890
- [x] https://github.com/getkirby/kirby/pull/4934 (could not find any usage in the docs)
- [x] https://github.com/getkirby/kirby/pull/4945
- [x] https://github.com/getkirby/kirby/pull/4910

**Comment by lukasbestle** [comment]
👉 https://github.com/getkirby/getkirby.com/pull/1907
