### ISSUE TITLE
switching tab/site in panel results in hidden tab content

### ISSUE THREAD

**Issue by findthebug** [getkirby/getkirby.com#192]
Switching between site and tab/content results in hidden content page. It seems to be a update problem when u switch between tabs and site content.reloading the page manual fix the problem. see mov/yml in attachment.
 
<img width="845" alt="b" src="https://user-images.githubusercontent.com/5121132/51250072-99a41680-1995-11e9-84a1-831c55477e3f.png">
<img width="835" alt="a" src="https://user-images.githubusercontent.com/5121132/51250073-99a41680-1995-11e9-88a8-21b17d35697e.png">
 
[files.zip](https://github.com/getkirby/getkirby.com/files/2764185/files.zip)

**Comment by texnixe** [comment]
This is the wrong repo, I'm afraid. Could you please post in the kirby repo.
