### ISSUE TITLE
Mark paid plugins / allow basic price entry

### ISSUE THREAD

**Issue by tobimori** [getkirby/getkirby.com#1943]
Currently, paid plugins, such as Merx or the Google Translate plugin, have no indication that they require a paid license to be used in a project.

There should be a clear indicator that those plugins are paid in order to avoid confusion.

**Comment by lukasbestle** [comment]
Adding the price is difficult as we need to keep it updated over time and because the end price may differ when different prices are used per currency.

What we could do is to add a `Paid: true` field that will generate a "paid" pill next to the plugin name in the plugin box and on the plugin page.

**Comment by tobimori** [comment]
Exactly my thoughts.
