### ISSUE TITLE
Documentation could use more examples

### ISSUE THREAD

**Issue by manuelmoreale** [getkirby/getkirby.com#1959]
**Issue with Reference**  
I'm using a random method as an example but this can be applied more broadly to the documentation.
https://getkirby.com/docs/reference/objects/image/image/rename

Most methods are currently quite barebones and could really benefit from a working example on how that specific method could be used.

**Expected**  
A short code example showcasing how the specific method or functionality works.

**Comment by distantnative** [comment]
We will keep working on it. With the number of classes and methods, manually added examples can become hard to maintain. Maybe we can complement this more with examples from in-code docblocks.

Closing this not to disregard it but as this isn't fully actionable but general feedback that has been well received :)
