### ISSUE TITLE
[Docs] More Extensive Example Needed for Structure Field 'Columns' Option

### ISSUE THREAD

**Issue by luxlogica** [getkirby/getkirby.com#199]
The [Table Columns doc](
https://getkirby.com/docs/reference/fields/structure#table-columns) for the structure field mention that apart from 'width', we can specify text alignment, and before/after texts. Unfortunately, no example is given, and these options don't seem to be documented anywhere - e.g., what is the option name for the text alignment option, and what are the available options? It would be very helpful to have a more extensive example.

**Comment by distantnative** [comment]
✅
