### ISSUE TITLE
Docs page throws error

### ISSUE THREAD

**Issue by CHE1RON** [getkirby/getkirby.com#1994]
https://getkirby.com/docs/reference/objects/email/email/__construct

throws whatever:

<img width="556" alt="Screenshot 2023-04-01 at 14 14 23" src="https://user-images.githubusercontent.com/122524301/229287975-9a1eabfd-3462-4a26-951c-4b3b7628a191.png">

**Comment by lukasbestle** [comment]
The error I'm getting locally is:

```
Call to undefined method ReflectionUnionType::getName()

in site/models/reference-class.php:240
```

A `ReflectionUnionType` provides an array of `ReflectionType` objects in `$type->getTypes()`, each of which will then have `$type->getName()`. I think we need a special case for that that loops through the union types.

**Comment by CHE1RON** [comment]
👍

**Comment by distantnative** [comment]
@CHE1RON thanks for reporting it btw! 🙏

**Comment by CHE1RON** [comment]
Sure thing!
