### ISSUE TITLE
Remote requests: documentation needed

### ISSUE THREAD

**Issue by adamkiss** [getkirby/getkirby.com#1998]
**Issue with Reference**  

`Remote` class is quite a pleasant class to work with - single function to do most kinds of requests. Unfortunately, the documentation is just an autogenerated reference, which misses:

- all the variations - `Remote::{http verb}`, only ` Remote::get()` is shown
- full list of `[arguments]` and when/how to use them
- explanation of arguments:
  - when to use Kirby stuff (basicAuth, data), and when to use headers (Bearer auth)
  - difference between body and data (I always start with "body", but the request body is in data? only when JSON?)
  - headers is not an array of `['Header' => 'value']`, but `['Header: value']`

I've worked with the classes many times, and every time, it takes 30 minutes to get one command right - when in the end, the call itself is very nice to get back to.

Thank you

**Comment by texnixe** [comment]
@adamkiss Please check out the added examples and let me know if you still find stuff missing:

https://getkirby.com/docs/reference/objects/http/remote

**Comment by texnixe** [comment]
Ok, closing this, feel free to reopen if not sufficient, @adamkiss
