### ISSUE TITLE
[Docs] Panel UI palette

### ISSUE THREAD

**Issue by jenstornell** [getkirby/getkirby.com#20]
All the colors used in the panel. Someone, maybe Fabian had a great list of colors a long time ago.

If there are css variables that we can use, it may be helpful as well.

**Comment by fabianmichael** [comment]
@texnixe @bastianallgeier I’d like to do that over next week … should we place it into the Cheatsheet? We could also add a a few paragraphs or another page on typography (recommended font stacks for sans-serif and monospace), visual hierarchy etc. Should I place it into the **Plugins** or the **Panel** section?
