### ISSUE TITLE
Guide for Templates / Snippets is producing an error

### ISSUE THREAD

**Issue by fritzlaszlo** [getkirby/getkirby.com#2002]
The reference page / guide under [https://getkirby.com/docs/guide/templates/snippets](https://getkirby.com/docs/guide/templates/snippets) is delivering a classic kirby-php-error: 

> This page is currently offline due to an unexpected error. We are very sorry for the inconvenience and will fix it as soon as possible. 

I am uncertain if this is a server error or code problem, aka if a github issue is the right place for this, but I guess its not the worst place to post this?

**Comment by texnixe** [comment]
Thanks for reporting, fixed via 2d5effbb22c1600d712bb50e678ba576795fe18f
