### ISSUE TITLE
Outdated Made with Kirby items

### ISSUE THREAD

**Issue by tobimori** [getkirby/getkirby.com#2023]
- Habita is offline
<img width="465" alt="CleanShot 2023-05-10 at 13 43 07@2x" src="https://github.com/getkirby/getkirby.com/assets/29142128/d401f320-0f6a-45a3-8814-a4a1e13aef73">

- Sean Purdy is now behind a .htaccess Auth
<img width="442" alt="CleanShot 2023-05-10 at 13 44 59@2x" src="https://github.com/getkirby/getkirby.com/assets/29142128/9bbd013e-9a73-4f2d-a062-e17497e85b27">

**Comment by texnixe** [comment]
Thanks, Tobi, fixed.
