### ISSUE TITLE
Images on releases page are very blurry

### ISSUE THREAD

**Issue by tobimori** [getkirby/getkirby.com#2026]
<img width="1438" alt="CleanShot 2023-05-16 at 15 04 06@2x" src="https://github.com/getkirby/getkirby.com/assets/29142128/544468a6-32eb-4823-b696-268033e86d28">

**Comment by lukasbestle** [comment]
I've replaced the code to use `srcset`, which makes the images significantly less blurry on mobile but just slightly less blurry on desktop (caused by the scaling factors – scaling down a screenshot by a weird non-integer factor always causes blur).
