### ISSUE TITLE
Partner profile: Fix two-column layout in medium width

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/getkirby.com#2039]
The partner info and expertise get moved to the right of the description in the medium width layout:

https://github.com/getkirby/getkirby.com/blob/24c64a2c001c0541d1bf12534c1722a0ce71951b/site/templates/partner.php#L20-L30

It looks like the changes to make these parts sticky in the large width layout broke this.

**Comment by distantnative** [comment]
Can you add a screenshot of the problem?

**Comment by lukasbestle** [comment]
Sure 🙂

**Current layout:**

![Bildschirmfoto 2023-06-03 um 18 25 27](https://github.com/getkirby/getkirby.com/assets/1595007/b7b485d8-518f-48ce-b265-9e13852ed8c3)

**Old layout:**

![Bildschirmfoto 2023-06-03 um 18 29 21](https://github.com/getkirby/getkirby.com/assets/1595007/2e960f9f-c898-44f5-937a-d76ecc3726be)

Going back to the old layout doesn't make sense with the reordering of "description first, info and expertise afterwards". But maybe we could delete the lines I linked to above and instead also use a sticky sidebar for info and expertise in this medium width.
