### ISSUE TITLE
Archived docs for 3.8 missing

### ISSUE THREAD

**Issue by bezin** [getkirby/getkirby.com#2053]
The [Docs Archive](https://getkirby.com/docs/archive) misses docs for Kirby 3.8. 

![2023-06-23 14_49_56](https://github.com/getkirby/getkirby.com/assets/4400435/fcaf3908-b32b-4aab-a312-61a0469b591f)

**Comment by texnixe** [comment]
It's not so much about the version missing from the archive page, but there is no link to a 3.8 version of the docs for some reason, @bastianallgeier?

**Comment by bastianallgeier** [comment]
It looks like we simply forgot about it to be honest.

**Comment by distantnative** [comment]
@bastianallgeier I think if we check out he state from https://github.com/getkirby/getkirby.com/commit/6844b6efef6dac8b7d7d2bcf89882c2ded56fc07 again, this could be used to still create the 3.8 docs archive

**Comment by texnixe** [comment]
This is now fixed
