### ISSUE TITLE
Does the `storage` root exist?

### ISSUE THREAD

**Issue by danburzo** [getkirby/getkirby.com#2065]
**Issue with Reference**  

The code sample in the [Public folder setup](https://getkirby.com/docs/guide/configuration#custom-folder-setup__public-folder-setup) includes a `storage` root. As far as I can tell, this is not a configurable root. 

**Expected**  

The code sample should reflect the current API.

**Screenshots**

**Comment by distantnative** [comment]
Have you tried defining it as shown in the guide's `index.php` section?

**Comment by danburzo** [comment]
Yes, I have tried it. I did not mean to suggest it doesn’t work, but that was slightly confusing. By passing them to the Kirby constructor, the sample gives the impression `base` and `storage` are configurable roots.

IMHO something like this makes it clearer at a glance:

```php
<?php

$base = dirname(__DIR__);

include $base . '/kirby/vendor/autoload.php';

$kirby = new Kirby([
    'roots' => [
        'index'    => $base . '/public',
        'content'  => $base . '/content',
        'site'     => $base . '/site',
        'accounts' => $base . '/storage/accounts',
        'cache'    => $base . '/storage/cache',
        'sessions' => $base . '/storage/sessions',
    ]
]);

echo $kirby->render();
```

**Comment by distantnative** [comment]
But I would think you can configure any custom roots. Maybe need to check this again. But that’s why I was asking if you actually did configure it and it didn’t work for you.

**Comment by texnixe** [comment]
This is an old topic, but I think we can close it? `$base` and `storage` are not roots we are defining, the roots are `index`, `content`, `site` etc. and what is on the right-hand side are the paths we assign to those roots. And you are totally free to create any structure in your project, as long as you make sure that you assign the resulting paths to Kirby's roots.
