### ISSUE TITLE
Denglish on pricing page?

### ISSUE THREAD

**Issue by johannahoerrmann** [getkirby/getkirby.com#207]
> Yes, students, educational projects, open-source projects or non-profit organizations can apply for a discount. Please get in contact to apply.

https://getkirby.com/buy

Not entirely sure about this, but "get in contact" doesn't sound right to me. I would use "get in touch" or "contact us" instead. Any active native speakers to confirm?

**Comment by texnixe** [comment]
While I think "get in contact" is correct, it's definitely clunky.
✅
