### ISSUE TITLE
getkirby.com - arrangement image and side menu 

### ISSUE THREAD

**Issue by zeljkovorel** [getkirby/getkirby.com#2078]
Hello everyone,
when opening getkirby.com, I see following :

![getKirbyCom](https://github.com/getkirby/getkirby.com/assets/88711468/d16d901a-e546-4f2b-8dd2-53883abba6d9)

The vertical arrangement of the top menu, image and side menu is not in line.

Browsers tested:
Chrome: Version 116.0.5845.96
Edge: Version 115.0.1901.203

Best regards

**Comment by distantnative** [comment]
The overflow of the image to the left and the little menu to the right outside of the main content column is intended.

**Comment by zeljkovorel** [comment]
First moment of truth - it looks like a CSS issue.
But if it's intended, I'll close the the issue.
