### ISSUE TITLE
To slash or not to slash cookbook article breaks image urls on first request

### ISSUE THREAD

**Issue by ovenum** [getkirby/getkirby.com#2085]
The Rewrite Rules suggested in the Cookbook article _[To slash or not to slash cookbook](https://getkirby.com/docs/cookbook/setup/trailing-slash)_ will add a trailing slash to every URL that:
-  is not excluded by the additional RewriteConditions,
- does not point to an existing file on the server,
- and does not have a trailing slash already

This will break URLs for image FileVersions when they are requested for the first time.

The file for a url like `/media/page/something/someimage-version-string.jpg` will not exists inside the media folder before it’s been requested at least once. With the articles rewrite rules in place, a 301 redirect to its trailing slashed version `/media/page/something/someimage-version-string.jpg/` is issued. This causes the server to respond with a 404 for the requested image.

The weird thing is: this is only reliable reproducible when i directly enter the trailing slashed url in the browser address bar.

Adding an additional rewrite condition to exclude all urls starting with media fixed the issue.

```
# force trailing slash
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_URI} !^/api
RewriteCond %{REQUEST_URI} !^/panel
RewriteCond %{REQUEST_URI} !^/media
RewriteRule ^(.*[^/])$ /$1/ [L,R=301]
```

Have posted this on [Discord](https://discord.com/channels/525634039965679616/809460677658804234/1149629594639552624) but thought this is the more appropriate place.

**Comment by lukasbestle** [comment]
Thanks 👍
