### ISSUE TITLE
docs: hook methods are missing

### ISSUE THREAD

**Issue by mauricerenck** [getkirby/getkirby.com#2089]
The [documentation for hooks](https://getkirby.com/docs/reference/plugins/extensions/hooks#creating-your-own-hooks) mentions both `$kirby->trigger()` and `$kirby-apply()` but both methods do not appear in the reference here: https://getkirby.com/docs/reference/objects/cms/app

**Comment by distantnative** [comment]
Will be added with the release of Kirby 3.9.7 - thanks @lukasbestle
