### ISSUE TITLE
Reference: icons show svg in overview

### ISSUE THREAD

**Issue by distantnative** [getkirby/getkirby.com#210]

**Comment by mrflix** [comment]
Did you mean adding them here?

![image](https://user-images.githubusercontent.com/60777/58865130-50d7ca80-86b6-11e9-880c-5835770b007a.png)

Cause that would be awesome!

**Comment by texnixe** [comment]
How is this different from #171? Duplicate?

**Comment by distantnative** [comment]
Duplicate indeed
