### ISSUE TITLE
Content from database recipe: wrong method signatures 

### ISSUE THREAD

**Issue by mrflix** [getkirby/getkirby.com#2106]
@lukasbestle it seems that some of the method signatures you [recently](https://github.com/getkirby/getkirby.com/commit/747b230e9422e5d3d307df89e58691c8277520cb) added to the [content from database recipe](https://getkirby.com/docs/guide/virtual-pages/content-from-database#advanced-setup__the-extended-comment-php-model) are wrong:

```php
protected function changeStatusToDraft(): static
{
    $data['status'] = 'null';

    if ($comment = Db::first('comments', '*', ['slug' => $this->slug()])) {
        return Db::update('comments', $data, ['slug' => $this->slug()]);
    }

    return $this;
}
```

Or rather the code has to be adjusted to match the `static` signature, since it's getting enforced in v4.

I have two pages with virtual pages where I use this code and with one I'm currently running into this problem:

> PHP message: TypeError: CustomPage::changeStatusToUnlisted(): Return value must be of type CustomPage, bool returned in site/models/custom.php:54

I think the two methods with this mix of boolean and static return – `changeStatusToDraft` and `changeStatusToUnlisted` – can be rewritten to behave like the methods around them that check for the `Db::update` boolean response and return `$this` on true:

```php
public function changeSlug(string $slug, string|null $languageCode = null): static
{
    // always sanitize the slug
    $slug = Str::slug($slug);


    $data['slug'] = $slug;

    if ($comment = Db::first('comments', '*', ['slug' => $this->slug()])) {
        if (Db::update('comments', $data, ['slug' => $this->slug()])) {
            return $this;
        };
    }
    return $this;
}
```

**Comment by lukasbestle** [comment]
Thanks 👍
Since there is another identical `return` statement directly below, I've fixed it by omitting the return value all-together. I've also cleaned up the code some more.

**Comment by mrflix** [comment]
Awesome – that was very fast. Thanks Lukas!
