### ISSUE TITLE
Field properties tables are missing in the docs currently

### ISSUE THREAD

**Issue by philipmarnef** [getkirby/getkirby.com#2108]
Every Field properties section in the docs show (field-options: <type>) instead of the properties table. Seems like a Kirby tag isn't being rendered or something?

**Comment by lukasbestle** [comment]
Locally I get the following exception:

```
Whoops\Exception\ErrorException thrown with message "Undefined array key "variadic"

Stacktrace:
#29 Whoops\Exception\ErrorException in getkirby.com/site/snippets/templates/reference/entry/parameters.php:46
```

Seems to be caused by cfa6d7a756eab0b1a63b50ca0b93e57e65ce84ae @distantnative

**Comment by lukasbestle** [comment]
@distantnative Can a field ever have variadic properties? Otherwise I think it's an easy fix to `?? null` the value.

**Comment by adamkiss** [comment]
@lukasbestle that's a good fix regardless. Or `$row['variadic'] ?? False`

**Comment by distantnative** [comment]
Sorry! Fixing it!

**Comment by philipmarnef** [comment]
Fixed in an hour on a Saturday 👏👏👏

**Comment by distantnative** [comment]
Haha well I also added the bug today... so 😅😂
