### ISSUE TITLE
[Docs] Guide for Blueprints should remove usage of 'sidebar' or add a link or explanation 

### ISSUE THREAD

**Issue by SirNovi** [getkirby/getkirby.com#214]
I had a quite frustrating time with the guide for blueprints. 

https://getkirby.com/docs/guide/blueprints/extending-blueprints#reusing-and-extending-field-groups

There the blueprint code for reusing a fields group is as follows

```
sidebar:
  meta:
    type: fields
    fields:
      meta: fields/meta
```

I got stuck here for quite some time as I did not get it to work and then I just figured that it must be a mistake and "sidebar" was supposed to be "sections". 

I know now that "sidebar" is a thing that is available to adjust the sidebar on a panel page, but only if you use `preset: page`. Nothing about this is mentioned anywhere on this page and to be able to know it you would have needed to read the whole docs first. 

In my opinion it should not be used there because it only adds unneeded complexity. It is not needed to reuse field groups. Sure would have saved me quite some time if it wouldn't have been used there.

If you know about said "sidebar" than you will surely be able to add field groups there without it being mentioned on this page. And if you don't know about it it really confuses you.

**Comment by distantnative** [comment]
✅
