### ISSUE TITLE
More in-depth documentation about customizing the Panel sidebar

### ISSUE THREAD

**Issue by texnixe** [getkirby/getkirby.com#2154]
e.g. how to open page create dialog directly from the sidebar as shown in the video etc.

**Comment by distantnative** [comment]
@texnixe I can take a stab at it. Do you think it should also go into https://getkirby.com/docs/reference/system/options/panel#panel-menu or maybe a Cookbook recipe that allows us to slim down that Reference part and link to the Cookbook recipe for all the twists and turns?
