### ISSUE TITLE
Docs: broken link in the cheat sheet — https://getkirby.com/docs/cheatsheet/pages/current

### ISSUE THREAD

**Issue by bastianallgeier** [getkirby/getkirby.com#216]

**Comment by lukasbestle** [comment]
Hm, very strange. I will look into this.

**Comment by texnixe** [comment]
This, in fact, affects all links to the collection class

**Comment by lukasbestle** [comment]
Turns out it was because the `Collection` class itself inherits from the `I` class. This broke the page fetching code somehow.
