### ISSUE TITLE
Repository button reports stable version number but GitHub will download the pre-release

### ISSUE THREAD

**Issue by tobimori** [getkirby/getkirby.com#2172]
![CleanShot 2024-01-13 at 11 19 44@2x](https://github.com/getkirby/getkirby.com/assets/29142128/6bfbb348-6d9b-4e66-87c7-e98301659bc3)
![CleanShot 2024-01-13 at 11 20 25@2x](https://github.com/getkirby/getkirby.com/assets/29142128/4b2e9cda-a373-4946-abb8-262a4575d1e6)
https://getkirby.com/plugins/tobimori/icon-field

**Comment by afbora** [comment]
I think if version available for the plugin, download link should be like that:

> https://github.com/tobimori/kirby-icon-field/archive/refs/tags/1.0.3.zip

Otherwise current zipball url can be use as fallback.
