### ISSUE TITLE
Page layout table: document more column types

### ISSUE THREAD

**Issue by distantnative** [getkirby/getkirby.com#2175]
https://getkirby.com/docs/reference/panel/sections/pages#layout

<img width="826" alt="Screenshot 2024-01-15 at 09 57 16" src="https://github.com/getkirby/getkirby.com/assets/3788865/c778cc87-1e2f-48fd-8705-43463d6d8648">

**Comment by bastianallgeier** [comment]
I think it would be really good to start with lab examples for all those types first. The setup is sometimes quite weird.
