### ISSUE TITLE
Centralize options docs, especially dynamic options

### ISSUE THREAD

**Issue by distantnative** [getkirby/getkirby.com#2185]
Currently we are duplicating docs in many options fields - would be better to just have the basics there and then link off to an options compendium page or so.

**Comment by bastianallgeier** [comment]
But it's a snippet so we technically only have one place for them. From a user perspective, I feel like it's more helpful to not have to jump to a different page. But we could maybe keep it a bit more high-level and then have a detailed guide for options.

**Comment by distantnative** [comment]
It's just so extensive but then not applicable to every field, e.g. the color field cannot really use the snippet. It wouldn't make a lot of sense with the phrasing, examples etc.

**Comment by texnixe** [comment]
> From a user perspective, I feel like it's more helpful to not have to jump to a different page.

I agree, that wouldn't make sense.

But I'm not quite sure, what this refers to, exactly. When creating such issues, a link to the document in question would be helpful.

**Comment by distantnative** [comment]
E.g.

https://getkirby.com/docs/reference/panel/fields/checkboxes#dynamic-options
https://getkirby.com/docs/reference/panel/fields/select#dynamic-options

vs.

https://getkirby.com/docs/reference/panel/fields/color#options
