### ISSUE TITLE
Document config option "editor"

### ISSUE THREAD

**Issue by mrflix** [getkirby/getkirby.com#2233]
See https://feedback.getkirby.com/616

Stumbled upon it recently by accident. Would be nice to have it in the docs.

![1_config php](https://github.com/getkirby/getkirby.com/assets/60777/12423aee-8b02-4be5-876c-128a55f64d46)
![2_whoops](https://github.com/getkirby/getkirby.com/assets/60777/443cf76f-7ffe-48a8-afb9-3934bd04859c)
![3_dialog](https://github.com/getkirby/getkirby.com/assets/60777/f779bbae-3847-4a18-a0b8-9eadb68e8374)

**Comment by bastianallgeier** [comment]
https://getkirby.com/docs/reference/system/options/editor

**Comment by mrflix** [comment]
Sorry, a bit late, but for my case with Sublime Text it was very important to install the [special handler](https://github.com/inopinatus/sublime_url) as noted in the [Whoops docs](https://github.com/filp/whoops/blob/master/docs/Open%20Files%20In%20An%20Editor.md). I don't know how people will find out about that from within the reference.
