### ISSUE TITLE
Missing redirects after content changes

### ISSUE THREAD

**Issue by bastianallgeier** [getkirby/getkirby.com#2271]
- [x] https://getkirby.com/docs/guide/virtual-pages/content-from-rss-feed
- [x] https://getkirby.com/docs/guide/virtual-pages/simple-virtual-page
- [x] https://getkirby.com/docs/cookbook/extensions/virtual-files
- [x] https://getkirby.com/docs/cookbook/setup/git
- [x] https://getkirby.com/docs/cookbook/content-representations/load-more-with-ajax
- [x] https://getkirby.com/docs/guide/files/files ([related article](https://getkirby.com/docs/reference/panel/fields/files#upload-options__restricting-uploads-to-certain-file-types))

**Comment by ghost** [comment]
- https://getkirby.com/docs/cookbook/setup/git

**Comment by samlinck** [comment]
- https://getkirby.com/docs/cookbook/content-representations/load-more-with-ajax

**Comment by texnixe** [comment]
I fixed some of them, but couldn't find with a full-text-search where those wrong virtual-pages links are supposed to be used, not the setup/git one

**Comment by distantnative** [comment]
Code | Invalid link | Found on
-- | -- | --
404 | /blog/a-new-starterkit-for-kirby | /kosmos/5
404 | /blog/habita | /kosmos/11
404 | /blog/interface-lovers | /kosmos/12
404 | /blog/questions-about-kirby-3 | /kosmos/25
404 | /blog/why-tower-has-gone-kirby | /kosmos/9
404 | /changelog/kirby-2-3-1 | /kosmos/2
404 | /changelog/kirby-2-3-2 | /kosmos/2
404 | /changelog/kirby-2-4-0 | /kosmos/5
404 | /changelog/kirby-2-4-0-beta-1 | /kosmos/4
404 | /changelog/kirby-2-5-0 | /kosmos/13
404 | /changelog/kirby-2-5-3 | /kosmos/14
404 | /changelog/kirby-2-5-4 | /kosmos/14
404 | /changelog/kirby-2-5-5 | /kosmos/15
404 | /changelog/kirby-2-5-6 | /kosmos/16
404 | /changelog/kirby-2-5-7 | /kosmos/18
404 | /changelog/kirby-2-5-9 | /kosmos/21
404 | /docs/cookbook/ajax-form-validation | /kosmos/4
404 | /docs/cookbook/ajax-load-more | /kosmos/4
404 | /docs/cookbook/deploying-with-capistrano | /kosmos/5
404 | /docs/cookbook/handling-images-in-kirby | /kosmos/9
404 | /docs/cookbook/multilanguage-secrets | /kosmos/10
404 | /docs/cookbook/relmeauth | /kosmos/12
404 | /docs/cookbook/sorting-and-grouping | /kosmos/11
404 | /docs/fonts/bwgradual-bold-webfont.woff | /docs/quicktips/panel-branding
404 | /docs/fonts/bwgradual-bold-webfont.woff2 | /docs/quicktips/panel-branding
404 | /docs/guide/../cookbook/panel/customizing-panel | /docs/reference/panel/styling
404 | /docs/guide/content/files | /docs/quicktips/update-file-metadata
404 | /docs/guide/files/files | /docs/cookbook/performance/responsive-images
404 | /docs/img/logo-dark.svg | /docs/quicktips/panel-branding
404 | /docs/quicktip/fine-tuning-the-cache | /kosmos/43
404 | /docs/quicktips/frontend-libraries | /kosmos/75
404 | /error | /docs/cookbook/performance/&lt;
404 | /konf | /kosmos/42
404 | /next | /kosmos/26
✅ | /docs/quicktips/multisite | /docs/cookbook/development-deployment/multisite-variant
✅ | /kits/starterkit/ | /kosmos/5
✅ | /plugins/diesdasdigital/metaknight | /kosmos/54
✅ | /quicktips/panel-branding | /kosmos/66
✅ | /releases/%20https:/getkirby.com/releases/3.8/migration-sites | /releases/3.8
✅ | /releases/%20https:/getkirby.com/releases/3.9/migration-sites | /releases/3.9
✅ | /should | /docs/cookbook/performance/lazy-loading

**Comment by texnixe** [comment]
IMO, doesn't make sense to fix the old kosmos issues for stuff that often doesn't exist anymore. It's an archive, after all.

**Comment by distantnative** [comment]
I would agree for things where we simply don't have an equivalent nor anymore. But where we can think of a new/correct target, would make sense to still fix it.

**Comment by distantnative** [comment]
>  but couldn't find with a full-text-search where those wrong virtual-pages links are supposed to be used, not the setup/git one

@texnixe could these be external links to these? - we could add redirects to those then.

**Comment by texnixe** [comment]
@distantnative Unfortunately, it doesn't say, but yes, could be old forum links etc.
