### ISSUE TITLE
Typo on Install & update via download

### ISSUE THREAD

**Issue by distantnative** [getkirby/getkirby.com#2285]
Colon after Plainkit:

<img width="727" alt="Screenshot 2024-04-01 at 21 19 15" src="https://github.com/getkirby/getkirby.com/assets/3788865/75c5a98d-39c9-4d70-b848-9438a77e7924">

**Comment by texnixe** [comment]
https://github.com/getkirby/getkirby.com/commit/cb89d809a66d88d96e4fe35e0b9178f23a6120a7
