### ISSUE TITLE
Menu link to guide/complete navigation in reference

### ISSUE THREAD

**Issue by texnixe** [getkirby/getkirby.com#229]

**Comment by distantnative** [comment]
@texnixe did you have specific places in mind where this is still missing?

**Comment by texnixe** [comment]
No, I'd just meant to have a link from the reference topbar to the guide. The K-Logo at the top leads to the homepage, so if I want to go back to the guide, I need two steps, which I find pretty annoying.

**Comment by distantnative** [comment]
Closing this in favour of #147 but agreed that this then should link back to the guide not the frontpage.
