### ISSUE TITLE
Pages section table layout, no way to switch off title column

### ISSUE THREAD

**Issue by medienbaecker** [getkirby/getkirby.com#2291]
In the pages section table layout it's not possible to remove the title column. That is however [implied in the docs](https://getkirby.com/docs/reference/panel/sections/pages#layout__table-layout:~:text=You%20can%20switch%20off%20those%20automatic%20columns%20with).

Here's the code that (if I understand it correctly) prevents the "essential" columns from being overwritten: https://github.com/getkirby/kirby/blob/main/config/sections/mixins/layout.php#L133-L135

**Comment by bastianallgeier** [comment]
Will be fixed in 4.2.0
