### ISSUE TITLE
Can't find sections in search

### ISSUE THREAD

**Issue by medienbaecker** [getkirby/getkirby.com#231]
I often have to search for the `pages` or `files` section. While [#155](https://github.com/getkirby/getkirby.com/issues/155) might help, I think these pages are not even indexed. They can't be found in the search. Not even when clicking on "View all results".

![section-search](https://user-images.githubusercontent.com/7975568/51443553-b9677180-1cea-11e9-9736-f34ed6b285e1.gif)

These are the pages I want to find:

https://getkirby.com/docs/reference/panel/sections/pages
https://getkirby.com/docs/reference/panel/sections/info
https://getkirby.com/docs/reference/panel/sections/files
https://getkirby.com/docs/reference/panel/sections/fields

**Comment by distantnative** [comment]
✅ Thanks for pointing us to that flaw. Fixed it - still working on slightly improving the ranking.
