### ISSUE TITLE
Tiny should be removed and add Huge if correct

### ISSUE THREAD

**Issue by luxuryluke** [getkirby/getkirby.com#2330]
https://github.com/getkirby/getkirby.com/blame/2ba8c57191333cf06d5eba9bc840cbd04c406a12/kirby/config/sections/stats.php#L29

Searched for ‘tiny’ for stats report cards and couldn't find it. Did see several references to 'huge', though, so perhaps this text and any other site text referencing 'tiny' stats report cards should be removed and the 'huge' value added in.

https://getkirby.com/docs/reference/panel/sections/stats#section-properties

**Comment by texnixe** [comment]
I already fixed it earlier today, the available sizes are small, medium, large and huge, docs were a bit contradictory and so is the in-code documentation.

**Comment by luxuryluke** [comment]
Thank you, Sonja! You rock!
