### ISSUE TITLE
Missing $users->findByKey() on reference page

### ISSUE THREAD

**Issue by floriankuek** [getkirby/getkirby.com#2335]
**Issue with Reference**  
The docs are missing $users->findByKey() under the reference [page](https://getkirby.com/docs/reference/objects/cms/users).

**Expected**  
The docs should include the method defined in the $user object [here](https://github.com/getkirby/kirby/blob/4.3.0/src/Cms/Users.php#L109). Thank you :)

**Comment by distantnative** [comment]
It's an internal method and thus not documented. Any reason why you don't want to use just `$user->find()`?

**Comment by floriankuek** [comment]
Gotcha. I definitely missed that. I use `$user = kirby()->users()->findByKey($email);` to determine if the provided email on login belongs to an already existing local user. If nothing is being returned I then query AD.
