### ISSUE TITLE
Blog documentation incorrect?

### ISSUE THREAD

**Issue by oilstel** [getkirby/getkirby.com#234]
I was following the documentation for creating a blog at this [doc](https://getkirby.com/docs/reference/panel/samples/blog). Everything worked but `articles.yml` was not finding `article.yml`. From the documentation it looks like `article.yml` should be under the `sections/` directory but `articles.yml` can't find it that way. What worked for me was placing `article.yml` under `pages/`. Not sure if this is a problem with the documentation or a problem with how I implemented it but either way it could be clearer in the docs : ). Anyways loving Kirby 3. Thanks for all the hard work!

**Comment by distantnative** [comment]
Let me have a look :)

**Comment by distantnative** [comment]
Yes, you are totally right. In the "Single article" part it must be `/site/blueprints/pages/article.yml` not `/site/blueprints/sections/article.yml`. Will fix it in a second.

**Comment by distantnative** [comment]
✅ Thanks for spotting it - and great that you like Kirby 3!
