### ISSUE TITLE
Improve `Past Security Incidents` table style

### ISSUE THREAD

**Issue by afbora** [getkirby/getkirby.com#2346]
TBH Past Security Incidents table doesn't looks good. Especially `Affected` and `Severity` columns should be fixed.

![screen-capture-1872-Security Policy - Kirby CMS-getkirby com](https://github.com/getkirby/getkirby.com/assets/3393422/2048341e-928c-461a-926e-fae689936793)

**Comment by lukasbestle** [comment]
I think this depends on the browser and/or operating system (due to different system fonts). In Safari I never had such issues, but could reproduce the issues in the first column in Chrome. I've now tried to fix it, please test again and reopen if the issue persists for you.

**Comment by afbora** [comment]
Now looks very nice 🎉 Thank you @lukasbestle
