### ISSUE TITLE
Recipe: Using a CDN with Kirby

### ISSUE THREAD

**Issue by luxlogica** [getkirby/getkirby.com#236]
Website speed is becoming a more relevant and important factor in development, and search engines are starting to use site loading speed as a factor that influences a site's ranking. Because of this, more and more developers are interested in using CDNs in order to increase their site's speed. As the number of available CDN services proliferate, and they become cheaper, using them is becoming an increasingly attractive option, even for small projects.

It would be extremely helpful if Kirby had a **Cookbook recipe** on _How to Use Kirby with a CDN_ - giving step-by-step instructions on how to do necessary things such as custom assets and media folder setup, setting up controllers/routers to rewrite URLs, setting up any necessary hooks, and dealing with cache. 

If I remember correctly, @jenstornell used to have a neat CDN plugin for Kirby 2. If anyone is working on a similar plugin for 3 it might be worthwhile mentioning it, too.

**Comment by texnixe** [comment]
A cookbook recipe is on the list.

And there's also an updated keycdn plugin right in the getkirby.com website for you to check out: https://github.com/getkirby/getkirby.com/tree/master/site/plugins/keycdn.

Also, their are some other secret plugins that might be interesting: https://github.com/getkirby/getkirby.com/tree/master/site/plugins

**Comment by texnixe** [comment]
PR: https://github.com/getkirby/getkirby.com/pull/899

Postponed, because Kirby should make this easier first.

**Comment by bastianallgeier** [comment]
✅
