### ISSUE TITLE
Broken Link "files section"

### ISSUE THREAD

**Issue by gbdesign2023** [getkirby/getkirby.com#2364]
**Issue with Reference**  
The page https://getkirby.com/docs/reference/panel/fields/files
contains a broken link: 
https://getkirby.com/docs/reference/sections/files-section

**Expected**  
new link: 
https://getkirby.com/docs/reference/panel/sections/files

**Screenshots**  
<img width="882" alt="broken-link" src="https://github.com/user-attachments/assets/d42fbe0c-43bc-471a-9554-4e87a7a3686b">

**Comment by texnixe** [comment]
Thanks, fixed.

**Comment by gbdesign2023** [comment]
@texnixe That was ‘lightning’ fast! Fitting for the current weather ;-)
