### ISSUE TITLE
Broken link to update instructions from Security page

### ISSUE THREAD

**Issue by philgyford** [getkirby/getkirby.com#2378]
**Issue with Reference**  
On https://getkirby.com/docs/guide/security there is a link in the first section in this text:

> Please follow these [instructions on how to update your installation](https://getkirby.com/docs/guide/installation#updates).

That link goes to a 404 page.

Given you have several "Install & update" pages for different methods, I'm not sure where it's supposed to link to.

**Comment by bastianallgeier** [comment]
Thanks for letting us know. I just fixed the link.
