### ISSUE TITLE
Site: Broken Headline IDs

### ISSUE THREAD

**Issue by bastianallgeier** [getkirby/getkirby.com#24]
On page http://getkirby.com/docs/content/text anchor link to videos is broken: http://getkirby.com/docs/content/text#youtube-amp-vimeo-videos but the id of that h2 is "youtube--vimeo-videos" ("amp" is missing).

**Comment by jaydenseric** [comment]
Was just about to report this then found this issue already already logged :)

**Comment by bastianallgeier** [comment]
I just finally fixed this :D
