### ISSUE TITLE
Search results hidden behind info box

### ISSUE THREAD

**Issue by texnixe** [getkirby/getkirby.com#248]
If an infobox is used at the top of a page, the result list is hidden behind the box.

Safari Version 12.0.2 (14606.3.4)
MacOS Mojave

<img width="708" alt="bildschirmfoto 2019-01-24 um 00 02 24" src="https://user-images.githubusercontent.com/5312492/51643129-baf39c80-1f6b-11e9-8031-f3ba8900b483.png">

**Comment by distantnative** [comment]
Will be fixed the next time dist files are built. ✅
