### ISSUE TITLE
"smartypants.parser" option deprecated in Kirby 2.3.0

### ISSUE THREAD

**Issue by texnixe** [getkirby/getkirby.com#251]

**Comment by texnixe** [comment]
@bastianallgeier : How do we handle this? Add a note? Special field? Remove?

**Comment by bastianallgeier** [comment]
I think we should remove it. Since we don't really offer docs for multiple versions, there will be no other easy way to display it properly.

**Comment by jenstornell** [comment]
Agree. In cases like this, to make it really clear, maybe add these kind of changes to the changelog? Then it's easier to see when it was depricated. Maybe even have a deprectated section with all documented functions that are deprecated in the new version.

**Comment by bastianallgeier** [comment]
@jenstornell I think we are pretty extensive in the changelog nowadays and try to mention everything that has been deprecated. But in earlier versions this has not always been true :) To actually add a list of deprecated features separately is a good idea though.

**Comment by texnixe** [comment]
Yes, a RIP section.
