### ISSUE TITLE
Missing link to the Kirby Cheatsheet in blog post Fun with menus

### ISSUE THREAD

**Issue by buk** [getkirby/getkirby.com#256]
Hey there,

there is a broken link you can find in the _The entire API_ section at the end of the blog post [Fun with menus](https://getkirby.com/blog/fun-with-menus)

Kind regards,
Sebastian

**Comment by texnixe** [comment]
Thanks for pointing this out. I fixed it via https://github.com/getkirby/getkirby.com/commit/38d4f5057c865a78066680dc437dd31a5b5290ea
