### ISSUE TITLE
Typo in custom panel css dev guide

### ISSUE THREAD

**Issue by Thiousi** [getkirby/getkirby.com#258]
In [Custom Panel CSS - Dev guide](https://github.com/getkirby/getkirby.com/blob/dc8e1392051040e35adca90bc0d399a780f58806/content/1-docs/8-developer-guide/3-panel/2-css/docs.txt)
Line 16 is:
`c::set('panel.stylesheet', '/assets/css/panel.css');`

It should be:
`c::set('panel.stylesheet', 'assets/css/panel.css');`

**Comment by texnixe** [comment]
Thanks for pointing this out. I've just fixed it: https://github.com/getkirby/getkirby.com/commit/59a10c61f46cae6e03ec8bab985d27e8ba6d18db
