### ISSUE TITLE
Blueprint options absent from navigation

### ISSUE THREAD

**Issue by malvese** [getkirby/getkirby.com#263]
The page at URL `getkirby.com/docs/panel/blueprints/options` is invisible and therefore not listed in the navigation menu.
I just fumbled for this information on the website, then only found it via Google.

**Comment by lukasbestle** [comment]
Thanks for pointing this out!

@texnixe Maybe we should even merge this with the "page settings" page. What do you think?

**Comment by malvese** [comment]
I always get a bit confused by these settings and wonder what goes under `options: ` or not in the blueprint.
There are `template:` settings at two levels (at the first level in the blueprint, and under `options`), which doesn't help.
We actually have **Page** settings and **Panel** options.
Also I think it is not "fool-proof" obvious that "options" are only related to the controls at the top of the sidebar in the panel.

So, not sure merging the two would make it easier to understand.

**Comment by texnixe** [comment]
@lukasbestle, I just published it, hadn't seen your suggestion to merge the two sections. Maybe we should rather think about how to improve it before merging, I think this whole notion about page und subpage settings and all the rest is probably not really easy to understand or to find what you are looking for.
