### ISSUE TITLE
Urls error

### ISSUE THREAD

**Issue by jenstornell** [getkirby/getkirby.com#27]
The urls does not work for me:

https://nnnnext.getkirby.com/docs/guide/panel/blueprints/columns
https://nnnnext.getkirby.com/docs/guide/panel/blueprints/sections

But they show up here:

https://nnnnext.getkirby.com/docs/search?q=blueprint+definition

**Comment by texnixe** [comment]
Looks like the algolia index needs to be updated to reflect the restructuring
