### ISSUE TITLE
Broken Link in Anatomy of a blueprint file

### ISSUE THREAD

**Issue by mrflix** [getkirby/getkirby.com#270]
The link in the last paragraph on [this](https://getkirby.com/docs/panel/blueprints/anatomy-of-a-blueprint) page is broken:

![screen shot 2016-06-22 at 11 31 48](https://cloud.githubusercontent.com/assets/60777/16261753/0e8e92c0-386d-11e6-8f0e-511cd5d758ef.png)
Its a typo: `https://getkirby.com/**dics**/panel/blueprints/form-fields`. **dics** – freudian slip? 😏😄
Link to Source: https://github.com/getkirby/getkirby.com/blob/master/content/1-docs/5-panel/1-blueprints/1-anatomy-of-a-blueprint/docs.txt#L45

**Comment by texnixe** [comment]
Thanks for pointing this out. It is now corrected.

**Comment by mrflix** [comment]
Of course! I would have opened a pull request but pulling the recent git changes in took too long 😁
