### ISSUE TITLE
Registry details

### ISSUE THREAD

**Issue by texnixe** [getkirby/getkirby.com#272]
https://forum.getkirby.com/t/documentation-on-registry-details-missing/4620

**Comment by moritzz** [comment]
Hey @lukasbestle. Is there a registry for `field.yml` files too?

**Comment by texnixe** [comment]
Yes, that's been introduced in 2.3.1

```
// The blueprint file must exist at the given location
$kirby->set('blueprint', 'fields/title', __DIR__ . '/blueprints/fields/title.yml');
```
See changelog: https://getkirby.com/changelog/kirby-2-3-1

**Comment by lukasbestle** [comment]
I have also already added that to the registry developer guide with the release. :)

**Comment by moritzz** [comment]
Wow. Now that's cool! Thanks again and again and again. :)

**Comment by moritzz** [comment]
Hey @lukasbestle. I'm writing plugins and plugins these days and have a question; is there a mechanism to automatically load a plugin's CSS without the need to specifically add these files to the templates `<head>`?

**Comment by lukasbestle** [comment]
No, that's not possible, we don't want Kirby to become a WordPress clone that inserts CSS files everywhere. ;)
The best way is to register your CSS file with a route and then provide a helper function that outputs the respective CSS tag.
