### ISSUE TITLE
Docs search: "-" character doesn't return results

### ISSUE THREAD

**Issue by Thiousi** [getkirby/getkirby.com#277]
I was looking for the `$page->modified` method. I literally typed `"page->method"` in the search input at the top of the page and got 0 results.
I assume the "-" character is the problem?

**Comment by lukasbestle** [comment]
Algolia uses a syntax similar to other search engines. Searching for `"$page->modified"` including the quotes works for me.

**Comment by Thiousi** [comment]
Thanks for pointing that out. I didn't use the quotes in my search but only as a way to show the input I had typed. It doesn't work without the quotes but does with them.
