### ISSUE TITLE
List of dependencies

### ISSUE THREAD

**Issue by distantnative** [getkirby/getkirby.com#284]
*@jenstornell commented on Jul 4, 2018, 5:47 AM UTC:*

I think it can be useful to have a list of all external libraries and frameworks used in Kirby + Panel in the docs. I was missing it for Kirby 2 already, so I made an inofficial list here: [https://github.com/jenstornell/kirby-secrets/blob/master/docs/dependencies.md](https://github.com/jenstornell/kirby-secrets/blob/master/docs/dependencies.md)

That list does not contain much, as I needed to go through the code to find these dependencies.

**Here they are for Kirby 2:**

*   SimpleImage (for thumbs)
*   Spyc (for yaml operations)
*   SQLight
*   jQuery
*   jQuery sortable

### Why it's important

Let's say I as a plugin developer build a panel plugin. If I know that `sortable.js` is used, I may base my sort function on that instead of including my own. A real life example is my [Kirby Crop Top](https://github.com/jenstornell/kirby-crop-top) that is based on SimpleImage. If I could not find it in the core, my plugin could not have been done.

Another important aspect of it is transparency. You already very transparent.

### What should be in such a list

So every library or framework that leaves a trace in Kirby should be in such a list, I think. It would include things like `Vue`, `Gulp` (if there is a gulpfile), `Composer` (because of the composer file), `SQLight`, `Spyc` (if still used) etc etc.

*This issue was moved by [bastianallgeier](https://github.com/bastianallgeier) from [k-next/kirby#548](https://github.com/k-next/kirby/issues/548).*

**Comment by texnixe** [comment]
- update and related like increment/decrement
- create
- changeX
- replace
- delete

**Comment by distantnative** [comment]
@texnixe I don't understand your comment 😅

**Comment by texnixe** [comment]
Didn't belong here, sorry.

**Comment by distantnative** [comment]
I'll close this for now: most dependencies in the Panel aren't accessible to Plugin developers at this point anyway.

**Comment by jenstornell** [comment]
@distantnative Ok. I can just mention that all dependencies are not related to the Panel. For example, I used SimpleImage for some more advanced thumbnail cropping. Because it was built in and I knew about it, I did not need to include it again.
