### ISSUE TITLE
Add warning: methods that fail if user is not logged in

### ISSUE THREAD

**Issue by luxlogica** [getkirby/getkirby.com#285]
There seems to be some methods - like `$page->update()` that will fail unless the current user is logged in, and has adequate permissions for the action. I'm finding that this is actually a really useful feature, and saves us having to write a lot of security-check code. The docs, however, should perhaps add a warning that this is the case, and also show how to use `impersonate()` to override the checks and get the job done, when necessary.

Please note, that the documentation for `impersonate()` does not show how to impersonate the superuser - ie. `impersonate('kirby')` - which would also be very helpful. 

Lastly, it might be useful to have an explanation in the docs for the affected methods, as to WHY this is the case, as this approach may feel counterintuitive to a programmer new to Kirby - e.g.:

> 'The page will not be allowed to update, unless the current user is logged in and has adequate permission. This helps increase the security of your code, by blocking operations for users that are not authorised to do them. If you want to override the built-in check, use the impersonate() method'.

**Comment by texnixe** [comment]
@distantnative Shall we put this in the code blocks or in the docs?

**Comment by distantnative** [comment]
@texnixe There isn't really any fitting DocBlock tag (http://docs.phpdoc.org/references/phpdoc/tags/index.html) - so I'd say it should be a separate field in the docs. We would then need to see how to implement a visual cue resulting from that content field.

**Comment by distantnative** [comment]
@luxlogica we have tackled this with different steps:

1. We will introduce a little tag in the reference on methods that need permissions:
<img width="510" alt="Screenshot 2019-03-11 at 22 35 19" src="https://user-images.githubusercontent.com/3788865/54161179-ac950d80-4451-11e9-9af1-86cff6745e90.png">

2. We added a sectionon the guide: https://getkirby.com/docs/guide/templates/php-api#permissions

3. We will ad more connecting links e.g. from/to the `$kirby->impersonate()` reference entry
