### ISSUE TITLE
[Mobile] Header half way hidden on reference page

### ISSUE THREAD

**Issue by mullema** [getkirby/getkirby.com#286]
Sometimes the header is half way hidden when navigating in the reference. It is not possible to scroll up more.

Difficult to say when the full header is shown and when only half of it. Cannot reproduce consistently.

![img_20190203_080818](https://user-images.githubusercontent.com/46723734/52175184-7bfdec00-27a0-11e9-9aad-65e7723bedfd.png)

Chrome on Android
72.0.3626.86

**Comment by fabianmichael** [comment]
@mullema We pushed a huge update for improving mobile support a some weeks ago. I had the same issue with Mobile Safari and implemented a fix. Could you please check if the issue has also been resolved in Chrome for Android? Thanks for your help.

**Comment by mullema** [comment]
@fabianmichael Looking good on my devices
