### ISSUE TITLE
Docs: Permissions

### ISSUE THREAD

**Issue by jbeyerstedt** [getkirby/getkirby.com#288]
The first example at the permissions page does not work, if you simply copy-paste it:
```
<?php
return [
  'name'        => 'Editor',
  'default'     => false,
  'permissions' => [
    '*'                 => true,
    'panel.site.update' => false,
    'panel.user.*'      => false,
    'panel.user.update' => function() {
      if($this->user()->is($this->target()->user())) {                
        // users are allowed to edit their own information
        return true;
      } else {
        // other users can't be edited
        return false;
      }

    }
  ]
];
```
Because `panel.user.read` is set to false by the wildcard, you get the beautiful new debug page when selecting the record of the user having the specified role in the panel.

I know, it's only an example, but I think, it should work anyway.

By the way: Is it right, to open an issue here for these problems?

**Comment by lukasbestle** [comment]
Thanks for letting us know. This is the correct repo for documentation issues. There's another issue with this though, there shouldn't be a debug page for those kinds of errors, I have opened an issue at https://github.com/getkirby/panel/issues/924.

**Comment by bastianallgeier** [comment]
I fixed the logic behind this in the user and dashboard views and prepared an update for the docs.
