### ISSUE TITLE
kirby-2-4-0-beta-1 download link broken

### ISSUE THREAD

**Issue by chrisvasey** [getkirby/getkirby.com#295]
All mentions of kirby-2-4-0-beta link to a 404 page.

Link:
https://getkirby.com/changelog/kirby-2-4-0-beta-1

Mentioned here:
https://getkirby.com/blog/kosmos-4
https://forum.getkirby.com/t/kirby-2-4-0-beta-1-is-here/5344

**Comment by bastianallgeier** [comment]
Thanks for the heads-up! I just fixed it with a redirect.
