### ISSUE TITLE
Sourcecode links don't work with traits

### ISSUE THREAD

**Issue by rasteiner** [getkirby/getkirby.com#3]
At least I think this is the problem.

Example: 
http://[ccccensored]/docs/framework/cms/app/user

links to https://github.com/k-next/kirby/blob/develop/src/Cms/App.php#L109

I guess this is because the function lives in a trait. 
The line number is right, the filename is wrong:
https://github.com/k-next/kirby/blob/develop/src/Cms/AppUsers.php#L109

**Comment by wottpal** [comment]
Don't know if this is related but the source code link from ``Pages::sortBy()` (http://85.90.245.237/docs/framework/cms/pages/sort-by) is also wrong. It should link to `Toolkit\Collection` instead I guess.
