### ISSUE TITLE
Detail up the image blueprint section?

### ISSUE THREAD

**Issue by janstieler** [getkirby/getkirby.com#304]
Hi,

at the references it would be great if the image blueprint section get more details e.g. some complete image blueprint.

I think as main concern is to explain more detailed the naming  of the blueprint as https://getkirby.com/docs/reference/panel/blueprints/file#default-file-blueprint .
I come up to this because I have a problem to create blueprints for two image sections in my template blueprint. But also my default.yml will also not work.

Width a example default.yml it would be easier to understand i think.

EDIT: now I found that: https://getkirby.com/docs/reference/panel/samples/file
It should be linked to https://getkirby.com/docs/reference/panel/blueprints/file.
But also in this sample, which helps me further, I don't understand how I can say which image which blueprint use if I have multiple images in one template and everyone should use its own blueprint.

Kindly,
Jan

**Comment by texnixe** [comment]
> But also in this sample, which helps me further, I don't understand how I can say which image which blueprint use if I have multiple images in one template and everyone should use its own blueprint.

I think we should discuss such things in the forum, because it's not the file blueprint that determines what template a file uses but the files section where you define that with the template option.

**Comment by texnixe** [comment]
via https://github.com/getkirby/getkirby.com/pull/308
