### ISSUE TITLE
Bad autocomplete links from http://getkirby.com/docs/

### ISSUE THREAD

**Issue by fvsch** [getkirby/getkirby.com#31]
If one happens to be on the http://getkirby.com/docs/ URL, which does show the same page as http://getkirby.com/docs, the links in the autocomplete results will be broken because they’re relative, and resolve to e.g. http://getkirby.com/docs/docs/cheatsheet/field-methods/kirbytext (404).

I’ve had this problem several times, and I’m not sure if I ended up on the `/docs/` (trailing slash) URL only by editing the URL myself, or if some parts of the website may also link to `/docs/` (trailing slash) instead of `/docs`.

**Comment by maxfenton** [comment]
I ran into this as well. Consider enforcing trailing slashes in Kirby, overall?

**Comment by vyder** [comment]
Can you provide an example search page where this is broken? I can't seem to reproduce it.

**Comment by fvsch** [comment]
Go to http://getkirby.com/docs/ (*with* trailing slash), type "page" in the search box, click on first result.
You should end up on http://getkirby.com/docs/docs/cheatsheet/field-methods/pages (404).

Tested in Firefox and Chrome.

**Comment by vyder** [comment]
So when you search for "page" on http://getkirby.com/docs/, I get this url: "http://getkirby.com/docs/?q=page". And the first url on the the results page for me is "Page Settings" which links to "http://getkirby.com/docs/panel/blueprints/page-settings".

I tried out a links from other sections too like Cheat Sheet, Panel, Solutions, etc and they link accurately for me. Strange.

**Comment by fvsch** [comment]
The problem is with the autocomplete results, not the GET query when you submit the form.
Sorry, that wasn't clear. I updated the issue accordingly.

**Comment by vyder** [comment]
Cool, I created a PR to fix the issue in the simplest/best way I can think of.

**Comment by bastianallgeier** [comment]
This is no longer valid with the Algolia Search
