### ISSUE TITLE
Search: split reference hits from the rest of the content (cookbook/docs/...)

### ISSUE THREAD

**Issue by bvdputte** [getkirby/getkirby.com#311]
Imho the search returns hits from the reference too soon at the expense of the content in the cookbook / docs / other pages which contain more explained info. To me, I often find the desired search results to be "buried" too deep. I can imagine for newcomers it might be a bit overwhelming too.

I believe it could be better to promote the other content first when searched. When no hits returned, or little, then it could be complemented with hits from the reference.

Of course, this behaviour shouldn't be used inside the reference. Actually, quite the opposite logic should be applied there imo.

On the search result page, you could work with "tabs" or something to clearly distinguish the 2 "categories"?

What do you think?

**Comment by distantnative** [comment]
Closing this in favor of https://github.com/getkirby/getkirby.com/issues/623
