### ISSUE TITLE
Language variables docs -> Missing PHP end-tag in associative array example

### ISSUE THREAD

**Issue by Mattrushka** [getkirby/getkirby.com#312]
The php end-tag `?>` is missing in the associative array example. Should look like this:
```
<?php

l::set(array(
    'submit' => 'Submit',
    'cancel' => 'Cancel',
    'next' => 'next',
    'previous' => 'previous',
));

?>
```

**Comment by texnixe** [comment]
No, the closing tag is not necessary and according to PSR 2 must be omitted from files that only contain PHP (see http://www.php-fig.org/psr/psr-2/).

**Comment by Mattrushka** [comment]
agree, but shouldn't we then remove the PHP end-tags in the 2 prior examples, because they contain PHP only, too?

**Comment by texnixe** [comment]
Agreed and done. Could you please provide a link to the files you are referring to in the future? Thanks a lot 😄.

**Comment by Mattrushka** [comment]
Thanks! And sorry for the missing link, will provide it next time :)
