### ISSUE TITLE
File filtering docs

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/getkirby.com#315]
It would be helpful to link to the [filter compendium](https://getkirby.com/docs/cookbook/search/filtering) on https://getkirby.com/docs/reference/objects/files/filter-by. 

Generally, it would be preferable to have one place (like the compendium) showcasing all filter options with other parts of the references linking prominently without providing partial documentation. Currently, the `filterBy` docs make you think the given filter option list is complete (which is not correct).

**Comment by nilshoerrmann** [comment]
There also seem to be some filter option missing from the compendium, see https://forum.getkirby.com/t/filter-out-files-without-template/12839/6.

**Comment by texnixe** [comment]
I agree that linking to a cookbook example makes sense when there is one.

I do not agree with putting the docs into the cookbook. That should remain in the reference. The two examples you mention are in fact covered by the docs, as it says that `$args` accepts a `mixed` value, which includes a string or `true` or `false` or an array in combination with the filters. But we could be more explicit here, as in general with the options.

**Comment by nilshoerrmann** [comment]
Let me point out three things that are important in my eyes (this trapped me multiple times in the current docs):

- If a feature is described in the reference, it should be complete or link to a document with the full option list.
- If feature descriptions are incomplete, they should look like being complete. Currently, given list look like "this is it".
- Explainations should be verbose. While the two examples mentioned above may have been covered by the docs already, this was only obvious for an advanced user. This is really hard for beginners.

In my eyes the docs could be more repetitive. Sometimes, like with filtering, I have to read the docs of other filter functions (jumping between files, pages and such) to grasp the full range of possibilities.

That said, I know documentation is hard and you've done a great job already for K3 already. So this is not meant as an offence :)
