### ISSUE TITLE
Navigation dropdown not opening in Browser Edge

### ISSUE THREAD

**Issue by mullema** [getkirby/getkirby.com#323]
The dropdown Docs [Guide, Cookbook..] does not open in Edge.

Browser Microsoft Edge 40.15063.674.0

**Comment by distantnative** [comment]
@fabianmichael something you can have a look at?

**Comment by fabianmichael** [comment]
@mullema Does this issue still persist? We changed the implementation of the dropdowns in a recent update, that was mostly about improving mobile support.

**Comment by mullema** [comment]
@fabianmichael the drop down does not open in Edge 42.17134.1.0
