### ISSUE TITLE
Better CSRF guide

### ISSUE THREAD

**Issue by sebsel** [getkirby/getkirby.com#340]
I was fiddling around with the CSRF helper, and I'm glad I tested it, because the code I used did not work.
According to <https://getkirby.com/docs/toolkit/api/helpers/csrf>, we should do:

```html
<input type="hidden" name="csrf" value="<?php echo csrf() ?>">
```
And
```php
$token = get('csrf');
if(csrf($token) === true) {
  // Success
} else {
  // Token doesn't match
}
```

But I was trying to get it shorter and used:

```php
  if(!csrf(get('csrf'))) return response::error('CSRF token does not match', 403);
``` 

But, since `csrf(null)` returns a new token, the `if` will not trigger when `$_POST['csrf']` is not set, so the script goes through.

So, a shorter but working one is this:
```php
if(csrf(get('csrf')) !== true) return response::error('CSRF token does not match', 403);
```

Maybe:
1. add a warning for this to this page in the docs
2. a cookbook recipe with more in dept about CSRF might be nice too? :)
3. shouldn't this be avoided in the code as well, so it's harder to make this mistake? don't know.

**Comment by sebsel** [comment]
Just realised:
```php
if(csrf(get('csrf')) != true) return response::error('CSRF token does not match', 403);
```
... would also not work. You really have to work with `===` and `!==`, which can be forgotten if a beginner types the example instead of copy-paste. That should be included into the warning :)

**Comment by lukasbestle** [comment]
Thanks for letting us know, that is indeed a bug in Kirby. We will fix it directly in the code: https://github.com/getkirby/toolkit/issues/240
