### ISSUE TITLE
Caching - option ignore confusion

### ISSUE THREAD

**Issue by mrflix** [getkirby/getkirby.com#345]
Hey,

in the [caching guide](https://getkirby.com/docs/guide/cache) the example `ignore` function doesn't fit the option description.

#### `ignore` function:

```php
return [
  'cache' => [
      'pages' => [
          'active' => true,
          'ignore' => function ($page) {
            return $page->title()->value() !== 'Do not cache me';
          }
      ]
  ]
];
```

#### `ignore` description

Option | Value
-- | --
ignore | **A function that returns a list of pages to ignore.**

My guess is that the description should be something along the lines of: "A function that returns true for pages that should be ignored and false for pages that should be cached."

**Comment by texnixe** [comment]
Thanks a lot for your suggestion.
https://github.com/getkirby/getkirby.com/commit/1343157b739ac1450cb34234d88a0f5c47690b03
