### ISSUE TITLE
Incorrect link to $field->key() source code

### ISSUE THREAD

**Issue by simlawr** [getkirby/getkirby.com#346]
The source code link on the [$field->key() reference page](https://getkirby.com/docs/reference/templates/field-methods/key) points to the wrong line.

**Comment by texnixe** [comment]
The method doesn't even exist in that file.

**Comment by simlawr** [comment]
Indeed, it points to the wrong line, in the wrong file.

**Comment by texnixe** [comment]
@bastianallgeier This is a general problem with the `githubSource()` page method that doesn't cover all cases. In this example, the field methods distributed between the `config/methods.php` file and `kirby/src/Cms/Field.php`. Probably doesn't just affect field methods, either.

**Comment by simlawr** [comment]
The problem is more widespread than I initially thought. I’ve found many more source code links that don’t point the correct location. Many are only a few lines out but are some way off.
