### ISSUE TITLE
How to access structure fields etc. in query language

### ISSUE THREAD

**Issue by texnixe** [getkirby/getkirby.com#35]

**Comment by philipmarnef** [comment]
Here's a suggestion.

In Cheat Sheet > Fields > Select > Options from other fields

Of course you get the same flexibility with those array values, to modify the result text and stored value. Each item in the array will automatically be converted into an object with a `key` and `value` property. Those properties are regular Kirby content fields and you can use all field methods to work with them further. Items in the array need to be referenced as `arrayItem`. **If you query a structure field instead, reference the items as `structureItem`.**
