### ISSUE TITLE
Missing home content folder results in "Not found"

### ISSUE THREAD

**Issue by BaerMitUmlaut** [getkirby/getkirby.com#352]
If `/content/home` is missing, Kirby only displays "Not found" without any kind of information what was actually not found, even with `debug` set to `true`. I encountered this problem when migrating a Kirby 2 project.

Additionally, neither the migration guide nor the content docs mention that this folder is essential for Kirby to function.

**Comment by BaerMitUmlaut** [comment]
After a quick search, this seems to be the only usage of an empty `NotFoundException`:
https://github.com/getkirby/getkirby.com/blob/c350e206b8fd8806f208e1a760f1dfce35b61fd2/kirby/src/Cms/App.php#L518

**Comment by BaerMitUmlaut** [comment]
Oops, I think this is the wrong repo for this. Moving to kirby repo.

**Comment by texnixe** [comment]
@BaerMitUmlaut I'm just surprised you had Kirby 2 working with the missing home folder; like in Kirby 2, you can set the home folder to another folder in your config file in Kirby 3. But either home or the folder you set to act like home must be present.

**Comment by BaerMitUmlaut** [comment]
I'm not quite sure if I did anything special for that, and with the Kirby 2 docs now gone I can't tell you either. Either way, I reopened the issue in the main kirby repo, see getkirby/kirby#1521.

**Comment by texnixe** [comment]
The Kirby 2 docs are not gone: https://k2.getkirby.com
