### ISSUE TITLE
Buttons in field type textarea does not work after updating to v2.5.7

### ISSUE THREAD

**Issue by kaloja** [getkirby/getkirby.com#354]
The link and email buttons in type textarea does not work after updating to Kirby v2.5.7. When trying to save the input fields nothing happens. I get no errors in the console but it feels like a JS-error. I did a test on a site with v2.5.5, that worked fine.

**Comment by lukasbestle** [comment]
This is a duplicate of https://github.com/getkirby/panel/issues/1121. We will take a look at it soon.
