### ISSUE TITLE
Bug: Kirby Shirt page

### ISSUE THREAD

**Issue by marcobiedermann** [getkirby/getkirby.com#363]
After clicking on "Preorder Now" on https://getkirby.com/shirt, I get the following error message:

```
Hmmm....something is not right.
Profile not found.
```

https://getkirby.wufoo.com/forms/kirby-shirt-preorder/

**Comment by texnixe** [comment]
@bastianallgeier  What do we do with this page, redirect to error?

**Comment by bastianallgeier** [comment]
Yikes, yes, we should remove it!

**Comment by marcobiedermann** [comment]
So there won't be any shirts any longer? Or do you moved it to another location and therefore have to update to link?

**Comment by texnixe** [comment]
No more shirts, the presale was two years ago. But who knows what the future holds? I mean, with Kirby 3 upcoming and if enough people crave to have a shirt… 🙂

**Comment by jenstornell** [comment]
@marcobiedermann If you really want one, it's possible to use services like https://www.spreadshirt.com/create-your-own, but maybe you need permission to use the logo for that?

**Comment by bastianallgeier** [comment]
I would really love to print a new set of shirts. It wasn't really that easy to ship them world-wide, but enough years have passed to be over the pain :D There's only one son old enough to be helpful though. Maybe we should start another list and just see how big the response is in general and decide then if it is worth it.

**Comment by texnixe** [comment]
I'd love a Kirby sports shirt…
