### ISSUE TITLE
Docs: $pages->has documentation wrong

### ISSUE THREAD

**Issue by rasteiner** [getkirby/getkirby.com#365]
https://getkirby.com/docs/cheatsheet/pages/has refers to the the string parameter as `uid()`. However, in Kirby, the `id()` is used as key for the collection.
see: https://github.com/getkirby/kirby/blob/master/core/pages.php#L49

The difference being that "id" string contains a whole path to the page, while `uid` contains only the last part:

E.g: `"news/an-article/a-subpage"` vs. `"a-subpage"`.

This means that:

```php
<?php if($page->children()->has('some-page')): ?>
``` 

Will never work, it should be something like: 

```php
<?php if($page->children()->has($page->id() . '/some-page')): ?>
```

**Comment by texnixe** [comment]
Thanks for reporting 🙂.
