### ISSUE TITLE
Image KirbyTag reference mentions non existent attributes

### ISSUE THREAD

**Issue by HashandSalt** [getkirby/getkirby.com#368]
The kirbytag page for image tag in the reference part of the docs mentions a size attribute the tag does not have. The source code link at the bottom also links to the wrong line in the source. Should be line 80, not 205.

https://getkirby.com/docs/reference/text/kirbytags/image

**Comment by texnixe** [comment]
Haha, yeah, that happens if you overwrite an existing tag and then let the Reflection class do the work for you.
