### ISSUE TITLE
Document Html::a $attr

### ISSUE THREAD

**Issue by distantnative** [getkirby/getkirby.com#372]
Which attributes are there?
https://getkirby.com/docs/reference/tools/html/a

**Comment by texnixe** [comment]
Any that are allowed for an a tag, I'd say.

**Comment by distantnative** [comment]
But we should answer that question in the docs, I'd say.

**Comment by texnixe** [comment]
rel, target, hreflang, type, download, ping
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a
