### ISSUE TITLE
[Docs] Devkit without Public Folder Instructions

### ISSUE THREAD

**Issue by carstengrimm** [getkirby/getkirby.com#38]
as mentioned in Slack.

if anyone were to use the devkit (composer) the configuration would always lead to having a public folder as a requirement. Many hosts do not provide the functionality for having a public folder to protect content so we would have to change some things get rid the public folder and rearrange some folders and files to make it working. But still being able to update our devkit / current nighties and composer.

Index.php and htaccess has to be moved from the public to root folder.
Index.php has to be changed to
```
<?php
require_once __DIR__ . '/vendor/autoload.php';

$kirby = new Kirby([
    'roots' => [
        'index'    => __DIR__,
        'base'     => $base    = __DIR__,
        'content'  => $base . '/content',
        'site'     => $base . '/site',
        'storage'  => $storage = $base . '/storage',
        'accounts' => $storage . '/accounts',
        'cache'    => $storage . '/cache',
        'sessions' => $storage . '/sessions',
    ]
]);

echo $kirby->render();
```
since it's kinda searching for a storage folder, as well as setting it's base to one parent directory we need to change it accordingly as above.

We need to move and create inside root
- assets/
- assets/js
- assets/css

as well as
- media
- storage (plus subfolders)

if path's are not set properly inside the index file, the panel e.g. will still prompt to "install" an account, however it won't show any page or information but stay blank.

**Comment by texnixe** [comment]
@bastianallgeier What are the plans for devkit?

**Comment by texnixe** [comment]
Can we close this since the devkit is gone?
