### ISSUE TITLE
Kirby 2 archive: install commands outdated 

### ISSUE THREAD

**Issue by SebastianEberlein** [getkirby/getkirby.com#396]
I needed to download the latest Kirby 2 version, but the download link in the [archive](https://getkirby.com/docs/archive/v2) (Installation & Updates › Download & Requirement) does not work.

But this is just a `Mixed Content` issue, because the link url is not https.

<img width="1153" alt="Screenshot" src="https://user-images.githubusercontent.com/15672385/54111066-4a052880-43e3-11e9-8ec9-0676af86a1aa.png">

**Comment by distantnative** [comment]
But we should definitely change the git clone command

**Comment by texnixe** [comment]
The download links downloads Kirby 3 (when you change it to https). We should either remove the download link or link to the new master zip download on GitHub,

**Comment by texnixe** [comment]
I created a PR here: https://github.com/getkirby-v2/getkirby.com/pull/405
