### ISSUE TITLE
Show when docs and guide pages got updated the last time

### ISSUE THREAD

**Issue by REHvision** [getkirby/getkirby.com#398]
In many cases, I find it very useful to know the state of information on a docs guide or reference page (i.e. seeing when it has been updated the last time).

This information is available in the public GitHub-repo anyways but only inconveniently retrievable.
I suggest a small and unobtrusive timestamp in the footer:
![Bildschirmfoto von »2019-03-11 16-41-16«](https://user-images.githubusercontent.com/2584674/54137077-4098b200-441d-11e9-8695-b29e167b1242.png)

That would be awesome! :+1:

**Comment by distantnative** [comment]
Thinking out loud here:
How would we do this for reference pages where parts of it are automatically generated from the source code of Kirby?

**Comment by REHvision** [comment]
Thanks @distantnative and also just thinking out loud:

Maybe it's not very important for reference pages because of the auto-generation from source you mention. They always reflect the current state.

But assuming you trigger the generation of the reference pages once for every release and not on the fly, the generation timestamp could be used. Maybe with a little note that they got generated automatically?

`updated 5 days ago (auto-generated from source)`

**Comment by distantnative** [comment]
Currently, there is no one-time generation. They are generated on-the-fly. But I/we will keep thinking about this idea.

**Comment by REHvision** [comment]
In this case, the proposed `updated` String would only apply for guides and cookbook recipes
and the references could always show a simple `auto-generated from source` String instead.

I would perceive this info as positive since it shows that the documentation is cutting-edge :fire:

But anyways, it's only a tiny feature-idea I wanted to propose here so it doesn't get lost (not important but nice to have).

Thanks a lot for thinking about it :smile::+1:

**Comment by distantnative** [comment]
@texnixe would be interested in hearing your take on this.

At the moment I tend to rather not favoring this: Too much of the guide and reference is created from source code on the fly or through common snippets. For all these it would be very hard to get a modified date. Which would then leave us with two options: Only have very few pages with this info included (if it's not a majority, I think it's not beneficial). Or have it shown an often much older timestamp, which would be even worse.

**Comment by texnixe** [comment]
To be honest, I don't really see a great benefit for users from adding such a date at all. Our docs are continually updated and whether or not a page has been updated three days ago or a month ago usually doesn't mean much regarding it up-to-date status.

**Comment by distantnative** [comment]
Agreed. Sorry @REHvision but I think we won’t pursue this one for the stated reasons.

**Comment by REHvision** [comment]
Alright and I agree if that's the case, thanks for evaluating @distantnative and @texnixe :grin:
