### ISSUE TITLE
Document: Custom API collections + models

### ISSUE THREAD

**Issue by distantnative** [getkirby/getkirby.com#407]
Write documentation for

https://getkirby.com/docs/guide/api/data#models
https://getkirby.com/docs/guide/api/data#collections

https://getkirby.com/docs/reference/plugins/extensions/api#custom-models
https://getkirby.com/docs/reference/plugins/extensions/api#custom-collections

**Comment by texnixe** [comment]
Details needed.

**Comment by distantnative** [comment]
To be honest, I am not 100% sure myself yet how they work - that's why I haven't written anything. But I know that you are supposed to be able to create custom models or collections for the API

**Comment by distantnative** [comment]
Those are rather on the way out, so I'd consider them as internal now.
