### ISSUE TITLE
Better document immutable character of objects

### ISSUE THREAD

**Issue by distantnative** [getkirby/getkirby.com#425]

**Comment by distantnative** [comment]
@texnixe was this fixed, I recall a discussion last week (e.g. with `$page = $page->update()`)?

**Comment by texnixe** [comment]
There was a discussion and I changed the docs example, but maybe we still need to add something more general somewhere. But don't know where atm.

**Comment by distantnative** [comment]
Guess we could put a warning box on key pages such as
https://getkirby.com/docs/reference/objects/page/update
