### ISSUE TITLE
Document missing toolkit classes

### ISSUE THREAD

**Issue by texnixe** [getkirby/getkirby.com#447]
e.g. collection class

https://forum.getkirby.com/t/where-are-the-docs-for-collection-filter/13570/2

**Comment by distantnative** [comment]
Would be pretty easy to just add the Toolkit package to https://github.com/getkirby/getkirby.com/blob/master/content/1_docs/3_reference/%40/packages.txt

Then the basic ones would be automatically created. Question is if we want to add manual docs to some as well. and do we want to link to some specifically.
