### ISSUE TITLE
home-panel thumb images way oversized

### ISSUE THREAD

**Issue by S1SYPHOS** [getkirby/getkirby.com#451]
Panel container thumb images are resized to 1400px (see [here](https://github.com/getkirby/getkirby.com/blob/master/site/templates/home.php#L90)) - and I don't see how that's necessary, since blur is applied via css `filter: blur(2px)`

Resizing them to 163px or so would be appropriate - saving about 98% of file size.

I smell that I'm mistaken somehow .. well, teach me, master!

**Comment by bastianallgeier** [comment]
It's a poor man's loader for the bigger versions. TBH I always planned to replace that with a proper js lazy loader, but then other stuff has always been more important.

**Comment by fabianmichael** [comment]
@bastianallgeier Should I take care of this? I would go through the whole page, I think we can lazyload at many more places.

**Comment by S1SYPHOS** [comment]
I thought about the loading technique, but as you said, proper lazyloading should be implemented if you have the resources!
