### ISSUE TITLE
Smartypants option doesn't accept boolean, needs array of options.

### ISSUE THREAD

**Issue by texnixe** [getkirby/getkirby.com#496]
https://getkirby.com/docs/guide/content/text-formatting#smartypants

**Comment by texnixe** [comment]
Check if fixing this is still necessary once https://github.com/getkirby/kirby/issues/1686 is fixed.

**Comment by distantnative** [comment]
If https://github.com/getkirby/kirby/pull/1769 gets merged, the current docs should be valid.

**Comment by distantnative** [comment]
✅
