### ISSUE TITLE
Document how to create a custom cache driver

### ISSUE THREAD

**Issue by texnixe** [getkirby/getkirby.com#503]
```
<?php

class CustomCache extends Kirby\Cache\FileCache
{
    public function flush(): bool
    {
        // your custom code
        // ...

        return parent::flush();
    }
}

Kirby::plugin('yourname/custom-cache', [
    'cacheTypes' => [
        'custom' => CustomCache::class
    ]
]);
```

**Comment by distantnative** [comment]
Guess that should go into the config option docs...

But then we should mention here: https://getkirby.com/docs/reference/plugins/extensions
that plugins can also extend all config options.

**Comment by lukasbestle** [comment]
Hm, why the config option docs? I'd say it's something for the plugin extension reference you linked to.

**Comment by distantnative** [comment]
Cause we have all the existing docs for config options that also can be used in plugins in the options docs. Would be just consistent (e.g. api).

**Comment by distantnative** [comment]
On the other hand, we have both entries for routes... hmmm

**Comment by lukasbestle** [comment]
But this isn’t about config options, is it? You can’t register a cache driver via a config option.

**Comment by texnixe** [comment]
No, this has to go into the extension docs. with a note in the config that you can also choose a custom cache driver in the options and a link back to the docs.

**Comment by distantnative** [comment]
👍 my knot in the brain :P
