### ISSUE TITLE
Reference: Document thrown exceptions

### ISSUE THREAD

**Issue by omz13** [getkirby/getkirby.com#504]
In 3.1.2, when calling `$user->validatePassword ( $password )`, if the password does not match (validate), an error is thrown. According to the  [documentation](https://getkirby.com/docs/reference/objects/user/validate-password), it should return `false`. Looking [at the code](https://github.com/getkirby/kirby/tree/3.1.2/src/Cms/User.php#L787), however, it is clear that things will be thrown instead of `false` being returned.

Could the behavior be updated to reflect the documentation or the documentation be updated to reflect the actual behavior.

**Comment by distantnative** [comment]
The documentation is not wrong, throwing an exception is not considered a return type... however, I totally get your point that it should be mentioned somehow.

I would argue for implementing
http://docs.phpdoc.org/references/phpdoc/tags/throws.html
and include that information automatically in the documentation.

So we would leave the return type as it is, but also mention if an exception could be thrown by the method and in which cases.

**Comment by distantnative** [comment]
I have implemented that exceptions will be automatically documented on the website, if they are documented in-code via `@throws`. 3.1.4 will bring the first ones for the example you mentioned. We will add more in-code documentation over time.
