### ISSUE TITLE
View type (basic/advanced) not respected when opening a method

### ISSUE THREAD

**Issue by texnixe** [getkirby/getkirby.com#518]
When opening the view of an advanced method, the method does not show up in the navigation bar on the left nor do any other of the advanced methods.

<img width="1267" alt="Bildschirmfoto 2019-04-19 um 12 26 01" src="https://user-images.githubusercontent.com/5312492/56420638-17323800-629f-11e9-9040-87df769d9f89.png">

**Comment by distantnative** [comment]
✅
