### ISSUE TITLE
License of this repository

### ISSUE THREAD

**Issue by bezin** [getkirby/getkirby.com#526]
Hi folks, 

I wonder what is the license of this repository? I like skimming through the source code to get inspiration on how to solve some issues, but there is also some code that is actually really handy, e.g. the page meta plugin. What is your position on using that for own sites?

Cheers

**Comment by distantnative** [comment]
As answered by @bastianallgeier on Slack:
> I’d say it’s the “Do whatever you want” license :slightly_smiling_face:
