### ISSUE TITLE
Missing docs for Structure object

### ISSUE THREAD

**Issue by yandodov** [getkirby/getkirby.com#529]
There are currently no docs for the Structure object. For example, I noticed that I can do `$page->myfield()->toStructure()->find()`, but there are no docs for that method.

**Comment by bastianallgeier** [comment]
Thank you for your issues. Please send all docs issues to the getkirby.com repo.

**Comment by texnixe** [comment]
All classes are now available in the "[Advanced](https://getkirby.com/docs/reference/@)" section
