### ISSUE TITLE
Better field plugin documentation

### ISSUE THREAD

**Issue by yandodov** [getkirby/getkirby.com#530]
I'm trying to create a new plugin. [This documentation](https://getkirby.com/docs/reference/plugins/extensions/fields) did a good job of providing a minimal example to get me started. But now I need a more specific information that I can't find. For example - how do I trigger Kirby's Save/Reject changes dialog? How to revert a value when the user clicks Revert? How do I actually provide a value to Kirby and make it save the value?

I found out that to trigger the Save dialog, you need to `$emit` an `input` event. To respond to the Revert action, I guess I need to deal with `props`. To figure all this out, I need to look at the source code of other field plugins and reverse-engineer them, which is not very easy. I have a pretty decent experience in Vue and I know what I'm looking for. Newcomers would probably be lost.

The current documentation is great, I just think it's incomplete. After the minimal example is shown, you should put a more concrete example that shows how to create an actual field - one that allows the user put a value and save it (or revert the changes).

**Edit:** There's also no documentation for the `methods` and `api` properties:

```php
Kirby::plugin('me/plugin', [
    'fields' => [
        'myfield' => [
            'methods' => ...
            'api' => ...
        ]
    ]
]);
```

I know they exist because I looked at the source code of another plugin. I wonder how other people figure this stuff out.

**Comment by texnixe** [comment]
I created a [custom field cookbook recipe](https://getkirby.com/docs/cookbook/extensions/first-panel-field), that I think covers most parts of this. We probably need some more documentation on events, but that's a different issue.

**Comment by igregson** [comment]
> How to revert a value when the user clicks Revert?

> We probably need some more documentation on events, but that's a different issue.

I ended up here searching for how to revert a value when the user clicks Revert. Had hopped that the custom field cookbook recipe would address it but it doesn't. Will continue searching (and update here if I figure it out). In the meantime, anyone who knows this feel free to share here.

**Comment by distantnative** [comment]
@igregson most common case where this fails: In your Vue component, don't just assign the `value` prop in your `data()` function, but also watch for changes of `value` and update your component data accordingly. When "revert" is happening, the `value` prop changes - so you need to react to it.

**Comment by igregson** [comment]
Thanks @distantnative! That's exactly what I was missing (I wasn't watching for changes of `value`).
