### ISSUE TITLE
API not documented in Extensions

### ISSUE THREAD

**Issue by yandodov** [getkirby/getkirby.com#531]
I want to create a new API route from my plugin. I happen to know that it's done like this:

```php
Kirby::plugin('me/plugin', [
  'api' => [
    'routes' => [
      [
        'pattern' => '...'
      ]
    ]
  ]
]);
```

But I can't find any documentation about it in the [extensions reference](https://getkirby.com/docs/reference/plugins/extensions). There's an entry for [routes](https://getkirby.com/docs/reference/plugins/extensions/routes), but not for API routes.

**Edit:** Oops, sorry, didn't know I had to post docs issues in the getkirby.com repo.

**Comment by distantnative** [comment]
✅ will be after an upcoming merge
