### ISSUE TITLE
Fix docs table layout on mobile

### ISSUE THREAD

**Issue by manuelmoreale** [getkirby/getkirby.com#541]
Layout of the tables on mobile is a bit buggy and need some love :)

![IMG_6633](https://user-images.githubusercontent.com/1738077/57303224-29a0d400-70dd-11e9-83df-f78e3dd5115e.PNG)

**Comment by texnixe** [comment]
It's not only on mobile, on desktop code blocks also don't wrap, resulting in text from different columns overlapping.
<img width="590" alt="Bildschirmfoto 2019-05-14 um 00 56 40" src="https://user-images.githubusercontent.com/5312492/57659626-3ba1db80-75e3-11e9-9aba-25cc18236b69.png">

**Comment by fabianmichael** [comment]
@texnixe What page is that screenshort from (can you share the URL, please)?

**Comment by texnixe** [comment]
I'm closing this, looks as if has been fixed.
