### ISSUE TITLE
Blueprint Fields Docs Could Have an Image Map

### ISSUE THREAD

**Issue by neildaniels** [getkirby/getkirby.com#564]
The overview image at https://getkirby.com/docs/reference/panel/fields could have an image map that lets you links each part of the image to the corresponding field documentation.

For example, clicking on the "checkboxes" field would take you to that page.

![panel-form-fields](https://user-images.githubusercontent.com/417182/58206903-7b795a80-7c96-11e9-95af-18192c9feff9.png)

**Comment by texnixe** [comment]
I'm closing this to clean up a bit.
