### ISSUE TITLE
Referencing aliases

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/getkirby.com#580]
It would be nice to have links between functions [and their aliases](https://github.com/getkirby/kirby/blob/master/config/aliases.php). E. g. the content class `Config` can also be accessed using `config` which can be quite confusing if you don't know that one is the alias of the other.

**Comment by distantnative** [comment]
- [x] In the core: refactor https://github.com/getkirby/kirby/blob/master/config/aliases.php to separate array from actual `spl_autoload_register`
- [x] For the website: use the separated array to automatically create a table somewhere, listing all aliases and the corresponding classes (with reference lookup)
- [x] Use it to include on class references something like `Alias: ...`

**Comment by distantnative** [comment]
Work on this after 3.2.4 has been released
