### ISSUE TITLE
Collection cheatsheet is hard to reach?

### ISSUE THREAD

**Issue by adamkiss** [getkirby/getkirby.com#583]
Trying to reference methods/functions available on `Collection` (in my case via `Db` class), I can't easily get to the [Reference/Advanced/$collection](https://getkirby.com/docs/reference/@/cms/collection) page: `Database` doesn't reference/link its return type, search doesn't find the page with search terms `$collection` or `Collection`.

I don't know everywhere it's used, but given that many classes like `Pages` extend it, I'd say it should have a bit more prominent place in docs or cheatsheet.

Thank you!

**Comment by adamkiss** [comment]
Additionally, looking at #131 it seems that there were more prominent pages in Docs/Guide, but they 404 now, so perhaps this already exists, but it was deleted or hidden.

**Comment by distantnative** [comment]
@adamkiss with the release of 3.2 all return and parameter types will be link much more riably to the correct reference pages

**Comment by adamkiss** [comment]
@distantnative Cool thanks, so you (as a team) are on it, right?

I just wanted to add that [Guide/Templates/Collections](https://getkirby.com/docs/guide/templates/collections) should also probably link the reference.

**Comment by texnixe** [comment]
Think this should now be fixed and I added links from collections to the different collection types.
