### ISSUE TITLE
filterBy() Paramaters issue?

### ISSUE THREAD

**Issue by PaulMorel** [getkirby/getkirby.com#598]
Noticed in the [`$pages->filterBy()` page](https://getkirby.com/docs/reference/objects/pages/filter-by#parameters), in the parameter section. The type for the second arument `$args` is a URL to another page within the reference docs.

I'm assuming this is no intended,

## Screenshot
![image](https://user-images.githubusercontent.com/1200261/59984428-02a05200-95f8-11e9-8634-8a063b8a755e.png)

**Comment by texnixe** [comment]
Yes, that is nonsense. We have that in multiple locations. Something is  going crazy there with  the automatic doc generation.

**Comment by bastianallgeier** [comment]
That was a hickup while we were working on the new return type design. Should be working again now.
