### ISSUE TITLE
Set up getkirby.test and panel

### ISSUE THREAD

**Issue by yandodov** [getkirby/getkirby.com#601]
I wrote an article about plugin workflows and @bastianallgeier told me I can put it in the Cookbook and can create a PR in this repo so @texnixe can check it.

The information in the readme was useful, but not enough. I can see the whole site at `http://localhost/getkirby.com/www/` but:

- How do I set up the `http://getkirby.test` domain for local purposes? I guess some Apache conf.
- How do I set up the panel? If I go to `/www/panel`, I get the 404 page. Are you guys using the panel?

**Edit:** I managed to set up `getkirby.test` locally. You could still tell me how you've set it up for yourselves, though. I might have done it wrong.

Now, if I open `http://getkirby.test/panel`, I get redirected to `http://getkirby.test/docs/guide`. 🤔

**Comment by distantnative** [comment]
We aren’t using the panel.

And I set it up with valet plus, linking to the www folder.

**Comment by yandodov** [comment]
I don't have Valet. I managed to set it up with some basic config for Apache, though. I summarized it [here](https://medium.com/oblik-studio/windows-xampp-vhost-and-custom-domain-setup-bd3e2fa788ab).
