### ISSUE TITLE
RSS feed for Kosmos issues

### ISSUE THREAD

**Issue by Stolzenhain** [getkirby/getkirby.com#605]
The old page hat a very convenient way of receiving updates via RSS on

https://getkirby.com/feed

but has since been deactivated – assuming there is no new feed someplace I didn't notice: Would it be possible to reinstate that one? Would gladly help.

Best! and thanks for all the hard work.

**Comment by distantnative** [comment]
Maybe we could even create a feed that merges the Kosmos issues with releases (feed that we would pull from GitHub first)?

**Comment by distantnative** [comment]
I think we should revisit this after the release of 3.4 based on what @lukasbestle is currently working on.

**Comment by Stolzenhain** [comment]
> Maybe we could even create a feed that merges the Kosmos issues with releases (feed that we would pull from GitHub first)?

Hmm … honestly, in this case I'd rather subscribe to both feeds individually.

In Kirby 2, the RSS feed used to be a simple template helper to be fed with filtered collections instead of regular PHP templates. (Here's a good example of the [WDRL one](https://wdrl.info/feed)) Don't know if the helper situation changed in 3.

**Comment by lukasbestle** [comment]
A feed class in the Kirby core is currently planned for Kirby 3.5.

**Comment by bastianallgeier** [comment]
✅  https://getkirby.com/kosmos.rss

**Comment by Stolzenhain** [comment]
:notes: Dreams are my reality…
