### ISSUE TITLE
Kirbytag (image: xxx) produces incorrect or surprising results when used with other text on the same line

### ISSUE THREAD

**Issue by jorgk3** [getkirby/getkirby.com#61]
Assuming that images are rendered as `<figure>`, that is, the following default option is used
`c::set('kirbytext.image.figure', true);`
the Kirbytag (image) doesn't work correctly when other text is used in the same line.

`text (image: xxx.jpg) more text`
produces (for example)
`<p>text <figure><img src="http://localhost:88/content/test/xxx.jpg" alt="xxx"></figure> more text</p>`

`(image: xxx.jpg) text ignored`
produces (for example)
`<figure><img src="http://localhost:88/content/test/xxx.jpg" alt="xxx"></figure>`

In the first case the produced HTML is incorrect, in the second case the system ignores part of the line.

**Comment by texnixe** [comment]
Have you tried with the latest 2.1 beta?

**Comment by jorgk3** [comment]
I have just now and it's still the way I described :-(

**Comment by texnixe** [comment]
Wrong repo, but bug seems to have been fixed in the meantime.
