### ISSUE TITLE
Missing icon for menu on mobile

### ISSUE THREAD

**Issue by tomasstana** [getkirby/getkirby.com#611]
Website is missing icon for menu on mobile devices. Tested in Chrome for iPhone and Safari.

![C56ECE1E-8E07-467A-9AC1-594F33F36D2D](https://user-images.githubusercontent.com/7951677/60709963-e5ca1f80-9f11-11e9-88d3-420a386df7e7.jpeg)

**Comment by nilshoerrmann** [comment]
I just noticed this as well. The hamburger icon is displayed black on black. You can interact with the menu when you know where it's located. It's visible on all pages with light backgrounds.
