### ISSUE TITLE
Textarea field properties: not all buttons correct ?

### ISSUE THREAD

**Issue by Pandorrrrrra** [getkirby/getkirby.com#613]
In the reference for textarea field properties `buttons` for me the options `list` and `|` divider are not working – don't know if they are outdated or if there are bugs ? Otherwise I'm happy to create an issue in the kirby repo.

https://getkirby.com/docs/reference/panel/fields/textarea#field-properties

Kirby 3.2.0 and 3.2.1-rc.1

**Comment by texnixe** [comment]
`list` doesn't have any effect, guess that is outdated (use `ul` or `ol`).

The divider works if you wrap it in quotes:

```
- "|"
```

**Comment by texnixe** [comment]
✅
