### ISSUE TITLE
Add documentation about bruteforce protection

### ISSUE THREAD

**Issue by GiantCrocodile** [getkirby/getkirby.com#615]
https://forum.getkirby.com/t/how-to-customize-override-the-user-password-validation/14844/4 (and posts after that)

**Comment by GiantCrocodile** [comment]
Please add the information that there's SHA256 hashing happening and why @lukasbestle. Thanks!

**Comment by lukasbestle** [comment]
We don't explain every technical implementation detail in the docs, that would get confusing. The docs are user-facing, not developer-facing. For that we have our code.

**Comment by GiantCrocodile** [comment]
I agree but this is more an user requirement to know what you have to provide as a part of your privacy policy: If you don't log any IP address at all (or in a irrevocable, anonymous way like hashing) it's fine. As an user, I don't want to check the code to know what I have to mention to be on the safe side of GDPR compliance ;). Right now it sounds like regular IP logging in a db/file like we had it with any ordinary software from some years ago, where privacy wasn't any serious topic.

**Comment by lukasbestle** [comment]
Thanks, I have created an issue here: https://github.com/getkirby/getkirby.com/issues/634
