### ISSUE TITLE
[Search] split search results, add categories and separate the result types

### ISSUE THREAD

**Issue by GiantCrocodile** [getkirby/getkirby.com#623]
See this post (https://forum.getkirby.com/t/cannot-find-used-blueprint-options-documentation-anywhere/15013/4?u=warg):

"I just checked the results of the Kirby site search with the terms “page parent” and “page section” and you are right: The correct spot of the documentation is listed. Maybe it makes sense to split the search results in general:

    Kirby 3 reference
    Cookbook and Guide
    Newsletter and information from the rest of the site

This way, the results are more structured and the more important stuff is on top. I think, there should be also some filtering possible, similar to the forum categories: Do you ask about a page, a blueprint or a setting? Also a preview of the search result would be nice when you hover over a single search result. If you agree, I post this as suggestions in the Github repo @texnixe."

It makes the life easier if you have added Kirby 3's search to your browser as an search engine via https://getkirby.com/search?q=<search termin>.

**(in general: see the whole thread as there are several suggestions for the site search)**

**Comment by distantnative** [comment]
I also think we should add something like a `searchTitle` to the pages that gets displayed in the search result instead of the actual title. 

If you search for `page`, you currently get:
<img width="961" alt="Screen Shot 2019-11-03 at 18 07 00" src="https://user-images.githubusercontent.com/3788865/68088994-c2ce5e80-fe64-11e9-871c-4be8b1bc67a5.png">

It should be rather something like
- Helper: page()
- Response type: Page
- Preset: page
- Icon: page
- Helper: pages()

**Comment by GiantCrocodile** [comment]
And then group by that (helper, response type, preset, etc.)

**Comment by distantnative** [comment]
Group by it? That would result in a lot of small groups. Don't think that's very beneficial. I feel like the three groups you suggested in the initial post make much more sense.

**Comment by GiantCrocodile** [comment]
Ah so you want to introduce both. I understood your idea as an alternative to mine. Yep, makes sense to use my categories and add the prefixes you've mentioned. Sounds like a neat solution!

**Comment by distantnative** [comment]
Closed in favor of https://github.com/getkirby/getkirby.com/issues/798
