### ISSUE TITLE
UI Kit Preview

### ISSUE THREAD

**Issue by zvaehn** [getkirby/getkirby.com#630]
How about a visual preview of the UI Kit Documentation?
https://getkirby.com/docs/reference/plugins/ui

**Comment by distantnative** [comment]
I'll leave this here: https://medium.com/@wojciechkrysiak/preview-your-vue-or-react-components-in-different-states-by-using-jsdoc-playground-included-5033d71ebb0e

Wondering if we could generate a static reference for a version with these tools and somehow incorporate them in the existing reference.
