### ISSUE TITLE
Blueprint Users Permissions Errors

### ISSUE THREAD

**Issue by manuelmoreale** [getkirby/getkirby.com#631]
I think I found a few mistakes in the docs

https://getkirby.com/docs/reference/panel/blueprints/user#permissions__page

The `page` setting should be `pages` I believe.

--- 

Also here...

https://getkirby.com/docs/guide/users/permissions#role-based-permissions-in-user-blueprints

In the initial overview of all the available settings I think we're missing the 

```
access:
    users: true/false
```

**Comment by texnixe** [comment]
Fixed. Thanks, @manuelmoreale!
