### ISSUE TITLE
List of Kirby features with GDPR/general privacy implications

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/getkirby.com#634]
- https://forum.getkirby.com/t/making-your-site-gdpr-ready-how-kirby-processes-personal-data/10471?u=lukasbestle (still applicable except the Panel part, which now only uses a session cookie and stores everything else in `localStorage`)
- Brute-force protection: Shortened SHA256 hash of the IP address stored temporarily on login failures (can't be converted back to the raw IP address)

**Comment by texnixe** [comment]
Where do we want to put this? As a last section in the guide (probably the best option "Kirby & GDPR")? As a subsection of another chapter? Doesn't really fit into any of the current chapters, I think.

**Comment by lukasbestle** [comment]
I'd say a new section "Kirby & GDPR" would probably be best. That would increase the visibility of the topic as well.

**Comment by distantnative** [comment]
Make it “Kirby & Privacy” to make it not too specific and understandable for people who have not heard about GDPR?

**Comment by texnixe** [comment]
@fabianmichael Could you provide an icon for this new guide section?
