### ISSUE TITLE
Indexing of advanced stuff of the Reference

### ISSUE THREAD

**Issue by GiantCrocodile** [getkirby/getkirby.com#638]
It would be nice if the advanced stuff is indexed because otherwise you search quite some time like I did in this case: https://forum.getkirby.com/t/how-to-find-documentation-for-remote-get/15131/2

**Comment by texnixe** [comment]
Is there a reason why this stuff isn't indexed? Intentional? Do we want to implement this?

**Comment by GiantCrocodile** [comment]
If there is a reason like "it would result in too many search results": Just add a checkbox (and GET parameter) to disable/enable advanced stuff search.

**Comment by texnixe** [comment]
@bastianallgeier, @distantnative ?

**Comment by distantnative** [comment]
Closed in favor of https://github.com/getkirby/getkirby.com/issues/798
