### ISSUE TITLE
Problems running the site locally

### ISSUE THREAD

**Issue by trych** [getkirby/getkirby.com#648]
As I had to do my first minor contributions to the docs "blindly" (I could not check them locally) I would now like to set this up in a way that I can also run the site locally, so I can better help out with contributions to the docs.

I followed the instructions, cloned the repo, ran `npm install` and then tried to run `npm start`.
That gives me a bunch of errors though and I don't know enough about npm to make sense of these:

```
mbp-trych-2:getkirby.com trych$ npm start

> getkirby.com@3.0.0 start /Users/trych/Documents/Coding/github/getkirby.com
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

internal/modules/cjs/loader.js:628
    throw err;
    ^

Error: Cannot find module '/Users/trych/Documents/Coding/github/getkirby.com/node_modules/laravel-mix/setup/webpack.config.js'
Require stack:
- /Users/trych/Documents/Coding/github/getkirby.com/node_modules/webpack/bin/convert-argv.js
- /Users/trych/Documents/Coding/github/getkirby.com/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at requireConfig (/Users/trych/Documents/Coding/github/getkirby.com/node_modules/webpack/bin/convert-argv.js:97:18)
    at /Users/trych/Documents/Coding/github/getkirby.com/node_modules/webpack/bin/convert-argv.js:104:17
    at Array.forEach (<anonymous>)
    at module.exports (/Users/trych/Documents/Coding/github/getkirby.com/node_modules/webpack/bin/convert-argv.js:102:15)
    at /Users/trych/Documents/Coding/github/getkirby.com/node_modules/webpack/bin/webpack.js:171:41
    at Object.Yargs.self.parse (/Users/trych/Documents/Coding/github/getkirby.com/node_modules/yargs/yargs.js:533:18) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/trych/Documents/Coding/github/getkirby.com/node_modules/webpack/bin/convert-argv.js',
    '/Users/trych/Documents/Coding/github/getkirby.com/node_modules/webpack/bin/webpack.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! getkirby.com@3.0.0 start: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the getkirby.com@3.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/trych/.npm/_logs/2019-08-07T11_13_49_188Z-debug.log
```

Does anybody know, what's the issue here and how I can solve it?

Also, there were some errors after running the `nmp install` already, I find it quite likely that they are causing the issue. Here is a screenshot of the errors in the end of the `npm install`:

![20190807-131309_Screenshot_Terminal](https://user-images.githubusercontent.com/9803905/62619135-5780f900-b916-11e9-93e5-bb6c33474394.png)

Any help would be very appreciated.

**Comment by texnixe** [comment]
If you only want to contribute to the docs, you don't need any of that, clone the repo and open the site at `http::/localhost/getkirby/www` or point your host to the www folder (if you use Valet, use the `link` command to link your host to that folder.

The npm stuff is only needed for development.

**Comment by trych** [comment]
> The npm stuff is only needed for development.

Ok, I indeed only want to contribute to the docs, so I can skip the npm stuff obviously.
Still, how do I locally serve the site?

Usually I serve Kirby pages by going to the root directory and doing

```
php -S localhost:8000 kirby/router.php
```

in the Terminal. However, that doesn't work here. What do I need to do instead?

**Comment by texnixe** [comment]
What if you call it from the **`www`** folder without the router:

```
php -S localhost:8000
```

**Comment by trych** [comment]
The serving itself works, but it does not load in any images. Any way to make this load images as well?

**Comment by texnixe** [comment]
Hm, maybe you need the router after all, in my test it worked but maybe because all the images are already there. Not using this simple setup myself, so can't really tell.

I recommend you use a "real" dev environment.

**Comment by trych** [comment]
If I add `kirby/router.php` again, it does not serve the site at all anymore:

```
php -S localhost:8000 kirby/router.php
PHP 7.1.23 Development Server started at Wed Aug  7 14:25:14 2019
Listening on http://localhost:8000
Document root is /Users/timo/Documents/Coding/github/getkirby.com/www
Press Ctrl-C to quit.
[Wed Aug  7 14:25:21 2019] PHP Warning:  Unknown: failed to open stream: No such file or directory in Unknown on line 0
[Wed Aug  7 14:25:21 2019] PHP Fatal error:  Unknown: Failed opening required 'kirby/router.php' (include_path='.:') in Unknown on line 0
[Wed Aug  7 14:25:25 2019] PHP Warning:  Unknown: failed to open stream: No such file or directory in Unknown on line 0
[Wed Aug  7 14:25:25 2019] PHP Fatal error:  Unknown: Failed opening required 'kirby/router.php' (include_path='.:') in Unknown on line 0
```

Any quick way to sort this out? Otherwise I will have to indeed look into dev environments (which I would like to avoid if possible).

**Comment by texnixe** [comment]
My assumption is that this custom setup is not supported by the router file. You probably have to fiddle with the `router.php` to make it work. We do not officially support the built-in php server.

**Comment by trych** [comment]
Ok, fair enough. I will look into running it via Laravel Valet instead.

**Comment by trych** [comment]
Alright, I got it running via Valet (and have to admit that – once it is set up correctly – this seems like a quite convenient dev environment :wink:).

**Comment by texnixe** [comment]
It definitely is.
