### ISSUE TITLE
unittesting cookbook add howto install phpunit globally

### ISSUE THREAD

**Issue by bnomei** [getkirby/getkirby.com#649]
you could add here https://getkirby.com/docs/cookbook/setup/plugin-workflow
how to install phpunit with composer globally in linking this article: 
https://akrabat.com/global-installation-of-php-tools-with-composer/

**Comment by bnomei** [comment]
well this actually creates a fatal error when running the composer script `test`.

> PHP Fatal error:  Cannot redeclare dump() (previously declared in /Users/brm/.composer/vendor/symfony/var-dumper/Resources/functions/dump.php:18) ...

**Comment by texnixe** [comment]
@bnomei What do you mean? Your suggestion doesn't work?

**Comment by bnomei** [comment]
nevermind. installing php unit globally should not be part of the cookbook.
