### ISSUE TITLE
Missing 3.2 docs

### ISSUE THREAD

**Issue by texnixe** [getkirby/getkirby.com#655]
- [x]  created plugin type ?
- [x]  Overriding Panel views with custom views
- [ ]  Using the Uploadfile.js helper ?
- [x]  New `$file->srcset()` syntax

**Comment by PaulMorel** [comment]
Is it possible that the new `$file->srcset()` syntax from this PR is missing https://github.com/getkirby/kirby/pull/1806 ? Assuming it made it into 3.2.

**Comment by texnixe** [comment]
Yes, guess I missed that.

**Comment by bastianallgeier** [comment]
The new `created` plugin type for the panel runs plugin code directly after the Vue instance has been loaded and gives access to the instance. You can use this to create your own modules for Vuex, add additional routes, register additional global events and more. 

```js
panel.plugin("my/plugin", {
  created(Vue) {
    // work with the newly created Vue instance here.   
  }
});
```

**Comment by bastianallgeier** [comment]
I wouldn't document the uploadfile.js helper yet, because we need new helpers docs for 3.3.0 anyway since we have a great new way to use them there.

**Comment by bastianallgeier** [comment]
Panel views: 

You can now overwrite our default panel views by replacing our view components. 

The following components can be replaced by you: 

- k-browser-view
- k-login-view
- k-installation-view
- k-site-view
- k-file-view
- k-page-view
- k-settings-view
- k-users-view
- k-user-view

```js
panel.plugin("my/view-plugin", {
  components: {
    "k-users-view": {
      // your Vue component code goes here. 
    } 
  }
});
```

Our views are often very complex. If you want to replace them without loosing features, you should check out the orginal source code for each component. You can find them in https://github.com/getkirby/kirby/tree/master/panel/src/components/Views

**Comment by distantnative** [comment]
✅
