### ISSUE TITLE
Non-consistent use of '<?php' in reference code snippets

### ISSUE THREAD

**Issue by plagasul** [getkirby/getkirby.com#658]
This is certainly not too relevant, but, for example in this ref. page 

https://getkirby.com/docs/reference/plugins/extensions/kirbytags

... the third code snippet starts with `<?php` but not the first two, is there a reason for this? perhaps the first two are supposed to be just a part of the refered file? if not, then I would expect the use of `<?php` to be consistent.

Thank you

**Comment by texnixe** [comment]
Hm, I understand your point, but in this case it makes sense to make it clearer for that one file, while we generally don't seem to have php tags in those `Kirby::plugin` files.
