### ISSUE TITLE
Docs: changeStatus method needs permissions

### ISSUE THREAD

**Issue by philipmarnef** [getkirby/getkirby.com#664]
I was trying to call `$page->changeStatus` from a route and got a permissions exception. Apparently I needed to set `kirby()->impersonate('kirby')` before I could update the page, but I didn't find any mention of this in the docs. The `changeStatus` reference page only mentions:

> Note that you cannot change the status of a page using this method if you have set permissions that disallow changing the status, e.g. set status: false in your blueprint.

I only ever did this in a hook before where I didn't need to set this permission, so I had no I idea. My suggestion:

> Note that you cannot change the status of a page using this method if you have set permissions that disallow changing the status, e.g. set status: false in your blueprint. When calling this method from a controller or route, you need to impersonate a user with the proper permissions first, e.g. with `kirby()->impersonate('kirby')`.

**Comment by texnixe** [comment]
That these methods need permissions is the rule, not the exception, each of this methods has an indicator below the title, so I wouldn't put this in the note.

**Comment by texnixe** [comment]
But maybe we have to somehow make it more obvious.

**Comment by philipmarnef** [comment]
I saw the lock icon at the top, but had no idea what it meant. The ? hover is empty. It doesn't link to a page explaining what it means either.

So yes, I think you should make it more obvious 🙂

**Comment by philipmarnef** [comment]
Closing message: so the `page.changeStatus` hover link in the docs wasn't being loaded in my browser window for whatever reason, so the docs do provide more info than I thought they did.
