### ISSUE TITLE
Incomplete $file reference: proxied Kirby\Image\Image methods not listed

### ISSUE THREAD

**Issue by distantnative** [getkirby/getkirby.com#666]
e.g. $file->dimensions()

**Comment by texnixe** [comment]
Methods from the Toolkit file class are also missing, e.g. `$file->mime()`

**Comment by nilshoerrmann** [comment]
Would be nice to see these added to the reference. It took me quite a while to figure out that these methods exist and that I was able to find them under “Advanced” > “All classes”.

I understand why the search excludes results from the advanced area by default but this makes it really hard to find methods listed there. Would it be an option to have an basic/advanced switch for the search similar to how it works in other areas of the docs:

![Bildschirmfoto am 2019-11-06 um 11 40 38](https://user-images.githubusercontent.com/25466/68291516-516ff500-008a-11ea-8144-2242c6edba41.png)

**Comment by GiantCrocodile** [comment]
@nilshoerrmann related to your suggestion: https://github.com/getkirby/getkirby.com/issues/638

**Comment by texnixe** [comment]
What would be the best way to handle this?

**Comment by distantnative** [comment]
I think, a way could be to add a field `proxies` (or so) to the `class.txt` content file wtih the class name inside (`Kibry\Image\Image`).
And if such a field is present, then the page model in its `children()` method should first add the methods from the `Image` class and second add its own methods (to properly overwrite the proxied ones).
