### ISSUE TITLE
Add nginx config example

### ISSUE THREAD

**Issue by texnixe** [getkirby/getkirby.com#670]
https://forum.getkirby.com/t/nginx-issues-500-error-for-media-and-panel-no-input-file-specified/12980/2?u=texnixe

**Comment by bnomei** [comment]
this is a good place to start: https://github.com/h5bp/server-configs-nginx/tree/master/h5bp

**Comment by texnixe** [comment]
Closing this, because we now have this recipe: https://getkirby.com/docs/cookbook/setup/nginx
