### ISSUE TITLE
users current is not the current user

### ISSUE THREAD

**Issue by bnomei** [getkirby/getkirby.com#675]
please add a warning that `$kirby->users()->current()` is not the proper way to get the _current logged in user_. the `current` method is part of the iterator `users()`.

the right way to do it is `$user = $kirby->user()` as described here:
https://getkirby.com/docs/cookbook/security/access-restriction#the-logout__adding-a-logout-link-to-the-menu

**Comment by bnomei** [comment]
add warning here:
https://getkirby.com/docs/reference/objects/users/current

**Comment by texnixe** [comment]
Where does it say it is the right way to get the current logged in user? All "collections" have this `current()` method. Or do you mean "just in case someone might think they can get the currently logged in user with this method"?

https://getkirby.com/docs/reference/objects/user#how-to-create-a-user-object__the-current-user

**Comment by bnomei** [comment]
thats how it worked in k2. but now it does not. old habits are hard to loose. 🤷‍♂ 
https://getkirby.com/docs/archive/v2

**Comment by texnixe** [comment]
> thats how it worked in k2

Not quite, in K2 there was a `$user->current()` method that got you the current user, not `$users->current()`, just saying.

**Comment by bnomei** [comment]
oh boy it did not. is was `$kirby()->user()->current()` back then. you decide what to do. aww you where faster. :D

**Comment by bnomei** [comment]
i wanted the current user. typed `current user` in docs search an got a method that seem well enough. i also got a user so i thought hey fine. but i also got the same one when i was logged out of frontend. and thats why i thought it might happen to someone else as well.

**Comment by texnixe** [comment]
So, here's your personal warning: https://getkirby.com/docs/reference/objects/users/current
