### ISSUE TITLE
Cache Reference Uses `driver` but Should be `type`

### ISSUE THREAD

**Issue by neildaniels** [getkirby/getkirby.com#681]
In https://getkirby.com/docs/reference/system/options/cache#cache-driver, it says that using a different cache driver should use:

```php
return [
  'cache' => [
    'driver' => 'memcached'
  ]
];
```

But I assume it should be `type` (not `driver`), as described in https://getkirby.com/docs/guide/cache.

**Comment by lukasbestle** [comment]
Thanks for pointing that out, you are right!
