### ISSUE TITLE
Fix broken multi site setup example

### ISSUE THREAD

**Issue by bastianallgeier** [getkirby/getkirby.com#682]
See: https://github.com/getkirby/kirby/issues/2048

The media URL has to be specified as well if it's not accessible at `/media`

```php
$kirby = new Kirby([
  'roots' => [
    'media' => __DIR__ . '/media/test'
  ],
  'urls' => [
    'media' => 'http://yourdomain.com/media/test'
  ]
]);
```

**Comment by bcevc** [comment]
I don't know whether I'm on the right track here, but then the whole directory structure in the cookbook seems strange. 

The suggested directory structure is:

/index.php
/kirby/...
/site1/media
/site1/site
/site2/media
/site2/site

and so on. 

If I'm not mistaken, that would mean that the media URL would need to be https://site2.example.com/site2/media – which seems somewhat bizarre to me.

**Comment by texnixe** [comment]
I wanted to update the docs but tested it first and somehow I still can't get this example to work. Tried this setup (and some variations of it):

```
<?php
require 'kirby/bootstrap.php';

$sites = [
  'kirby.test' => __DIR__ . '/site1',
  'shop.test' => __DIR__ . '/site2'
];

$url  = Url::host();
$root = $sites[$url];
$kirby = new Kirby([
  'roots' => [
    'index'   => __DIR__,
    'site'    => $root . '/site',
    'content' => $root . '/content',
    'media'   => $root . '/media',
    'assets'  => $root . '/assets'
  ],
  'urls' => [
    'media' => kirby()->url(). '/media', // or url() . '/media' or `url('media')`
    'assets' => kirby()->url(). '/assets'
  ]
]);
echo $kirby->render();
```

with a folder structure like in the [docs](https://getkirby.com/docs/cookbook/setup/multisite#in-the-filesystem).

Local env setup with valet and both `kirby.test` and `shop.test` mapped to the parent folder.

On first load, the images load, but on second load they are gone again. The assets don't load at all, no matter if the `urls` property is set or not.

I don't know if this is a bug or a completely wrong setup, but I'd like to see a working example to include in the docs.

**Comment by bcevc** [comment]
If I can support here, please let me know. My understanding is that the roots folder is the issue, not the URL. At least in my setup, if I'm not mistaken or mis-remebering, Kirby kept reverting to $mainroot/media instead of $mainroot/site1/media (with $mainroot referring to the path hosting index.php, i.e. __DIR__). As it always partially fell back to the wrong (filesystem) folder, the URLs would not help. And, frankly, setting the URL to the folder in the filesystem would create URLs like https://$domain/site1/media/... which looks plain ugly (and is in most setups not something you would like to do, as it would uncover your inner structure in the URL.

As for me, the (now working) setup is:
```
<?php

require 'kirby/bootstrap.php';

$sites = [
  'fingolex.com' => __DIR__ . '/fl-prod',
  'www.fingolex.com' => __DIR__ . '/fl-prod',
  'staging.fingolex.com' => __DIR__ . '/fl-staging',
];

$url  = Url::host();
$root = $sites[$url];

$kirby = new Kirby([
  'roots' => [
    'index'   => __DIR__,
    'site'    => $root . '/site',
    'assets'    => $root . '/assets',
    'content' => $root . '/content',
\#    'media'   => $root . '/media',
    'accounts' => __DIR__. '/fl-all/site/accounts',
  ]
]);
echo $kirby->render();
```

**Comment by bastianallgeier** [comment]
Here's my suggestion for a working setup: 

```php
<?php

require __DIR__ . '/kirby/bootstrap.php';

$sites = [
    'domain-1.com',
    'domain-2.com',
];

$host = Url::host();
$url  = 'http://' . $host;

if (in_array($host, $sites) === false) {
    die('Site not found');
}

$kirby = new Kirby([
  'roots' => [
    'index'   => __DIR__,
    'site'    => __DIR__ . '/site/' . $host,
    'content' => __DIR__ . '/content/' . $host,
    'media'   => __DIR__ . '/media/' . $host,
    'assets'  => __DIR__ . '/assets/' . $host
  ],
  'urls' => [
    'media'  => $url . '/media/' . $host,
    'assets' => $url . '/assets/' . $host
  ]
]);

echo $kirby->render();
```

This will create subfolders in `content`, `site`, `assets` and `media` depending on the current domain. I.e. 

```
/content/domain-1.com/
/site/domain-1.com/
/assets/domain-1.com/
```

The media routing will only work if the media folder is actually accessible at the given URL that you setup. That's why @texnixe's example didn't work. You could of course turn it around and use the domain as main folder and have assets, content and media as subfolders. That doesn't really make a difference and is more a matter of taste. But `domain.com/.../media` or `domain.com/media/...` must point to actually existing folders on the server.

**Comment by texnixe** [comment]
Ok, thanks @bastianallgeier. The above setup works for the media folder but not for the assets. That is, the @auto CSS links are generated correctly, but not the standard CSS links:

```
<link href="http://d2.test/assets/css/index.css" rel="stylesheet">
<link href="http://d2.test/assets/d2.test/css/templates/home.css" rel="stylesheet">
```

Guess, that's a bug. 

Unfortunately, the generated media and asset URLs are pretty ugly.
