### ISSUE TITLE
Make the Plainkit more visible

### ISSUE THREAD

**Issue by medienbaecker** [getkirby/getkirby.com#689]
Currently, the [plainkit](https://github.com/getkirby/plainkit) is only downloadable here: https://getkirby.com/docs/guide/installation#installation

The starterkit may be the better kit for newbies, but it's not really suited for starting a new project.

**Comment by texnixe** [comment]
https://forum.getkirby.com/t/where-can-i-download-kirbys-plainkit/15602/2

**Comment by texnixe** [comment]
Step 1: it is now in the Quickstart guide: https://getkirby.com/docs/guide/quickstart

**Comment by distantnative** [comment]
Closed in favor of https://github.com/getkirby/getkirby.com/issues/760
