### ISSUE TITLE
Feature editor on homepage

### ISSUE THREAD

**Issue by texnixe** [getkirby/getkirby.com#690]

**Comment by GiantCrocodile** [comment]
I would like to see an information about if the new editor is an official part of the core or just a plugin without official, same quality support and updates as the core then. This is an important information to know if we can use the editor without any additional risks.

**Comment by distantnative** [comment]
@GiantCrocodile the editor will remain a plugin for now - that’s the current plan. Basically as it is not small and not needed by everyone. Of course it will be an official
Plugin, so it has a very special status in that sense.

**Comment by GiantCrocodile** [comment]
Hmm, so what's the license of this plugin @distantnative? Will it be 100 % compatible with the license of Kirby 3? I found no license info in the repository.

**Comment by bastianallgeier** [comment]
@GiantCrocodile it will be a free plugin but with the same proprietary license. Kirby users can use it for their sites without limitation.

**Comment by GiantCrocodile** [comment]
Thank you for the clarification @bastianallgeier!
