### ISSUE TITLE
Add 3.3.0 docs

### ISSUE THREAD

**Issue by texnixe** [getkirby/getkirby.com#711]
- [x] Search in pages, files, users fields
- [x] Pagination  in pages, files, users fields
- [x] `subpages` option pages field
- [x] New field methods: `$field->inline()` and `$field->nl2br()`
- [x]  `deprecated()` helper
- [x] `flip` option for pages and files sections
- [x] New Hooks
- [x] User ID instead of email stored in users field
- [x] New collection methods: `intersects()` , `intersection()`
- [x] `ready` config option
- [x] `svg()` helper with file objects
- [x] Section shortcuts
- [x]  `$collection->when()` method: https://github.com/getkirby/ideas/issues/349
- [x] Smartypants per language
- [x]  Use `kirbytext` in info field/section/field help text
- [x] New icons (should be included automatically)
- [x] CSS variables (maybe find a better place or link to this from other parts, or make it more obvious that these types of pages contain more information)
- [x] Extendable dump() helper
- [x] $pages->notTemplate()
- [x] `$kirby->nonce()` method
- [x] Register license w/o Panel
- [x] New Visitor::preferredMimeType() method (auto)
- [x] New Visitor::prefersJson() method (auto)
- [x] New Mime::matches() method (auto)
- [x] Plugin hooks
- [x] Unsaved changes
- [x] New isUploadEvent helper for the panel
- [x] expose libraries to plugins (add to new Panel internals section)
- [x] Content store (WIP)
- [x] New ::panelOptions method for all models (Page, User, File)
- [x] New ErrorPageException (where?)
- [ ] Immutable pagination objects
- [x] switch off the toggle text in structure columns entirely with the text option (3.3.0-rc.2)

**Comment by texnixe** [comment]
Have I missed anything in the list above? The rest looked like internal stuff to me.

**Comment by afbora** [comment]
@texnixe I couldn't find `content.locking` option in document for 3.2.5: https://github.com/getkirby/kirby/pull/2025

Other than that, I couldn't see anything missing 👍

**Comment by distantnative** [comment]
Documenting the whole content store. Probably best when I get on that?

**Comment by texnixe** [comment]
@distantnative Definitely!

**Comment by distantnative** [comment]
Last remaining one: https://github.com/getkirby/getkirby.com/issues/759
