### ISSUE TITLE
Reference: Icons missing in overview

### ISSUE THREAD

**Issue by distantnative** [getkirby/getkirby.com#725]
<img width="1052" alt="Screen Shot 2019-10-31 at 20 56 06" src="https://user-images.githubusercontent.com/3788865/67981422-ed2fda00-fc20-11e9-8305-cac0ad3d87bd.png">

on https://getkirby.com/docs/reference

**Comment by texnixe** [comment]
What is missing?

**Comment by distantnative** [comment]
I can't see the preview of the icon in the grey square.

**Comment by texnixe** [comment]
🙈
