### ISSUE TITLE
[Docs] Licensing request can leak information

### ISSUE THREAD

**Issue by GiantCrocodile** [getkirby/getkirby.com#736]
According to https://getkirby.com/docs/guide/kirby-and-privacy#features-with-privacy-implications__licensing only the domain of the Kirby 3 installation is sent to the licensing server. This seems to be not precise enough: The domain and the directory of Kirby 3 is sent to the server.

Situation:
I suspect `mydomain.tld` is sent to the server and is being stored in relation to my license.
In fact `mydomain.tld/<my Kirby 3 folder>` is stored in relation to my license.

Problem:
This might disclose personal names or project names without being aware, depending on your folder name structure.

Solution:
Either mention it or just store the domain without the folder name.

**Comment by lukasbestle** [comment]
Kirby transmits the index URL of the site, which also includes the path. This is because each license is valid for one installation – and installations are defined by their index URL.

I have fixed this in the docs.
