### ISSUE TITLE
Add information about privacy implications if you embed content

### ISSUE THREAD

**Issue by GiantCrocodile** [getkirby/getkirby.com#737]
https://getkirby.com/docs/guide/kirby-and-privacy#features-with-privacy-implications__licensing should have a mention about stuff like the video kirbytag and youtube/vimeo helpers and that they will disclose more or less information about the visitor of your site. This might be not too clear to everyone (especially how much impact it has if you embed a plain youtube video for example regarding cookies, third party sites loading, ip address leak, etc.) due to being a native Kirby 3 feature. Maybe it can be mentioned to check the network and cookie/local storage tab of your browser to check it for any content embedded.

**Comment by distantnative** [comment]
Wondering how far we would need to take this...
Cause basically using any remote image has the same implications.

**Comment by GiantCrocodile** [comment]
I didn't embed a remote image yet. Is this possible with Kirby 3's editor? Then we should mention it. My major point is that it's a tiny and useful feature in the editor but resulting in quite some code and YouTube videos embedded leading to third party cookies and sites being loaded which is not typical for embedding a remote image.

**Comment by distantnative** [comment]
Well it is possible with the image KirbyTag. All of this is possible to do in Kirby's templates.
Wondering where to draw the line.

**Comment by GiantCrocodile** [comment]
I see. Maybe we should add a general one sentence warning about remote images and videos via kirbytags?

The level of detail of this guide depends on what we want to provide to the reader:
- Is it a guide to check your own site for complying with legal regulations?
- Is it a guide you can link to in case of a legal review by the data protection officer in your country so they better understand where Kirby 3 is an privacy risk/no risk?
- Do we want to educate the user who creates content?
- Do we want to educate the site administrator for features to watch out/to monitor for?
- Is it about what the Kirby software owner/founder knows about you/your site?

I would like to have this page as an answer to all these questions, not just one or two. It's an topic which shouldn't be answered too unprecise as it's one of the most major topics of the web for the last years and the next years. On top of this, as an user and customer, I have quite high expectations regarding privacy aspects from a software made in Germany as it's a major selling point and something Germany stands for.

**Comment by lukasbestle** [comment]
Our goal for that page mostly fits "Do we want to educate the site administrator for features to watch out/to monitor for?".

We aren't lawyers and can't (= aren't allowed to under German legislation) provide legal advice. We write exactly that in the info box in the intro. I get that you as the user and developer want as much helpful information as possible, but in the end it can only be a voluntary offer of information from us to you. Most companies probably don't even have such a guide. :)

As Nico wrote:

> Wondering how far we would need to take this...
> Cause basically using any remote image has the same implications.

I think we need to distinguish between Kirby features and other ways of using Kirby that are unrelated to Kirby in particular. For example you could argue that we should include information on analytics trackers that are commonly used – but those are no Kirby feature. That's why I'd say that remote images aren't something we'd need to mention.

The `video` KirbyTag and helpers are something we could mention though.

**Comment by GiantCrocodile** [comment]
Of course it's a voluntary offer but it still impacts the decision of buying Kirby and reduces legal fears and risks. I wouldn't agree too much with the statement that most companies don't have a guide like this: Maybe not a guide but I see a huge impact of the GDPR on the information provided about data processing and transferring, even at in-the-past-not-so-privacy-focused-companies like e. g. SAP and Microsoft who are working a lot on improving the transparency and understanding regarding these topics and they provide more and more excessive information. So there's a noticeable change and I think it's just a matter of time who will be lost on the market because no or incomplete information is provided.

The analytics tracker part is something I see different to this. There is no Kirby tracking feature so I would say it's optional to provide information about it (same as Google Fonts which isn't used by Kirby 3's core).

The tags and helpers seem to be a reasonable balance between too much and too less information.

**Comment by texnixe** [comment]
I completely agree with @lukasbestle and I think we should be careful here. The more detailed information we provide, the more likely it is that people rely on this information and think they are on the safe side despite our disclaimer. Such a guide can also never be a source of information for data protection officers, as each individual Kirby instance will be different from what Kirby in its "raw" state provides.

I think the guide in its current state makes it very clear that there are many things to keep in mind when creating content for the web, and we already provide a lot of information that goes beyond the mere Kirby implications. But it is each website owners own responsibility to inform themselves or get legal advice from a lawyer.

**Comment by distantnative** [comment]
Maybe we can add a section next to „data submitted by visitors” that mentions that you need to be careful when embedding/using remote/external sources/data, using the video tag as an example. This way I feel like we stick to the current strategy but add one pointer to make people aware: “that’s also an area you should think about. We can’t do all the thinking for you, but we help you with a short comment to put it in your list”

**Comment by distantnative** [comment]
✅
