### ISSUE TITLE
Visuals: download boxes

### ISSUE THREAD

**Issue by distantnative** [getkirby/getkirby.com#739]
A bit related to https://github.com/getkirby/getkirby.com/issues/689, but I just feel that this part could be prettier and highlight the download options visually much more:

<img width="768" alt="Screen Shot 2019-11-03 at 22 31 57" src="https://user-images.githubusercontent.com/3788865/68092294-e35cdf80-fe89-11e9-995d-ec9b9258f4b2.png">

**Comment by GiantCrocodile** [comment]
Adding some icon like a disk or something else as a symbol for a download might attract the eyes attention more.

**Comment by distantnative** [comment]
Closed in favor of https://github.com/getkirby/getkirby.com/issues/800
