### ISSUE TITLE
[Docs] Storing translations in JSON format in `site/translations`

### ISSUE THREAD

**Issue by tillprochaska** [getkirby/getkirby.com#740]
I was just looking for the easiest way to store translations in JSON or YAML format instead of having them directly in the language configuration file.

The first relevant information I found is this [cookbook article](https://getkirby.com/docs/cookbook/i18n/language-variables) that proposes to manually load those files in the language config.

Alternatively, it seems possible to simply place JSON files in `site/translations` which will then be loaded automatically. I think this is the most convenient solution (at least if you’re working with JSON files). However, (if I’m not mistaken) this solution isn’t mentioned in the docs.

Would be great if this solution was mentioned in the [guide](https://getkirby.com/docs/guide/languages/custom-language-variables).

**Comment by texnixe** [comment]
I've never heard of this feature and can't get it to work?

**Comment by distantnative** [comment]
> Alternatively, it seems possible to simply place JSON files in site/translations which will then be loaded automatically.

Where did you pick up that info?

**Comment by texnixe** [comment]
Maybe you used keys that exists in  Kirby's json translations like 

```
echo t('change');
```

**Comment by tillprochaska** [comment]
I just tried to reproduce this in a latest starterkit and you’re totally right, that’s not actually working.

I’ve been on an older Kirby versions where the now removed `translations` root still existed. And I had overwritten it to `site/translations` when initializing the Kirby instance.

Sorry for causing confusion!

**Comment by texnixe** [comment]
No worries.
