### ISSUE TITLE
Adding mod_rewrite as a requeriment in 'Get up and running' page (website suggestion)

### ISSUE THREAD

**Issue by plagasul** [getkirby/getkirby.com#748]
If mod_rewrite is **NOT** enabled for Apache2, kirby won't work

But mod_rewrite is **NOT** present among the requeriments in the ['get up and running' section](https://getkirby.com/docs/guide/quickstart)

Unless it is supposed to be enabled by default (not my case in debian/ubuntu based linux mint with default config) I suggest you add it.

Thank you

**Comment by texnixe** [comment]
We have added URL rewriting as required to keep it more general.
