### ISSUE TITLE
Flags for immutable objects/methods

### ISSUE THREAD

**Issue by distantnative** [getkirby/getkirby.com#759]
Somehow highlight that a method doesn't mutate the object itself but only returns an altered object.

**Comment by distantnative** [comment]
Once https://github.com/getkirby/kirby/pull/3167 is merged and released, we could automate this check:

Return type
- `$this` = mutuable
- `static` or `self` = immutable

By no, I think a glass would be too little for users to understand. This probably needs to be a dynamically added text paragraph/section explaining what immutable also means and how to deal with it.

To discuss: how do we treat methods that depending on the parameter passed return `$this` (usually unchanged) or `static`?

**Comment by lukasbestle** [comment]
We could use the type hint `$this|static` for that. In this case, we'd need a manual text for what it means that would be printed instead of the auto-generated mutability info box.
