### ISSUE TITLE
Remove `$request->ajax()` examples

### ISSUE THREAD

**Issue by texnixe** [getkirby/getkirby.com#764]
- [x] https://getkirby.com/docs/reference/objects/request
- [ ] https://getkirby.com/docs/cookbook/templating/generating-json

**Comment by johannschopplich** [comment]
Just saw this issue. Opened a PR yesterday regarding the cookbook article: https://github.com/getkirby/getkirby.com/pull/766

**Comment by johannschopplich** [comment]
@texnixe Merged. You can close this issue. 🙂

**Comment by texnixe** [comment]
Thanks, @jschopplich!
