### ISSUE TITLE
events example documentation typo

### ISSUE THREAD

**Issue by marianruberg** [getkirby/getkirby.com#778]
The example code at https://getkirby.com/docs/reference/panel/samples/events#example-template has a typo at line 17:
` <time><?= $event->from()->toDate()('d.m.') ?> - <?= $event->to()->toDate('d.m.Y') ?></time>`
should be
` <time><?= $event->from()->toDate('d.m.') ?> - <?= $event->to()->toDate('d.m.Y') ?></time>`

**Comment by texnixe** [comment]
Thank you!
