### ISSUE TITLE
Recipe: "How to use Git and Composer to maintain your kirby application"

### ISSUE THREAD

**Issue by vauvarin** [getkirby/getkirby.com#790]
I'm currently updating my Kirby websites and plugins manually by replacing files/folder and I know it's not the best solution. I'm not very familiar with composer but it seems the preferred solution by "pro" dev. I would like to suggest this topic for a cookbook: "How to use Git and Composer to maintain your kirby application" (what cmd use, what files/folder exclude in the .gitignore, using composer cmd on local/dev server or on production server ? ...) What do you think? could it be usefull for other Kirby users?

**Comment by afbora** [comment]
Following pages does not meet your needs?

https://getkirby.com/docs/cookbook/setup/composer
https://getkirby.com/docs/guide/plugins/plugin-setup-composer

**Comment by lukasbestle** [comment]
@vauvarin The first two questions are answered in the [general Composer recipe](https://getkirby.com/docs/cookbook/setup/composer) @afbora linked to.

Regarding the question whether to run Composer on the dev or production server: That depends on your deployment strategy. If you deploy via direct upload (SFTP, rsync etc.), Composer should be run on the local machine like the other build steps. If you deploy via Git, the vendor files shouldn't be included in the repo (see the tutorial linked to above), so Composer dependency installation (like other build steps) should be executed while deploying – either on a separate deployment server or on the production server. As that all very much depends on the setup, we can't really explain it all in the docs.

Let me know in case you have any further questions or ideas on what information we could add to the docs.
