### ISSUE TITLE
Sticky menus for guides

### ISSUE THREAD

**Issue by distantnative** [getkirby/getkirby.com#794]
Longer guides are a bit of a problem right now (and for these problemsn not happening that much):

- The main menu on the left is disappearing quite soon after scrolling
- The TOC at the top is never seen again.

I feel like it would be great to have a sticky TOC appear on the right once the actual TOC is scrolled out of view. That way, one would always have orientation where I am on the current page.

And with a sticky left menu, I could also move on at any time.

**Comment by distantnative** [comment]
@bastianallgeier don't we wanna do this at some point?

**Comment by bastianallgeier** [comment]
The more I work with them the more I hate sticky elements. There are some places where they make sense (i.e. the new home page) but in general they introduce so much trouble. I just recently read a good rant about sticky on Twitter. It's often already difficult for "regular" browsing, but it also introduces a massive accessibility issue when you need to zoom in.

**Comment by distantnative** [comment]
I think you could argue the same for only having a TOC on top but not throughout the page when reading the content. I get that sticky is quite tricky. But I don't think the current way is ideal either.
