### ISSUE TITLE
Better search

### ISSUE THREAD

**Issue by distantnative** [getkirby/getkirby.com#798]
We can do a lot better with the search in general. Some action points:

- [x] Be more context sensitive: Prioritize areas of website depending on where the user currently is
- [x] Instead of UID show type/area in info line
- [x] For certain areas also show parent in info line (e.g. "Helpers")
- [x] On detail page: group by type/area #623
- [x] Allow to pre-filter by area in search input, instead of searching whole site
- [x] Index whole reference (all classes), maybe with advanced toggle #638

**Comment by mrflix** [comment]
- [ ] show guids as first result

**Comment by distantnative** [comment]
@mrflix I think that is not the best as general
Rule. We should be context sensitive. If you are in the Reference, likelihood that you are searching for another Reference entry is a lot higher

**Comment by mrflix** [comment]
Finding guids from within the reference is actually my point. As a Kirby developer I usually always have the reference open. There I often search for parts outside the reference. For example the blueprints guide. Search for that from within the reference and from outside. Outside the reference, the guide appears in the first results. From within the reference its not visible and it also not possible to search for 'blueprints guide'.

**Comment by plagasul** [comment]
I was searching for image dimensions or orientation (there was a k2 method) and could not find $dimensions class because it is not searchable, as stated here:

https://forum.getkirby.com/t/classes-not-searchable-in-reference/17930

**Comment by moritzebeling** [comment]
> Be more context sensitive: Prioritize areas of website depending on where the user currently is

Very nice idea! But: That also could mean that the best results get a penalty, when you’re not on the right place in the website. Instead maybe the search results could show a tag or category, e.g. `guide`, `docs`, `plugin`, ... so it is easier for users to contextualize the results
