### ISSUE TITLE
News: add Kosmos thumbs and teaser

### ISSUE THREAD

**Issue by distantnative** [getkirby/getkirby.com#810]
Let's start with pulling in the first image as a preview

**Comment by bastianallgeier** [comment]
Looks instantly more interesting … 

![Screenshot 2020-01-14 at 16 47 22](https://user-images.githubusercontent.com/24532/72358880-926d3100-36ed-11ea-8298-704cfa0249fd.png)

**Comment by distantnative** [comment]
It does!

Should we leave the dummy blind text or add actual teasers?

**Comment by texnixe** [comment]
What do we want as teaser text? Currently, hidden behind what looks like dummy text is the newsletter intro text. We could either use that and remove/adapt the styles, or mention some of the content links in short form. But if we do that, we have to go through the newsletters again. Using the intro is the cheapest way.
