### ISSUE TITLE
Guide: split up "Get advanced" section on overview

### ISSUE THREAD

**Issue by distantnative** [getkirby/getkirby.com#819]

**Comment by texnixe** [comment]
How would we split them?

Group 1:
- configuration
- database
- routing
- emails
- caching

Group 2:
- Virtual pages
- API
- Plugins

...

**Comment by distantnative** [comment]
Your groups sound good - would maybe adjust the order slightly (based on my estimation what users are more likely to use) and add a third:

Group 1: "Adapt to your needs"
- configuration
- routing
- emails
- caching
- database

Group 2: "Get advanced"
- Virtual pages
- API
- Plugins
- Sessions

Group 3: "Be secure"
- Security
- Kirby & Privacy
- Troubleshooting

I don't like my names, but I wanted to start with ideas XD

**Comment by texnixe** [comment]
I'd put the Troubleshooting section further up into the Get started section. It's pretty useless to have it all the way down there where nobody will ever find it.

Totally agree on the third group otherwise.

**Comment by distantnative** [comment]
@texnixe true, that's a good point!

GET STARTED
- Get up and running
- Explore the Starterkit
- Troubleshooting

GET PRODUCTIVE
- Content
- Templates
- Blueprints
- Languages
- Users

ADAPT TO YOUR NEEDS
- configuration
- routing
- emails
- caching
- database

GET ADVANCED
- Virtual pages
- API
- Plugins
- Sessions

BE SECURE
- Security
- Kirby & Privacy

**Comment by distantnative** [comment]
Thoughts on the names?

**Comment by texnixe** [comment]
Maybe stick with the "Get" stuff throughout:

- GET STARTED
- GET PRODUCTIVE
- GET ADVANCED
- GET PRO
- GET SECURE

**Comment by distantnative** [comment]
👍 

I only have access to Github right now and I don't want to create 20 individual commits, so for tonight:
- [x] Update https://github.com/getkirby/getkirby.com/blob/master/content/1_docs/1_guide/documentation.txt accordingly
- [x] Rename subfolders to match new order
