### ISSUE TITLE
Since badges: only show in yellow for last major version

### ISSUE THREAD

**Issue by distantnative** [getkirby/getkirby.com#821]
<since> Badges: only in yellow if within last major version, if older show the badge in grey (moderate attention)

**Comment by texnixe** [comment]
I'd really like to get rid of these left borders…

**Comment by distantnative** [comment]
@texnixe Do you have a suggestion how to display the extend of the since block (what is part and where the normal content starts again)?

**Comment by texnixe** [comment]
Die müssten halt jeweils ein durch eine Überschrift definiertes Kapitel bilden, wie z.B. in der [Vue.js Doku.](https://vuejs.org/v2/guide/components-custom-events.html#sync-Modifier)

**Comment by distantnative** [comment]
@texnixe 

Was hältst du ganz schlicht davon?
<img width="750" alt="Screen Shot 2020-01-14 at 19 20 07" src="https://user-images.githubusercontent.com/3788865/72370662-05cd6d80-3703-11ea-848d-c126ecf721d9.png">

und für ältere Versionen:

<img width="669" alt="Screen Shot 2020-01-14 at 19 20 42" src="https://user-images.githubusercontent.com/3788865/72370686-0ebe3f00-3703-11ea-88f1-6fdd619a18d5.png">

**Comment by texnixe** [comment]
Ja, so hatte ich mir das vorgestellt.

**Comment by distantnative** [comment]
Dann schau ich mal, dass ich noch die PHP-Logik zur Versionsunterscheidung rausschraube und dann kommt das auch.
