### ISSUE TITLE
Announce v2 EOL in v2 docs

### ISSUE THREAD

**Issue by distantnative** [getkirby/getkirby.com#829]
- [x] v2 docs
- [x] v2 READMEs

**Comment by bastianallgeier** [comment]
Ok, I think I already did that by adding December 31st, 2020 to the 2.5.13 release messages.

**Comment by bastianallgeier** [comment]
![Screenshot 2020-01-14 at 16 22 55](https://user-images.githubusercontent.com/24532/72357663-a1eb7a80-36eb-11ea-831d-6d64e9ecdc3e.png)
