### ISSUE TITLE
v2 Docs checklist

### ISSUE THREAD

**Issue by bastianallgeier** [getkirby/getkirby.com#835]
- Change PHP requirements on https://k2.getkirby.com/docs/installation/download 
- Change Download-Info to getkirby-v2-org + ("Kirby 2 is no longer actively supported, but you can still find the source code on GitHub").
- Add banner to all v2 docs pages

**Comment by distantnative** [comment]
@lukasbestle since you did the EOL PR recently, are these still relevant? I guess so?

**Comment by lukasbestle** [comment]
Yes, I think so, even more now that it's EOL. But only @bastianallgeier has access to the code behind k2.getkirby.com. Maybe we should also update k1.getkirby.com while we're at it.
