### ISSUE TITLE
Try: Maybe swap screenshot with one of the Demokit?

### ISSUE THREAD

**Issue by lukasbestle** [getkirby/getkirby.com#856]
Proposed by @johannschopplich in Slack:

> Compared to the screenshot of the starter kit, I consider the new overview page of the demo kit more attractive as well as more meaningful. It would be worth changing as I’d feel more appealed as a new user. Maybe even allow the link to point directly to a new instance when clicking the image?

**Comment by bastianallgeier** [comment]
✅
