### ISSUE TITLE
Add anchors to h3

### ISSUE THREAD

**Issue by medienbaecker** [getkirby/getkirby.com#88]
You can already link `h2` headers like https://nnnnext.getkirby.com/docs/guide/blueprints#general-blueprint-options

It's not possible to link `h3` headers, though. Looking at the example above it would be very useful, though. Maybe even combined with the possibility to [link to tabs](https://github.com/k-next/getkirby.com/issues/87).

**Comment by distantnative** [comment]
@medienbaecker do you still think this would be benificial? We have tried to organize the content so that the h2 tags define main sections.

**Comment by distantnative** [comment]
I will close this for now. Please feel free to reopen if there is still need for this.

**Comment by texnixe** [comment]
I would actually like to see links on h3 tags, would make it easier to link to specific parts of the docs

**Comment by distantnative** [comment]
✅

**Comment by distantnative** [comment]
Had to revert it as it caused a lot of issues with other elements.

**Comment by bastianallgeier** [comment]
I finally merged the PR for this after making a few additional changes. I think it should be pretty solid now.
