### ISSUE TITLE
Hotkey: search on `/`

### ISSUE THREAD

**Issue by bnomei** [getkirby/getkirby.com#882]
https://getkirby.com/docs/guide

a lot of docs do that recently and i found myself pressing "/" at kirby docs expecting the search input field to be focused. here is a small jquery/zepto snippet that does the trick. the if clause prevents jumping if focus is a input/textarea so a `/` char can be typed in search field.

```js
// bind 'jump to search' "/" hotkey
  if ($('#search').length > 0) {
    $(document).on('keypress', function (e) {
      let tag = e.target.tagName.toLowerCase();
      if (e.which === 47 && tag !== 'input' && tag !== 'textarea') {
        $('#search').focus();
        e.preventDefault();
      }
    });
  }
```

**Comment by bastianallgeier** [comment]
✅
