### ISSUE TITLE
Cookbook: Highlight contributor/author section with a special styling

### ISSUE THREAD

**Issue by yandodov** [getkirby/getkirby.com#884]
Recently, I made a Medium article importer for Kirby and asked @texnixe if I could write a Cookbook recipe about it because it was a very simple showcase of a section plugin. She agreed and we also talked about Xdebug and me writing a recipe about that as well...

I want to make these recipes, but I also have a ton of work at [Oblik Studio](https://oblik.studio/). We're striving to increase our presence on the web and I'd get much more encouragement from my team to take the time for these recipes if we had our name somewhere in them. Do you think that could happen?

Reasons I think that would be great:

- Other people would be more interested in contributing to recipes as well
- If something's not clear, you could ask the author for more assistance in the forum, for example. In turn, the author could edit the recipe to make it more clear for others
- It would make Kirby more transparent - you'd see the actual people behind that content. I believe that would be beneficial for both the authors _and_ Kirby

**Comment by lukasbestle** [comment]
We already add the authors to contributed cookbook recipes. It is very important to us that authors are credited properly.

We plan to make the author section more visible by styling it differently from the recipe text. That will come with an upcoming site refactor.

**Comment by texnixe** [comment]
I think we can close this?
