### ISSUE TITLE
Add date handler or a note in "Sitemap for search engines" recipe

### ISSUE THREAD

**Issue by lukasleitsch** [getkirby/getkirby.com#885]
In the recipe "Sitemap for search engines" the date for `<lastmod>` will be generated with the following line: 

```php
<lastmod><?= $p->modified('c') ?></lastmod>
```

If the date handler was changed in the config this output is not working. The function `->modified` accepts a handler as a second parameter. After adding the handler everything works as expected.

```php
<lastmod><?= $p->modified('c', 'date') ?></lastmod>
```

What do you think about adding this line to the docs or add a small note?

**Comment by texnixe** [comment]
Thanks @lukasleitsch for pointing this out. Fixed.
