### ISSUE TITLE
Document icons plugin

### ISSUE THREAD

**Issue by bnomei** [getkirby/getkirby.com#896]
i want to add a few more (purchased) nucleo icons to the panel.

like

- textfield: icon
- page blueprint: icon

**Comment by bnomei** [comment]
@distantnative i will use the nucleo as well but the svg string does not work raw, nor image optimized, nor if it try to remove stroke and fills manually. can you share how to prepare the svg string to make it work?

**Comment by distantnative** [comment]
Can you post the string that you currently are trying?

**Comment by bnomei** [comment]
got it working. i had to properly configure the nucleo app export.

![Screenshot 2020-03-09 at 13 05 48](https://user-images.githubusercontent.com/3265642/76215485-c0ab5080-6206-11ea-9cf2-4b7e1b8e6b43.png)
