### ISSUE TITLE
Docs: site->modified() and site->index()

### ISSUE THREAD

**Issue by bnomei** [getkirby/getkirby.com#915]
https://getkirby.com/docs/reference/objects/site/modified

maybe add a warning that this might take (very) long for websites with more than a few content pages. same could be applied for `site->index()` i guess.

**Comment by texnixe** [comment]
We already have a warning for `$site->index()`, but might make sense for `modified()` as well.

Edit: Shouldn't modified be a lot faster though, because it doesn't run through the complete index inclusing all files (as the index does?)

**Comment by bnomei** [comment]
> Gets the last modification date of all pages in the content folder.

**Comment by bnomei** [comment]
maybe its faster but it still killed my 3k pages setup :D
