### ISSUE TITLE
Document Panel $events bus

### ISSUE THREAD

**Issue by yandodov** [getkirby/getkirby.com#928]
I wanted to do something in my custom panel section whenever the page is updated. After a quick search in the Kirby source, I found out I can do that with:

```js
this.$events.$on('model.update', ...)
```

I saw a lot more useful hooks there. You should add them in the docs.

**Comment by distantnative** [comment]
We should probably first finish our refactoring of the event bus, so it is actual useful for developers.

**Comment by distantnative** [comment]
Closing in favor of bigger project https://github.com/getkirby/getkirby.com/issues/1137
