### ISSUE TITLE
Error in plugin search page

### ISSUE THREAD

**Issue by ghost** [getkirby/getkirby.com#943]
Searching  _Video_ in plugin page gives 3 results. In these results there is a plugin from _schnti_ and an other from _hashandsalt_ . Opening both links to preview plugin gives the same content (_hashandsalt plugin_) but not the same url.

**Comment by texnixe** [comment]
Thanks for reporting. the plugins have the same slug, so there's something going wrong with fetching the right repo info.

**Comment by texnixe** [comment]
Weird, in my local copy everything is correct. Maybe a caching issue on the server.

**Comment by texnixe** [comment]
Closing this as it works now.

**Comment by texnixe** [comment]
Hm, weird, still not fixed online, although locally it works ok, @bastianallgeier?

**Comment by distantnative** [comment]
We're using different cache types locally vs. online. Maybe that's related?

**Comment by distantnative** [comment]
I would assume that this line is the origin:
https://github.com/getkirby/getkirby.com/blob/master/site/models/plugin.php#L17

Just using the `slug` is probably the cause. Instead we might use `id()`, @bastianallgeier?

**Comment by distantnative** [comment]
Yep, I think this solved it.
