### ISSUE TITLE
Image props can not be found in docs

### ISSUE THREAD

**Issue by bnomei** [getkirby/getkirby.com#951]
like `isPortrait`

https://github.com/getkirby/kirby/blob/785e941e41dfbfaa4fe8d43a7c130302bde4539a/src/Image/Image.php#L174

**Comment by distantnative** [comment]
duplicate https://github.com/getkirby/getkirby.com/issues/666

**Comment by bnomei** [comment]
number of the beast. nice. :D

**Comment by distantnative** [comment]
For a reason 🙈😆
