### ISSUE TITLE
Docs: extensibility - handlers & parsers

### ISSUE THREAD

**Issue by distantnative** [getkirby/getkirby.com#96]
You can now extend even more core functionalities with the following new options:

- markdown.parser
- smartypants.parser
- css.handler
- js.handler
- date.handler

Those options can now take callbacks, which you can use to setup your own Markdown parser (if you are not happy with Parsedown i.e.) or to modify the js() and css() helpers to - let's say - create a cache busting plugin. BTW: I've already done that: https://github.com/getkirby/plugins/tree/develop/cachebuster :)

Check out the Kirby class for the base implementation to get started.

**Comment by bastianallgeier** [comment]
This is also covered by the new options list.
