### ISSUE TITLE
Docs: Permission "hide"

### ISSUE THREAD

**Issue by Pandorrrrrra** [getkirby/getkirby.com#987]
I think the permission "hide" should be "read"? I tried both in Kirby 3.3.5 and only "read" worked.
https://getkirby.com/docs/guide/users/permissions#role-based-permissions-in-user-blueprints

```
pages:
  …
  hide: true
  …
```

**Comment by lukasbestle** [comment]
You are right – the list of permissions in the docs is currently outdated.

I have already [fixed it on the branch for the 3.4.0 release](https://github.com/getkirby/getkirby.com/commit/ad751672ce037a26c68362ff63c3c53b760fdafe), which will be live on the site soon.
